### ISSUE TITLE
Adaptation options data model for screening, round 2

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/csis#100]
Related to: https://github.com/clarity-h2020/csis/issues/19, https://github.com/clarity-h2020/csis/issues/77

I thought that I'm finished with this, but @humerh has just reported that the "local effects change" can not be the same for all relevant land use categories.
In practical terms, this means that we need a possibility to state that albedo will be 0.5 for "buildings", 0.6 for "low urban fabric" and 0.4 for the "dense urban fabric".

Of course, this is already possible to do but in a way that would lead to inflation of the adaptation options, which would make them more difficult to use for the end users. 

I am not sure what to do here. Of course, I could change the data model and yes, this would probably be an improvement. On the other hand, there is nothing that we can't demonstrate with the current model so changing it would not significantly change our ability to demonstrate that calculating the effect of adaptation options in the screening works.

@stefanon : what do you think about this?

**Comment by patrickkaleta** [comment]
> I am not sure what to do here. Of course, I could change the data model and yes, this would probably be an improvement. On the other hand, there is nothing that we can't demonstrate with the current model so changing it would not significantly change our ability to demonstrate that calculating the effect of adaptation options in the screening works.

Agreed. So I'm just putting it on hold for now.

**Comment by DenoBeno** [comment]
This is not relevant anymore, I'll open a different ticket to explain what really needs to be done.
