### ISSUE TITLE
Should we revise the "Data" tab?

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/csis#102]
related to https://github.com/clarity-h2020/emikat/issues/16

I have recently implemented the "table views" for the vulnerability and for the adaptation options. These views just show the available "data" and allow users to include this data in the report.

What "include in the report" means is an interesting question. In some cases it simply means that the report should contain more information about this data set. In other, it may influence the calculations.

Questions: 
1. Should these "tables" appear under "data" tab? If not, what should?
2. Should we revise *all* data tabs in this way?

**Comment by DenoBeno** [comment]
Current work on "URL variables" (see https://github.com/clarity-h2020/data-package/issues/47) may allow us to drastically lower the number of resources listed per data package, thus making the "data" tabs under "hazard", "local effects" and "element at risk exposure" steps more manageable and eliminating the need to redesign them. 

Furthermore, the see https://github.com/clarity-h2020/csis/issues/101 will eventually allow users to also limit the number of resources shown in table and map tabs...

I'm still not sure what to do with "data" tabs under "vulnerability" and "adaptation options". Putting this on hold.

**Comment by p-a-s-c-a-l** [comment]
Can this be closed?

**Comment by p-a-s-c-a-l** [comment]
Duplicate of https://github.com/clarity-h2020/csis/issues/146
