### ISSUE TITLE
Report bugs, things to improve

### ISSUE THREAD

**Issue by claudiahahn** [clarity-h2020/csis#104]
@p-a-s-c-a-l, I have opened this issue to be able to report small things regarding CSIS. Feel free to put the content somewhere else, but I think it is helpfull to collect comments from people/ partners who start using CSIS somewhere. I have entered my other comments in already existing github issues (hopefully the right ones).  

https://csis.myclimateservice.eu/study/1/step/3/view/introduction#sdfootnote1sym
- Reference 1 and 2 not correct  I guess (link to copernicus website and eurostat should be there, instead: modelling framework paper and lessons learned from 2007 uk flood?)

**Comment by DanielRodera** [comment]
Thank you @claudiahahn  for reporting the issue, I have changed the references

**Comment by claudiahahn** [comment]
@DanielRodera Thank you!

**Comment by claudiahahn** [comment]
Very small issue: "maintenance" is spelled wrong on the following page: 
https://csis.myclimateservice.eu/study/35/step/1525/view/introduction: 
"Overviews of of already defined nodes of different types are available under "Mainteinance""

It should be maintenance, instead of "mainteinance" and "of" instead of "of of"

**Comment by p-a-s-c-a-l** [comment]
done

**Comment by claudiahahn** [comment]
It is not possible to unselect a map after selecting one. 
I wanted to look at different hazard maps. But when selecting one map under "wet periods" it is not possbile to unselect. It is possbile to choose another map under "wet periods" but if I want to have a look at heat instead, the map under "wet periods" is still selected and the legend of the heat index will be displayed on top - so you cannot see the whole legend

**Comment by claudiahahn** [comment]
![screenshot_notPossibleToUnselectMap](https://user-images.githubusercontent.com/45260352/72813425-93f5a680-3c63-11ea-8627-1b8259404b08.png)

**Comment by p-a-s-c-a-l** [comment]
Yes, that not possible. 

> It is not possible to unselect a map after selecting one.

Yes, that's not possible with (x) option boxes. We could switch back to [x] checkboxes instead of option boxes but then you would be able to select more than one layer in a group (e.g. **wet-periods**). Would that be o.k.?

**Comment by claudiahahn** [comment]
That should be ok. It is just for the user to explore the different hazard indices. With the current setting, it is not possible to fully see the legend of the second layer that was selected. With [x] checkboxes, it might  be more tedious for the the user, since he needs to actively unselect layers in one group, when displaying another one, but it would be possible to unselect all layers in one group, which seems to be necessary to view the legend of the map of interest in a proper way

**Comment by p-a-s-c-a-l** [comment]
I added to possibility to deselect (x) option boxes:

![map-component](https://user-images.githubusercontent.com/1788226/72999866-4498ad00-3e00-11ea-9d3b-af28c9a8b99c.gif)

You can try it [here](https://csis.myclimateservice.eu/apps/map-component/build/DataPackagePreviewMap/?host=https://csis.myclimateservice.eu&study_area=POLYGON%20((14.735388874433%2041.096530514014,%2014.735388874433%2040.508407371315,%2013.837759299902%2040.508407371315,%2013.837759299902%2041.096530514014,%2014.735388874433%2041.096530514014))&datapackage_uuid=14c81c77-a6f2-4419-b916-aad431f6accd&write_permissions=1&grouping_tag=taxonomy_term--eu_gl).

**Comment by claudiahahn** [comment]
That is great. Thank you!

**Comment by claudiahahn** [comment]
another comment: 
There is no description for the background layers. Would it be possible to include an information icon after every layer and if the user clicks on it there would be some information about the layer (meaning, where does it come from, referencing the source...,)? References need to be included anyway I think.

**Comment by p-a-s-c-a-l** [comment]
> There is no description for the background layers.

ATM you can find the complete description of the resources shown on the map in the "Data Tab". O.K., this is not so convenient. Perhaps we can show at least a summary of the resource description as tooltip in the layer box.

**Comment by claudiahahn** [comment]
That would be very much appreciated by the user, I think. Also refering to the data tab for more information would be helpful. 
However, so far under the data tab there are only the hazard resources, not the background layers listed.

**Comment by claudiahahn** [comment]
when clicking on one hazard layer in the data tab, the information is being shown at the bottom...but if you do not know that, you think there is no information. Would it be possible to display the information right below the resource, that was selected?

**Comment by p-a-s-c-a-l** [comment]
@patrickkaleta @fgeyer16 
See comment [above](https://github.com/clarity-h2020/csis/issues/104#issuecomment-578646346). Would that be possible? Claudia is right, the current behaviour isn't very user-friendly.

**Comment by claudiahahn** [comment]
under the "exposure evaluation" tab: when selcting population, the unit above the legend is "days".
![wrongUnit_inMap](https://user-images.githubusercontent.com/45260352/73461511-8edada80-437a-11ea-8109-e2887ba7b686.PNG)

**Comment by p-a-s-c-a-l** [comment]
> under the "exposure evaluation" tab: when selcting population, the unit above the legend is "days".

AFAIK the legend is generated by EMIKAT WMS, so this has to be changed by @humerh

**Comment by humerh** [comment]
Currently this link goes to "meteogrid-Service". So I must forward this issue to @ghilbrae

**Comment by ghilbrae** [comment]
I've checked all the layers related to population on geoserver and none has that style.

I've checked the population at Exposure Evaluation for the Example northern EU study and what I've found is that the layer being shown for population is this one:

https://clarity.meteogrid.com/geoserver/europe/wms?&service=WMS&request=GetMap&layers=europe%3API_rx5day_rcp85_20710101-21001231_ensmean&styles=&format=image%2Fpng&transparent=true&version=1.1.1&width=1536&height=1536&srs=EPSG%3A3857&bbox=2343253.5391103635,7651040.783233002,2357929.4485411174,7665716.692663757

So I'm either looking at the wrong study or that layer is not the one that should be.

**Comment by patrickkaleta** [comment]
> I've checked all the layers related to population on geoserver and none has that style.
> 
> I've checked the population at Exposure Evaluation for the Example northern EU study and what I've found is that the layer being shown for population is this one:
> 
> https://clarity.meteogrid.com/geoserver/europe/wms?&service=WMS&request=GetMap&layers=europe%3API_rx5day_rcp85_20710101-21001231_ensmean&styles=&format=image%2Fpng&transparent=true&version=1.1.1&width=1536&height=1536&srs=EPSG%3A3857&bbox=2343253.5391103635,7651040.783233002,2357929.4485411174,7665716.692663757
> 
> So I'm either looking at the wrong study or that layer is not the one that should be.

You can find the problem in the Exposure step in this study: https://csis.myclimateservice.eu/study/18/step/1904/view/maps

when you select the "European population distribution" layer, 3 requests are sent to clarity.meteogrid. One of them is for the wrong legend: https://clarity.meteogrid.com/geoserver/europe/wms?service=WMS&request=GetLegendGraphic&version=1.1.0&format=image%2Fpng&width=20&height=20&layer=europe:PI_rx5day_rcp85_20710101-21001231_ensmean&style=

**Comment by ghilbrae** [comment]
Yes I've noticed, the thing is that neither of those requests are requesting population, they are all referred to PI_rx5day_rcp85_20710101-210001231_ensmean which is not population. So is the right layer being requested from geoserver?

**Comment by p-a-s-c-a-l** [comment]
The resource title (population) does not match the configured layer (service path): https://github.com/clarity-h2020/map-component/issues/82#issuecomment-581312847

**Comment by DenoBeno** [comment]
FYI: I have pinned this issue to https://github.com/clarity-h2020/csis/issues now so that it's easier to find it.

**Comment by claudiahahn** [comment]
Following the link “Streams in Europe” from the European datapackage list of resources  (when selecting the data package for a study) leads to the Urban Atlas link: 
 
![image](https://user-images.githubusercontent.com/45260352/74941339-228c4d80-53f3-11ea-827b-5b142c167162.png)

That is probably a mistake. Should it lead to https://land.copernicus.eu/imagery-in-situ/eu-hydro/eu-hydro-river-network-database?tab=metadata ? or where does the data come from?

**Comment by claudiahahn** [comment]
No information available for background and default layers!
Nothing is displayed for layer called “Urban Atlas 2012”
Some layers are listed twice – under default and under background layers (e.g.: Dense urban farbric spaces in Europe)

@negroscuro the "dense urban fabric" layers etc. are the old ones still, right? They were not yet updated, right?

How are the default layers defined (generated), as listed below?
1-water (UA code 50000)
2-roads (UA codes 12210,1220)
3-railways (UA code 12230)
4-trees (without STL data, only UA, that’s poor but is something at least) (UA code 3100)
5-vegetation (without ESM, only UA, that’s poor but is something at least) (UA codes 14100, 14200,32000,33000)
6-agricultural areas (UA code 20000,21000,22000,23000,24000)
7-built_up (only ESM data!) 
8-built_open_spaces (only ESM data!) 
9-dense_urban_fabric (UA codes 11100,11210)
10-medium_urban_fabric (UA code 11220)
11-low_urban_fabric (UA code 11230,11240,11300)
12-public_military_industrial (UA code 12100)

Original Urban Atlas Codes:
![image](https://user-images.githubusercontent.com/45260352/75341089-fc076000-5893-11ea-9251-3366c3bbfa84.png)

**Comment by claudiahahn** [comment]
can someone provide the meta data (references/sources) for the background and default layers? 
I might need that for the workshop in Linz. 

Why is there a differentiation between background and default layers?
are the default layers being used for the advanced screening (local effect calculation) and the background layers available just for additional information?

**Comment by p-a-s-c-a-l** [comment]
> No information available for background and default layers!

Yes, [Background Layers](https://csis.myclimateservice.eu/taxonomy/term/5238) are present in all EU-GL Steps. They are not specifically listed on the [Data Tab](https://csis.myclimateservice.eu/study/33/step/1513/view/data) of a particular step, because they aren't assigned to a particular step. 

> Why is there a differentiation between background and default layers?

Sorry, the term 'default' is misleading, as explained also [here](https://github.com/clarity-h2020/map-component/issues/84#issuecomment-584046575). Usually, non-background layers are grouped according to the *[hazard](https://csis.myclimateservice.eu/admin/structure/taxonomy/manage/hazards/overview)* the respective resource has been assigned to.  If this assignment is missing, they are added to a group named 'default'.

**Comment by claudiahahn** [comment]
> Yes, Background Layers are present in all EU-GL Steps. They are not specifically listed on the Data Tab of a particular step, because they aren't assigned to a particular step.

Information about the background layers should still be listed somewhere, I think. Why not displaying it under the data tab as well? or/and including an info button behind each layer, which links to the description (references etc.) of the layers (as discussed before here). That was just discussed with @DenoBeno @mattia-leone @RobAndGo

**Comment by p-a-s-c-a-l** [comment]
Information on Background Layers is available in the [data package](https://csis.myclimateservice.eu/node/682/), but currently this information is not shown in the study:

![grafik](https://user-images.githubusercontent.com/1788226/75784524-9a973380-5d62-11ea-99d4-cbf96fa04e60.png)

So perhaps we could include  the the data package view in the data tab of the study. WDYT @patrickkaleta ?

**Comment by patrickkaleta** [comment]
> Information on Background Layers is available in the [data package](https://csis.myclimateservice.eu/node/682/), but currently this information is not shown in the study:
> 
> ![grafik](https://user-images.githubusercontent.com/1788226/75784524-9a973380-5d62-11ea-99d4-cbf96fa04e60.png)
> 
> So perhaps we could include the the data package view in the data tab of the study. WDYT @patrickkaleta ?

I agree. The current Data tab doesn't provide enough information about the DP and it's resources. I added a "Data" display mode to the [DP](https://csis.myclimateservice.eu/admin/structure/types/manage/data_package/display/data) and [DP_resource](https://csis.myclimateservice.eu/admin/structure/types/manage/data_package_metadata/display/data) entities, which control what is shown on the Data tab of the Study.

So ATM the Data tab of the Study shows (more or less) exactly what you would get when viewing the [DP ](https://csis.myclimateservice.eu/node/682/) directly. We can change that via the two display modes I mentioned above.

**Comment by DenoBeno** [comment]
I have just tried to set up a new "advanced screening" study. This is what I got:

https://csis.myclimateservice.eu/study/118/view/context

![image](https://user-images.githubusercontent.com/2961790/76311565-89ee3c80-62d1-11ea-8312-b26ec08acdef.png)

That's new and not a good sign. What happened here?

**Comment by DenoBeno** [comment]
"Toggle edit" on "Area" step when defining the study should have some visual effect apart from just adding the edit possibility in the map. As it is, it's quite confusing - users will not be sure if pressing the button did anything.

**Comment by DenoBeno** [comment]
Related to https://github.com/clarity-h2020/csis/issues/104#issuecomment-597055733, I have configured the service to use these template names as step names ages ago. This worked well AFAIK and allowed us more flexibility, e.g. to use the acronyms as step names in study "menu" buttons. 

Why was this reverted to use the default names form the taxonomy again?

**Comment by claudiahahn** [comment]
this is just a test for me (because I have accidentally clicked on the unsubscribe button...)

**Comment by DenoBeno** [comment]
Strange, I thought that I have posted a report complaining about the color coding of the hazard indice maps earlier today here. In short, my recommendation is to use multicolor coding, but to avoid repeating similar colors as it's the case now (dark blue, light blue, dark blue, light bluish/turquoise). We still have maps where most of the map is just a single color.

In the meantime, I have also discovered further errors:
- snow days is not showing anything.
- Highest 1-day/5 day precipitation figures are in days, suppose they should be in mm?

**Comment by DenoBeno** [comment]
@claudiahahn, @mattia-leone : What is T_A? Ambient or apparent temperature? Ins what does this mean? (if "apparent", how is this different from UTCI?)

**Comment by p-a-s-c-a-l** [comment]
>  In short, my recommendation is to use multicolor coding, but to avoid repeating similar colors as it's the case now (dark blue, light blue, dark blue, light bluish/turquoise).

Colour Coding is something that has to be implemented in GeoServer (SLD). Now that layers are [moved from METEOGRID to ATOS](https://github.com/clarity-h2020/ckan/issues/23) this issue could be addressed by @DanielRodera

**Comment by RobAndGo** [comment]
Hi @DenoBeno,
T_A refers to "Apparent Temperature" and is defined as:  

T_A = 0.716 x UTCI - 1.48

That is, the apparent temperature, which is the temperature felt by humans, is correlated with the UTCI using the above relation (taken from a paper _Blazejczyk, K., Epstein, Y., Jendritzky, G., Staiger, H., & Tinz, B. (2012). Comparison of UTCI to selected thermal indices. International journal of biometeorology, 56(3), 515-535._)

Note that here, UTCI and T_A only consider the air temperature and relative humidity.

I think the reason that both are supplied is in case the users are more familiar with using one or the other.

**Comment by RobAndGo** [comment]
@DenoBeno 
I think the problem with the "snow days" is that the data has not been processed yet by Meteogrid (@ghilbrae @LauraMTG). That is, the data is not available on the Meteogrid geoserver:
https://clarity.meteogrid.com/geoserver/web/wicket/bookmarkable/org.geoserver.web.demo.MapPreviewPage?3

This was one of the last data sets that I uploaded and can be found on the clarity ftp here:
/clarityftp/europe/hazard_indices/precipitation/snow-days

And you are correct in that the units of the "Highest 1-day/5 day precipitation" should be in mm. In fact, this is something which I forgot to do for each index - that is I need to add the units for each index in the description.   ![foreheadslap](https://user-images.githubusercontent.com/45385637/78253004-00a6e000-74f4-11ea-8cb8-bf19269ff236.gif)

**Comment by DenoBeno** [comment]
thanks

**Comment by DenoBeno** [comment]
Last week, I have stumbled into a very strange issue. It's IMO almost a "showstopper", but more interestingly, it's something I have never seen in Drupal except on CSIS.

**- paging links aren't shown**

E.g. on https://csis.myclimateservice.eu/adaptation-options, first 25 adaptation options are shown but no links to the next page is presented to users. 

Probably the same in https://csis.myclimateservice.eu/solution-offers and https://csis.myclimateservice.eu/showcases - I didn't check if they have paging enabled or not.

As long as the number of elements is small, we can use "show all" option, but this needs to be addressed.

**Comment by patrickkaleta** [comment]
> Last week, I have stumbled into a very strange issue. It's IMO almost a "showstopper", but more interestingly, it's something I have never seen in Drupal except on CSIS.
> 
> **- paging links aren't shown**
> 
> E.g. on https://csis.myclimateservice.eu/adaptation-options, first 25 adaptation options are shown but no links to the next page is presented to users.
> 
> Probably the same in https://csis.myclimateservice.eu/solution-offers and https://csis.myclimateservice.eu/showcases - I didn't check if they have paging enabled or not.
> 
> As long as the number of elements is small, we can use "show all" option, but this needs to be addressed.

Took care of that. If such an error occurs, just remove remove the pager and add it back again.

**Comment by DenoBeno** [comment]
I have tested the options we have for the simple screening and encountered several issues. Most, if not all of these have been reported by me before but nothing has changed so far:

See https://csis.myclimateservice.eu/study/138/step/4143/view/summary for examples I have in mind.

First, OUR SCALES ARE TERRIBLE. I have reported this before, again and again, but nothing changes.

1. A scale that starts with blue, then changes to purple and then back to blue, before starting to change colors is a sheer madness. How an I supposed to differentiate between lower and upper blue?
2. A "consecutive something days" scale that goes from 0 to 200 is IMO quite useless too. If I have more than 100 consecutive dry days, that's 3 months without rain. Any forest that I might still have *will* burn, like it does in Italy these today. How about consecutive summer days?
Consecutive 
3. Rainfall values are still in days (should be mms, e.g. for "maximal 5 days percipitation")
4. CLC2012 layers are unreliable. Sometimes I get them, sometimes not.
5. Our input layers still don't show up in the screenshot.

**Comment by p-a-s-c-a-l** [comment]
Styles/Scales are configured on GeoServer. Maybe @DanielRodera is able to address his with help from @RobAndGo.

> Second, CLC2012 layers are unreliable. Sometimes I get them, sometimes not.

We could try to import CLC into ATOS GeoServer instance , so we have full control over it. Means, we can also change the legend. CLC should be available as open data (Shapfile, etc.).

> Third, our input layers still don't show up in the screenshot.

Yes, they are still loaded from the old GeoServer which does not have http**s** enabled. This will be resolved [soon](https://github.com/clarity-h2020/ckan/issues/23#issuecomment-630849875).

**Comment by RobAndGo** [comment]
I thought this may be a problem of links not being correct after the migration to the new geoserver by METEOGRID? I thought this was mentioned on Monday by @ghilbrae and that any issues should be reported to her.

**Comment by p-a-s-c-a-l** [comment]
It is correct that the *new* GeoServer is currently lacking the styling ('scales').

But the migration is not done yet. We still use the old instance. So this an independent problem with the current styling.

**Comment by ghilbrae** [comment]
We are updating the layers with the correct styles this week, so you'll find layers with correct styles and layers without.
A different matter is that there may still be layers, even updated ones, that may have styles that you don't like or that could be improved in some ways. That is something that we know nothing about, we'd need you to tell us exactly which layers and which scale/style you want for them.

**Comment by p-a-s-c-a-l** [comment]
closing this 'mega issue' in favour of more focussed ones.
