### ISSUE TITLE
Data view needs to be improved

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/csis#106]
Two issues: 

1) duplication of content.
2) we should (?) also include the "pseudo-resources" - adaptation options and vulnerabilities

**Duplication of content**
![image](https://user-images.githubusercontent.com/2961790/65759496-61a3c480-e11b-11e9-973e-4b3cce826b5e.png)

"Local effect apparent temperature" is listed 3x because it's featuring three tags that are relevant for this step: "heat wave", "consecutive summer days" and "heat wave duration". This view then produces three lines for the resource based on these three tags (I have added a content in parentheses to show what is going on. Originally it was just 3x the same title.):
- https://csis.myclimateservice.eu/admin/structure/views/view/step_data_collection/edit/entity_view_3

**Questions:** 
1. Should the resource reference only  one of them or not?
- Pro: if only one of these tags remains, the data view will not show duplicates.
- Contra: I don't know which one to keep. Probably other users will have the same problem.
2. do we even need such a complex view? After all, we aren't presenting the data hierarchically anyway. If we don't care about the hierarchy, it would be easier to avoid the duplication.

**Pseudo resources**

Adaptation options and vulnerabilities could IMO be shown as a flat list rather than as a hierarchy. That could be done e.g. by attaching a simple(r) view with AOs & vulnerabilities to the existing data view. 

One more question: why isn't this attached to the page in the same way as tables are? If it were, we could easily have per-step data views...

**Comment by DenoBeno** [comment]
Update: in the "hazard characterization" step, the hierarchy is still shown, see illustration.
From https://csis.myclimateservice.eu/study/1/step/2/view/data 

![image](https://user-images.githubusercontent.com/2961790/65761939-28218800-e120-11e9-8f8d-3f926962aff7.png)

And the number of duplicates here is astonishing...
In exposure evaluation step too.

![image](https://user-images.githubusercontent.com/2961790/65762103-7fbff380-e120-11e9-9ef4-ba001204da50.png)

I have no clue why this isn't the case in "local effects" data tab. Also the input data for the local effects is not shown anymore. E.g. roads, railways, built up area etc.

**Comment by DenoBeno** [comment]
@fgeyer16 : we will need to fix this one of these days. Maybe not you, but we need to at least clarify what is the best way to handle this before assigning it to anyone. Any suggestions?

**Comment by patrickkaleta** [comment]
The original idea of some sort of hierarchy goes back to the days when we used the Mock-up as a reference. But that would only work if resources would be assigned **exactly one** relevant tag. If they can have multiple ones, I don't know how we could build a hierarchy with a simple enough logic, so that it can be done inside a View.

So, before we show the same resource 2-3 times, or try to come up with a complicated logic that could build a hierarchy, I would rather drop this and instead show a simple list or table with the included tags right next to each resource and add a filter function on top of the page.
<br>
 > @fgeyer16 : we will need to fix this one of these days...

Agreed. It is not that urgent at the moment, so I'm putting this on hold.

**Comment by DenoBeno** [comment]
I also agree that flat lists would probably work better for us now. 

In the future, we should be able to lower the number of resources that need to be shown too, especially if/when we resolve teh https://github.com/clarity-h2020/data-package/issues/47 and start showing only the resources that fit the users presets as defined in https://github.com/clarity-h2020/csis/issues/101 and https://github.com/clarity-h2020/csis/issues/108.

**Comment by DenoBeno** [comment]
Please also see https://github.com/clarity-h2020/clarity-theme/issues/7
