### ISSUE TITLE
Would it make sense to upload the data that we want to visualise in tables and graphs on Drupal?

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/csis#110]
related to: https://github.com/clarity-h2020/csis/issues/98, https://github.com/clarity-h2020/emikat/issues/23

As discussed in https://github.com/clarity-h2020/emikat/issues/23, we should develop better data viewers for CSIS. then again, as presented in https://github.com/clarity-h2020/csis/issues/98 a module exists that provides several visualisation methods for CSV and some simple JSON data models.

An alternative to developing the data viewers might thus be to call the server, fetch the data, save it on the drupal site and let this module visualise it. (I can ask the author if it could also work with external data)

**Disadvantages:** need to upload the data on drupal site and less control over the visualization (although the module seems to be quite extensible - e.g. it integrates several existing libraries for data visualisation including one that shows 3D molecules in interactive viewer...)
**Advantages**: less calls to the backend servers, several nice viewers available out of the box, maybe less work for us?

WDYT?

**Comment by p-a-s-c-a-l** [comment]
I don't know. But before we redo the table component ([again](https://github.com/clarity-h2020/table-components/issues/19)), we have to be very clear about what "better data viewers" concretely means. How can the data that is currently available be better visualised? What does the user actually want to see? What is really useful? ATM, I don't know. Diagrams for ... Hazard Events? Does it make sense? 

And what happens, if the data models changes again as happened in the past? E.g. how stable is the impact result format? Before we cannot answer these questions, it's IMHO too early to discuss about a completely new approach towards tables.

IMHO the system should be made public ASAP, even with simple tables. The feedback we'll receive then from real end users outside of the project, which is BTW urgently needed for the **Validation Tasks** in WP2, can be help us to answer these questions.

**Comment by DenoBeno** [comment]
That's rather an answer to another question (https://github.com/clarity-h2020/emikat/issues/23). Here I merely wanted to point out the possibility of not having to develop our own table component at all - however, this would require us to store table/graph data on Drupal. In any case, we it's less the question of "how the table component works" and more a question of "what data should be in the table" IMO.

As for the "what users want", Rose has made some offers and we got positive feedback on these. Some of her proposals are IMO too complex but some should be relatively easy.

**Comment by p-a-s-c-a-l** [comment]
Can this be closed?

**Comment by patrickkaleta** [comment]
> ...(I can ask the author if it could also work with external data)

From the response you got from the module author on that [issue](https://www.drupal.org/project/chart_suite/issues/3086815), it seems like his module cannot work with external data (the other module he proposed as an alternative is unfortunately only available for Drupal 7).

So for this module to work, we would need to store the actual data as files on our Drupal site. Question is, how to do this and who will do it?

**Comment by p-a-s-c-a-l** [comment]
> who will do it?

closed until we find a find a volunteer
