### ISSUE TITLE
Entity Browser - "auto open EB" bug

### ISSUE THREAD

**Issue by patrickkaleta** [clarity-h2020/csis#112]
**Look what's going on when someone tries to add a new data package:**

![EB-bug](https://user-images.githubusercontent.com/42167036/66645061-c3d3ed80-ec22-11e9-8499-7ae26266f410.gif)

The problem is caused by multiple Entity Browser on the same form having the "**Auto open entity browser" option** enabled. This causes the EBs to race each other trying to be on top of the others. In the end the user cannot do anything on that form.

I disabled this option on all our Entity browsers, which fixed the problem. @DenoBeno & @fgeyer16, we shouldn't use this option in the future anymore, in order to stay clear of this error. (In the option's description it is also adviced against using this feature)

**Comment by DenoBeno** [comment]
This should be declared "best practice" and closed, no?
