### ISSUE TITLE
CSIS Production Cloud Infrastructure

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/csis#113]
Move CSIS **Production** System to Cloud Infrastructure, e.g. [pantheon.io](https://pantheon.io).

Since our highly customised CSIS Drupal instance uses some workarounds and "hacks" which need full control over web server and php configuration, it will be hard to find a cloud infrastructure that gives us enough freedom to do what we are currently doing. 

### pantheon.io:
- max. PHP Application Memory Limit: [512 MB](https://pantheon.io/pricing-comparison), starting at $225/month, atm we are using **1GB**
- [cannot modify php.ini](https://pantheon.io/docs/platform-considerations) and probably also upload.ini, but this is needed e.g. [here](https://github.com/clarity-h2020/csis-helpers-module/issues/13#issuecomment-541167667)
-  [modifications to the nginx.conf file are not supported](https://pantheon.io/docs/platform-considerations), but this is needed [here](https://github.com/clarity-h2020/docker-compose-letsencrypt-nginx-proxy-companion/blob/clarity/data/vhost.d/csis.myclimateservice.eu)
- [web server ignores distributed configuration files such as .htaccess](https://pantheon.io/docs/platform-considerations). But this is needed for our self-hosted external apps, like the map component and the table app.

**Comment by ghilbrae** [comment]
Would it make sense to look for a hosting or cloud infrastructure that offers support for Docker, like AWS or Digital Ocean?

Due to privacy or legal matters, are we looking for European-based companies only?

At Meteogrid we use a German company for hosting and services https://www.hetzner.com/

**Comment by DenoBeno** [comment]
> 
> 
> Move CSIS Drupal System to Cloud Infrastructure, e.g. [pantheon.io](https://pantheon.io).
> 
> Since our highly customised CSIS Drupal instance uses some workarounds and "hacks" which need full control over web server and php configuration, it will be hard to find a cloud infrastructure that gives us enough freedom to do what we are currently doing.
> ### pantheon.io:
> 
>     * max. PHP Application Memory Limit: [512 MB](https://pantheon.io/pricing-comparison), starting at $225/month, atm we are using **1GB**
> 
>     * [cannot modify php.ini](https://pantheon.io/docs/platform-considerations) and probably also upload.ini, but this is needed e.g. [here](https://github.com/clarity-h2020/csis-helpers-module/issues/13#issuecomment-541167667)
> 
>     * [modifications to the nginx.conf file are not supported](https://pantheon.io/docs/platform-considerations), but this is needed [here](https://github.com/clarity-h2020/docker-compose-letsencrypt-nginx-proxy-companion/blob/clarity/data/vhost.d/csis.myclimateservice.eu)
> 
>     * [web server ignores distributed configuration files such as .htaccess](https://pantheon.io/docs/platform-considerations). But this is needed for our self-hosted external apps, like the map component and the table app.

Thanks, that makes it "easier" - at least to know what we can't use. That's a pity, but it is as it is.

**Comment by Itsman-AT** [comment]
> 
> 
> Would it make sense to look for a hosting or cloud infrastructure that offers support for Docker, like AWS or Digital Ocean?
> 
> Due to privacy or legal matters, are we looking for European-based companies only?
> 
> At Meteogrid we use a German company for hosting and services https://www.hetzner.com/

We also used a dedicated server from Hetzner in another H2020 project and can recommend it.

**Comment by p-a-s-c-a-l** [comment]
OK, let's rent a root server and setup synchronisation between DEV and PROD instances.

**Comment by p-a-s-c-a-l** [comment]
There is also a possibility to run [Containers on Google Compute Engine ](https://cloud.google.com/compute/docs/containers/?hl=en) or [Running Drupal in Kubernetes](https://www.jeffgeerling.com/blog/2019/running-drupal-kubernetes-docker-production) with Docker in production.

All we need to try this out for free is $300 free trial on [Google Cloud Platform Free Tier](https://cloud.google.com/free/docs/gcp-free-tier?hl=en). I wonder if somebody already singed up for such a GCP account? Usually you need it to obtain a Google Maps API key, so @Itsman-AT perhaps?

**Comment by Itsman-AT** [comment]
> All we need to try this out for free is $300 free trial on [Google Cloud Platform Free Tier](https://cloud.google.com/free/docs/gcp-free-tier?hl=en). I wonder if somebody already singed up for such a GCP account? Usually you need it to obtain a Google Maps API key, so @Itsman-AT perhaps?

Yes, I will check back with Denis if we can just create a Clarity Google account via the project budget, should be possible,

**Comment by p-a-s-c-a-l** [comment]
We need that account in case for our GoogleMaps, even if we don't host our "containers" in google cloud platform. See https://github.com/clarity-h2020/docker-drupal/issues/55#issuecomment-574129603

**Comment by Itsman-AT** [comment]
> We need that account in case for our GoogleMaps, even if we don't host our "containers" in google cloud platform. See clarity-h2020/docker-drupal#55 (comment)

@DenoBeno : Do you see any way of financing a Clarity Google Maps account? The DRC one runs out of budget soon (around 250$ of free use are consumed now (of 300$)).

**Comment by p-a-s-c-a-l** [comment]
CSIS has been copied to the new DEV and PROD servers is nor reachable under
- https://csis-dev.ait.ac.at/
- https://csis.ait.ac.at/

[DNS entries](https://github.com/clarity-h2020/csis/issues/23#issuecomment-581776771) for [**csis-dev**.myclimateservices.eu](https://csis-dev.myclimateservices.eu) should be updated next Monday and for [**csis**.myclimateservices.eu](https://csis.myclimateservices.eu) when the [issue of synchronisation](https://github.com/clarity-h2020/csis/issues/135) has been resolved.

In the meantime I'll start moving other services like CKAN to the new servers.

**Comment by p-a-s-c-a-l** [comment]
https://csis-dev.ait.ac.at/ and https://csis.ait.ac.at/ are currently down due to some [proxy erros](https://github.com/clarity-h2020/docker-compose-letsencrypt-nginx-proxy-companion/issues/7) that have to be resolved first.

**Comment by Itsman-AT** [comment]
> down due to some proxy erros that have to be resolved first.

Anything I can help with here? Is this proxy something our ITO needs to configure?

And: I checked with our ITO and port 80 incoming should already be open.

**Comment by p-a-s-c-a-l** [comment]
@Itsman-AT no, atm nothing you can help with, thanks.

**Comment by p-a-s-c-a-l** [comment]
@negroscuro Can you please register csis-dev.myclimateservice.eu to 62.218.164.246?

**Comment by p-a-s-c-a-l** [comment]
DEV and PROD Docker hosts are now operational.
