### ISSUE TITLE
The external app: EEA Urban Adaptation City Profiles exists in different versions

### ISSUE THREAD

**Issue by therter** [clarity-h2020/csis#116]
The external application: "EEA Urban Adaptation City Profiles" exists in different versions. There should only be one version to avoid confusion. So version 1 should be removed and version 2 should be renamed.

**Comment by DenoBeno** [comment]
fine with me.

**Comment by p-a-s-c-a-l** [comment]
resolved?

**Comment by therter** [comment]
Study 35 uses the correct "EEA Urban Adaptation City Profiles" version and the versions, which should not be used have the suffix deprecated. But the bulk editor does not know the workflow step "EEA city factsheet". So I cannot filter for this step to ensure, that no other versions are used. But perhaps I can get this information from the db.

**Comment by p-a-s-c-a-l** [comment]
@therter what's the status here?

**Comment by therter** [comment]
Now, we have only one version of the "EEA Urban Adaptation City Profiles"

**Comment by DenoBeno** [comment]
can you explain me this? This should not be the case.

**Comment by therter** [comment]
The bulk editor (https://csis.myclimateservice.eu/maintenance/gl-steps) has a filter function, that can be used to filter for workflow steps. But there is no workflow step for the "City factsheets"

![Bildschirmfoto vom 2019-11-04 16-34-22](https://user-images.githubusercontent.com/1788509/68133703-2fa72e80-ff21-11e9-827b-d2940cd56e02.png)

**Comment by DenoBeno** [comment]
ah yes, configuration error. Unfortunately, this is defined in a less than robust way - has to be reconfigured whenever a new taxonomy term is added. Should probably rewrite it one day.
