### ISSUE TITLE
Configure the CSIS with some datasets

### ISSUE THREAD

**Issue by maesbri** [clarity-h2020/csis#12]
This task is linked to issue #9

**Comment by p-a-s-c-a-l** [comment]
:x: Adding sample netCDF Files to [geonode](https://github.com/clarity-h2020/docker-geonode/issues/5) failed.

**Comment by Itsman-AT** [comment]
Do you want me to have a look at the NetCDF import?

**Comment by p-a-s-c-a-l** [comment]
@Itsman-AT 
For European-level Data, I think will will work with the processed gridded data in the future, so this is not so critical if we don't show the origin data on the a map via WMS. But local data like MUKLIMO (/data/MUKLIMO_3/Linz_number_of_summerdays_1981-2010.nc ) will become the basis for custom [Data Packages](https://github.com/clarity-h2020/csis/issues/13) creation between modelling experts and end users. So we should have the ability to at least preview such data if the user orders a custom Data Package containing local hazard / exposure / vulnerability / impact maps.

I would prefer to import these NetCDF files in Geoserver, but this did not work [at all](https://github.com/clarity-h2020/docker-geonode/issues/5).
