### ISSUE TITLE
Bug in Adaptation Options View

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/csis#121]
`Warning: Invalid argument supplied for foreach() in Drupal\Core\Template\Attribute->__construct() (line 81 of core/lib/Drupal/Core/Template/Attribute.php).` at https://csis.myclimateservice.eu/adaptation-options

**Comment by patrickkaleta** [comment]
Just had a quick look at this. This bug doesn't seem to do any harm other than scaring users. It is related to [this bug report](https://www.drupal.org/project/better_exposed_filters/issues/3001967). Applying patch no.4 fixed the error in my local instance. I will enable this patch on the server.

**Comment by patrickkaleta** [comment]
Done. Error messages disappeared.

**Comment by DenoBeno** [comment]
Ah yes, that's just an useless error message.
