### ISSUE TITLE
Edit Study as Area is empty

### ISSUE THREAD

**Issue by ghilbrae** [clarity-h2020/csis#124]
Edit Study as Area has no information. Is this meant to be like that? Is it related to some info missing from some other resource or DP?

As an example https://csis.myclimateservice.eu/study/52/view/summary click on **Edit Study as Area**

![Screenshot](https://user-images.githubusercontent.com/1615745/69957653-58601b00-1503-11ea-8290-4ca1af15eb34.png)

**Comment by p-a-s-c-a-l** [comment]
Those control should not be visible to 'ordinary' users. They are for admins only.

![grafik](https://user-images.githubusercontent.com/1788226/69963429-8009b000-1510-11ea-8ebc-be0674774ffb.png)

**Comment by patrickkaleta** [comment]
So far, these controls were visible for users with roles: admin, editor or developer. To avoid any confusions, I now made them visible for admins only.
