### ISSUE TITLE
New Hazards and Hazard Indexes

### ISSUE THREAD

**Issue by ghilbrae** [clarity-h2020/csis#126]
Is it feasible to add new Hazards or Hazard Indexes to the list available in the CSIS?

So far we've identified one Hazard missing (Coastal flooding) and we might also need new Hazard Index categories for Resccue data.

**Comment by patrickkaleta** [comment]
**Just from a Drupal-side perspective**: adding new hazards (indexes) is not a problem. 
The taxonomy we use for hazards can be expanded by new hazard terms. Then we only need to update a couple of elements (Views and EntityQueues) to include these new terms. And then the new hazard can be selected in a datapackage/resource, a twin, a showcase, an adaptation option, etc etc.

I don't know what the exact consequences for our components (table- , map- and scenario analysis-component) and the external services (Emikat) would be.

**Comment by DenoBeno** [comment]
EMIKAT would simply ignore them until instructed differently.

Patrick Kaleta <notifications@github.com> schrieb am Do., 5. Dez. 2019,
11:39:

**Comment by ghilbrae** [comment]
Ok, thanks!
