### ISSUE TITLE
CSIS UI General Improvments

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/csis#127]
Here we collect some issue for improving the general usability of the CSIS.

**Comment by p-a-s-c-a-l** [comment]
![grafik](https://user-images.githubusercontent.com/1788226/70692681-22b5f180-1cbc-11ea-8d52-def27bda7331.png)

- "edit study as context" is no userfridn title
- **more important**:  a cancel button is missing!

**Comment by p-a-s-c-a-l** [comment]
![grafik](https://user-images.githubusercontent.com/1788226/70693116-11b9b000-1cbd-11ea-98fa-f850e8b6dd61.png)

If have no idea, how to change "presets". This looks like an "artefact" of a button. @DenoBeno Do you know where I can find the functionality for selecting a "preset"?

Furthermore, we have to be consistent with our own terminology. See [Ubiquitous Language](https://dzone.com/articles/importance-of-ubiquitous-language-in-domain-driven), which is also explained in detail in D4.2 CSIS Architecture. Since we are performing **Impact Scenario Analysis**, this has to be renamed to Scenario or Impact Scenario.

**Comment by p-a-s-c-a-l** [comment]
OK, I've found the possibility for changing the scenarios at https://csis.myclimateservice.eu/study/54/step/1938/view/table:
![grafik](https://user-images.githubusercontent.com/1788226/70696468-0d44c580-1cc4-11ea-9fd5-d72b0073ff70.png)

But I don't know, where this is configured so that I can add it to the [study context edit form](https://csis.myclimateservice.eu/admin/group/types/manage/study/form-display/context), too. 
Neither in [table view](https://csis.myclimateservice.eu/admin/structure/views/view/view_mode_for_gl_step/edit/page_6) not in [table display](https://csis.myclimateservice.eu/admin/structure/types/manage/gl_step/display/table) Any ideas @fgeyer16 @therter ?

**Comment by p-a-s-c-a-l** [comment]
Include in Report Button: If you press the button, the button just disappears. After some time, the edit report image comment view is shown. 

A message or a loading animation should be shown to improve user experience.

**Comment by p-a-s-c-a-l** [comment]
Have to put this in the footer:
"This project has received funding from the European Union's Horizon 2020 research and innovation programme under grant agreement No 730355 "

**Comment by p-a-s-c-a-l** [comment]
![grafik](https://user-images.githubusercontent.com/1788226/72879599-88ef5480-3cfd-11ea-9a07-e0cec3bff45e.png)

Edit Data Package -> Add existing resource -> There's no cancel button, cannot exit the modal Dialog without selecting a resource

**Comment by p-a-s-c-a-l** [comment]
There are no cancel buttons. Is this a general problem of the [theme](https://github.com/clarity-h2020/clarity-theme/issues)

![grafik](https://user-images.githubusercontent.com/1788226/73546342-5b14b900-443d-11ea-955e-91727be349b3.png)

**Comment by patrickkaleta** [comment]
> There are no cancel buttons. Is this a general problem of the [theme](https://github.com/clarity-h2020/clarity-theme/issues)?

yes, it is: https://github.com/clarity-h2020/clarity-theme/issues/11#issuecomment-543754611
I hope that the new theme update that Alejandro is working on (according to Miguel) will finally fix this.

**Comment by p-a-s-c-a-l** [comment]
Closing in favour of https://github.com/clarity-h2020/csis/issues/104
