### ISSUE TITLE
Adaptation options in screening (round 3)

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/csis#131]
related to: https://github.com/clarity-h2020/csis/issues/100

Following the discussion in Naples, this is a recommendation concerning the adaptation options calculations:

- [ ] Implement a mechanism that will tell the EMIKAT which adaptation options to implement, to which cells, to which land use and to which percentage of this land use. Basically, this is a table with a whole lot of entries looking more or less like this:

- Option, 1..* land use category, 1..* cells, percentage

@patrickkaleta: I'll think about a simple way to implement such a list, let us talk next week. 

- [ ] Emikat needs to be notified when the list is ready and a calculation should be done somehow.

The triggering mechanism must be implemented by @patrickkaleta. I supposed this is similar to what is already done to trigger the initial calculation

- [ ] On emikat side, a mechanism to understand the trigger and the parameters table, "apply" the adaptation, re-calculate the local effect and make the new data available must be implemented

@humerh : please check what this means, how much work this would be...
@all: should we allow only one adaptation scenario or more than one? If more than one, how could this be implemented on CSIS and on EMIKAT side?

- [ ] On the CSIS side, we will also need a way to show the results. 

_I believe that adding one more resource and enabling the already existing table & map views from the impact step on adaptation option step would do the trick. More work would be required If we need to support more than one adaptation scenario._

- [ ] On CSIS side, the data model for the adaptation options should be changed and a GUI implemented in the study to alllow the users to choose:

1. Which land use category to apply the adaptation option to? 

_Currently the land use category is indicated in the adaptation option, if/when this is implemented it will be effectively possible to change the land use category by applying an adaptation option to a "wrong" land use category._

2. Which percentage of this land use category to apply the adaptation option to, in the relevant cell(s)? 

_Currently, it is implicitly assumed that this is always 100%. That is, if there is 50% houses in a cell, and we apply "green roof" to the houses, then there will be 50% of houses with green roofs in the cell afterwards. If/when this is implemented, we could end up with 20% houses with green roof and 30% not updated ones in this cell._

3. Which cells to apply the adaptation option(s) to?

_Currently, the adaptation options are assumed to apply to the whole project area. To chose the relevant cells, we woudl probably need a map view where the cells can be somehow chosen that the adaptation options apply to or the adaptation options to be applied defined for each cell in a project individually.__

@p-a-s-c-a-l @therter : I or @patrickkaleta can probably find a way to implement 1 and 2, but implementing a map (3) where the users can choose area or click on a cell is definitely something for @therter . Please give this a thought and comment how much work would it be to implement something like this and if it's realistic to do it in the remaining project duration.

In my opinion, we should be already able to provide interesting information by applying the adaptation options to the whole area. If we build the "parameters table" with fixed parameters and give this data to EMIKAT now, then changing the GUI could be done later without the need to change anything on the EMIKAT side.

@mattia-leone , @claudiahahn , @all: please read this carefully and comment if the above specifications are defined corectly and complete of if something is wrong/missing.

**Comment by DenoBeno** [comment]
One important question comes to mind: How are we supposed to handle the multiple adaptation options being applied to the same land use category?

I can imagine several cases here:

- Two adaptation options can indeed be applied in paralell. E.g. a green roof + a green facade can be both applied to a house. 

In theory, this shouldn't be a problem, but in praxis all of our adaptation options are replacing some parameters (e.g. runoff, albedo) so the secons one will disable the first.

- Two adaptation options cen't be applied simultaneously.

Imagine a first adaptation option changing a house to a park and the second one adding green roofs. This is a nonsense.

One way of handling this issue is to allow only one adaptation option being applied to each of the land use clases. If we follow this path, then the GUI for applying the adaptation options would probably need to start with the land use class, and a configuration table would then look like this:

1. LAND USE CLASS ;  cell(s); percentage; adaptation option
2. LAND USE CLASS ;  cell(s); percentage; adaptation option
...

**Comment by p-a-s-c-a-l** [comment]
> Please give this a thought and comment how much work would it be to implement something like this and if it's realistic to do it in the remaining project duration.

This can only be estimated after the public system is working and delivers realistic results. I'll come back to this issue after we've reached this goal.

**Comment by p-a-s-c-a-l** [comment]
done
