### ISSUE TITLE
Revising available GL-Steps in Study type "Basic Screening: General"

### ISSUE THREAD

**Issue by patrickkaleta** [clarity-h2020/csis#132]
Based on the Study Type, external services (like Emikat) can either be triggered for further calculations or not (see [this](https://github.com/clarity-h2020/csis-helpers-module/issues/12#issuecomment-562505399)). 

Now, since for `Basic Screening: General` Emikat is not listed as the calculation method, Emikat is not triggered. Nonetheless the "Risk and Impact Assessment" step is available for this Study type and in the map the user can request the "heat mortality risk/impact screening" layer, but nothing is then shown, since nothing is available in Emikat (example: https://csis.myclimateservice.eu/study/19/step/1946/view/maps).

**Question now is**: Should Emikat also be triggered for this Study type or should we remove/replace the "Risk and Impact Assessment" step?

**Comment by p-a-s-c-a-l** [comment]
EMIKAT should not be triggered. This is a "show available EU-level data only" study type.

Whether we can remove the RA/IA step depends on whether there will be some EU-level RA/IA data available. ATM we even lack Exposure.

**Comment by DenoBeno** [comment]
I had some discussion about exposure last week and I'm convinced that we
should be able to use the "local model input data " for exposure.

If we could also visually superpose the hazard & exposure data on a map, we
would even have something for the risk section.

Pascal Dihé <notifications@github.com> schrieb am Fr., 17. Jan. 2020, 15:08:

**Comment by p-a-s-c-a-l** [comment]
> in the map the user can request the "heat mortality risk/impact screening" layer

This is the expected behaviour. 😀 

The reason for this is that for this **Basic** Screening Study, the [European Wide Data Package for Automated Screening Studies](https://github.com/clarity-h2020/data-package/milestone/1) is used instead of a [Basic European Wide Data Package for Basic Screening Studies](https://github.com/clarity-h2020/data-package/issues/65).
