### ISSUE TITLE
"Cannot load a NULL ID" warning

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/csis#136]
I added a couple of presets to https://csis.myclimateservice.eu/study/18. On a save, the following warning was shown:

```
Warning: assert(): Cannot load a NULL ID. failed in Drupal\Core\Entity\EntityStorageBase->load() (line 249 of core/lib/Drupal/Core/Entity/EntityStorageBase.php).
Warning: array_flip(): Can only flip STRING and INTEGER values! in Drupal\Core\Entity\EntityStorageBase->loadMultiple() (line 266 of core/lib/Drupal/Core/Entity/EntityStorageBase.php).
```

I got this once for each new preset. Presets were saved OK, not sure if this caused any other problems. This is what I get in the logs:

`Warning: assert(): Cannot load a NULL ID. failed in Drupal\Core\Entity\EntityStorageBase->load() (line 249 of /app/web/core/lib/Drupal/Core/Entity/EntityStorageBase.php) #0 /app/web/core/includes/bootstrap.inc(587): _drupal_error_handler_real(2, 'assert(): Canno...', '/app/web/core/l...', 249, Array) #1 [internal function]: _drupal_error_handler(2, 'assert(): Canno...', '/app/web/core/l...', 249, Array) #2 /app/web/core/lib/Drupal/Core/Entity/EntityStorageBase.php(249): assert(false, 'Cannot load a N...') #3 /app/web/core/lib/Drupal/Core/Entity/EntityBase.php(531): Drupal\Core\Entity\EntityStorageBase->load(NULL) #4 /app/web/modules/custom/csis-helpers-module/csis_helpers.module(394): Drupal\Core\Entity\EntityBase::load(NULL) #5 /app/web/core/modules/options/options.module(89): csis_helpers_allowed_values_function(Object(Drupal\field\Entity\FieldStorageConfig), Object(Drupal\group\Entity\Group), true) #6 /app/web/modules/contrib/select_or_other/src/Plugin/Validation/AllowedValuesConstraintValidator.php(91): options_allowed_values(Object(Drupal\field\Entity\FieldStorageConfig), Object(Drupal\group\Entity\Group)) #7 /app/web/modules/contrib/select_or_other/src/Plugin/Validation/AllowedValuesConstraintValidator.php(60): Drupal\select_or_other\Plugin\Validation\AllowedValuesConstraintValidator->getValidChoices(Object(Drupal\options\Plugin\Field\FieldType\ListStringItem)) #8 /app/web/core/lib/Drupal/Core/TypedData/Validation/RecursiveContextualValidator.php(196): Drupal\select_or_other\Plugin\Validation\AllowedValuesConstraintValidator->validate(Object(Drupal\options\Plugin\Field\FieldType\ListStringItem), Object(Drupal\select_or_other\Plugin\Validation\AllowedValuesConstraint)) #9 /app/web/core/lib/Drupal/Core/TypedData/Validation/RecursiveContextualValidator.php(148): Drupal\Core\TypedData\Validation\RecursiveContextualValidator->validateConstraints(Object(Drupal\options\Plugin\Field\FieldType\ListStringItem), '000000007829add...', Array) #10 /app/web/core/lib/Drupal/Core/TypedData/Validation/RecursiveContextualValidator.php(158): Drupal\Core\TypedData\Validation\RecursiveContextualValidator->validateNode(Object(Drupal\options\Plugin\Field\FieldType\ListStringItem)) #11 /app/web/core/lib/Drupal/Core/TypedData/Validation/RecursiveContextualValidator.php(158): Drupal\Core\TypedData\Validation\RecursiveContextualValidator->validateNode(Object(Drupal\Core\Field\FieldItemList)) #12 /app/web/core/lib/Drupal/Core/TypedData/Validation/RecursiveContextualValidator.php(100): Drupal\Core\TypedData\Validation\RecursiveContextualValidator->validateNode(Object(Drupal\Core\Entity\Plugin\DataType\EntityAdapter), Array, true) #13 /app/web/core/lib/Drupal/Core/TypedData/Validation/RecursiveValidator.php(90): Drupal\Core\TypedData\Validation\RecursiveContextualValidator->validate(Object(Drupal\Core\Entity\Plugin\DataType\EntityAdapter), NULL, NULL) #14 /app/web/core/lib/Drupal/Core/TypedData/TypedData.php(131): Drupal\Core\TypedData\Validation\RecursiveValidator->validate(Object(Drupal\Core\Entity\Plugin\DataType\EntityAdapter)) #15 /app/web/core/lib/Drupal/Core/Entity/ContentEntityBase.php(489): Drupal\Core\TypedData\TypedData->validate() #16 /app/web/core/lib/Drupal/Core/Entity/ContentEntityForm.php(192): Drupal\Core\Entity\ContentEntityBase->validate() #17 [internal function]: Drupal\Core\Entity\ContentEntityForm->validateForm(Array, Object(Drupal\Core\Form\FormState)) #18 /app/web/core/lib/Drupal/Core/Form/FormValidator.php(82): call_user_func_array(Array, Array) #19 /app/web/core/lib/Drupal/Core/Form/FormValidator.php(275): Drupal\Core\Form\FormValidator->executeValidateHandlers(Array, Object(Drupal\Core\Form\FormState)) #20 /app/web/core/lib/Drupal/Core/Form/FormValidator.php(118): Drupal\Core\Form\FormValidator->doValidateForm(Array, Object(Drupal\Core\Form\FormState), 'group_study_con...') #21 /app/web/core/lib/Drupal/Core/Form/FormBuilder.php(576): Drupal\Core\Form\FormValidator->validateForm('group_study_con...', Array, Object(Drupal\Core\Form\FormState)) #22 /app/web/core/lib/Drupal/Core/Form/FormBuilder.php(319): Drupal\Core\Form\FormBuilder->processForm('group_study_con...', Array, Object(Drupal\Core\Form\FormState)) #23 /app/web/modules/contrib/form_mode_manager/src/Controller/EntityFormModeBase.php(278): Drupal\Core\Form\FormBuilder->buildForm(Object(Drupal\group\Entity\Form\GroupForm), Object(Drupal\Core\Form\FormState)) #24 /app/web/modules/contrib/form_mode_manager/src/Controller/EntityFormModeBase.php(238): Drupal\form_mode_manager\Controller\EntityFormModeBase->getForm(Object(Drupal\group\Entity\Group), 'edit_context') #25 [internal function]: Drupal\form_mode_manager\Controller\EntityFormModeBase->entityEdit(Object(Drupal\Core\Routing\RouteMatch)) #26 /app/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array(Array, Array) #27 /app/web/core/lib/Drupal/Core/Render/Renderer.php(582): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() #28 /app/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure)) #29 /app/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) #30 /app/vendor/symfony/http-kernel/HttpKernel.php(151): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() #31 /app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #32 /app/web/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #33 /app/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #34 /app/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(106): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #35 /app/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(85): Drupal\page_cache\StackMiddleware\PageCache->pass(Object(Symfony\Component\HttpFoundation\Request), 1, true) #36 /app/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #37 /app/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #38 /app/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #39 /app/web/core/lib/Drupal/Core/DrupalKernel.php(693): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #40 /app/web/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #41 {main}.`

and 

`Warning: array_flip(): Can only flip STRING and INTEGER values! in Drupal\Core\Entity\EntityStorageBase->loadMultiple() (line 266 of /app/web/core/lib/Drupal/Core/Entity/EntityStorageBase.php) #0 /app/web/core/includes/bootstrap.inc(587): _drupal_error_handler_real(2, 'array_flip(): C...', '/app/web/core/l...', 266, Array) #1 [internal function]: _drupal_error_handler(2, 'array_flip(): C...', '/app/web/core/l...', 266, Array) #2 /app/web/core/lib/Drupal/Core/Entity/EntityStorageBase.php(266): array_flip(Array) #3 /app/web/core/lib/Drupal/Core/Entity/EntityStorageBase.php(250): Drupal\Core\Entity\EntityStorageBase->loadMultiple(Array) #4 /app/web/core/lib/Drupal/Core/Entity/EntityBase.php(531): Drupal\Core\Entity\EntityStorageBase->load(NULL) #5 /app/web/modules/custom/csis-helpers-module/csis_helpers.module(394): Drupal\Core\Entity\EntityBase::load(NULL) #6 /app/web/core/modules/options/options.module(89): csis_helpers_allowed_values_function(Object(Drupal\field\Entity\FieldStorageConfig), Object(Drupal\group\Entity\Group), true) #7 /app/web/modules/contrib/select_or_other/src/Plugin/Validation/AllowedValuesConstraintValidator.php(91): options_allowed_values(Object(Drupal\field\Entity\FieldStorageConfig), Object(Drupal\group\Entity\Group)) #8 /app/web/modules/contrib/select_or_other/src/Plugin/Validation/AllowedValuesConstraintValidator.php(60): Drupal\select_or_other\Plugin\Validation\AllowedValuesConstraintValidator->getValidChoices(Object(Drupal\options\Plugin\Field\FieldType\ListStringItem)) #9 /app/web/core/lib/Drupal/Core/TypedData/Validation/RecursiveContextualValidator.php(196): Drupal\select_or_other\Plugin\Validation\AllowedValuesConstraintValidator->validate(Object(Drupal\options\Plugin\Field\FieldType\ListStringItem), Object(Drupal\select_or_other\Plugin\Validation\AllowedValuesConstraint)) #10 /app/web/core/lib/Drupal/Core/TypedData/Validation/RecursiveContextualValidator.php(148): Drupal\Core\TypedData\Validation\RecursiveContextualValidator->validateConstraints(Object(Drupal\options\Plugin\Field\FieldType\ListStringItem), '000000007829add...', Array) #11 /app/web/core/lib/Drupal/Core/TypedData/Validation/RecursiveContextualValidator.php(158): Drupal\Core\TypedData\Validation\RecursiveContextualValidator->validateNode(Object(Drupal\options\Plugin\Field\FieldType\ListStringItem)) #12 /app/web/core/lib/Drupal/Core/TypedData/Validation/RecursiveContextualValidator.php(158): Drupal\Core\TypedData\Validation\RecursiveContextualValidator->validateNode(Object(Drupal\Core\Field\FieldItemList)) #13 /app/web/core/lib/Drupal/Core/TypedData/Validation/RecursiveContextualValidator.php(100): Drupal\Core\TypedData\Validation\RecursiveContextualValidator->validateNode(Object(Drupal\Core\Entity\Plugin\DataType\EntityAdapter), Array, true) #14 /app/web/core/lib/Drupal/Core/TypedData/Validation/RecursiveValidator.php(90): Drupal\Core\TypedData\Validation\RecursiveContextualValidator->validate(Object(Drupal\Core\Entity\Plugin\DataType\EntityAdapter), NULL, NULL) #15 /app/web/core/lib/Drupal/Core/TypedData/TypedData.php(131): Drupal\Core\TypedData\Validation\RecursiveValidator->validate(Object(Drupal\Core\Entity\Plugin\DataType\EntityAdapter)) #16 /app/web/core/lib/Drupal/Core/Entity/ContentEntityBase.php(489): Drupal\Core\TypedData\TypedData->validate() #17 /app/web/core/lib/Drupal/Core/Entity/ContentEntityForm.php(192): Drupal\Core\Entity\ContentEntityBase->validate() #18 [internal function]: Drupal\Core\Entity\ContentEntityForm->validateForm(Array, Object(Drupal\Core\Form\FormState)) #19 /app/web/core/lib/Drupal/Core/Form/FormValidator.php(82): call_user_func_array(Array, Array) #20 /app/web/core/lib/Drupal/Core/Form/FormValidator.php(275): Drupal\Core\Form\FormValidator->executeValidateHandlers(Array, Object(Drupal\Core\Form\FormState)) #21 /app/web/core/lib/Drupal/Core/Form/FormValidator.php(118): Drupal\Core\Form\FormValidator->doValidateForm(Array, Object(Drupal\Core\Form\FormState), 'group_study_con...') #22 /app/web/core/lib/Drupal/Core/Form/FormBuilder.php(576): Drupal\Core\Form\FormValidator->validateForm('group_study_con...', Array, Object(Drupal\Core\Form\FormState)) #23 /app/web/core/lib/Drupal/Core/Form/FormBuilder.php(319): Drupal\Core\Form\FormBuilder->processForm('group_study_con...', Array, Object(Drupal\Core\Form\FormState)) #24 /app/web/modules/contrib/form_mode_manager/src/Controller/EntityFormModeBase.php(278): Drupal\Core\Form\FormBuilder->buildForm(Object(Drupal\group\Entity\Form\GroupForm), Object(Drupal\Core\Form\FormState)) #25 /app/web/modules/contrib/form_mode_manager/src/Controller/EntityFormModeBase.php(238): Drupal\form_mode_manager\Controller\EntityFormModeBase->getForm(Object(Drupal\group\Entity\Group), 'edit_context') #26 [internal function]: Drupal\form_mode_manager\Controller\EntityFormModeBase->entityEdit(Object(Drupal\Core\Routing\RouteMatch)) #27 /app/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array(Array, Array) #28 /app/web/core/lib/Drupal/Core/Render/Renderer.php(582): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() #29 /app/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure)) #30 /app/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) #31 /app/vendor/symfony/http-kernel/HttpKernel.php(151): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() #32 /app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #33 /app/web/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #34 /app/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #35 /app/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(106): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #36 /app/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(85): Drupal\page_cache\StackMiddleware\PageCache->pass(Object(Symfony\Component\HttpFoundation\Request), 1, true) #37 /app/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #38 /app/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #39 /app/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #40 /app/web/core/lib/Drupal/Core/DrupalKernel.php(693): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #41 /app/web/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #42 {main}.`

**Comment by DenoBeno** [comment]
I just tried this with another study - no error. https://csis.myclimateservice.eu/study/29

**Comment by patrickkaleta** [comment]
I fixed it. Apparently, when adding paragraphs, first an empty paragraph is created and then shown in the UI form to be filled out. For this empty paragraph no references yet exist, which is why the csis-helpers module then triggers the warning message in the log files.
