### ISSUE TITLE
Future exposure

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/csis#137]
At the moment, we have no "future exposure" layers in the pan-european data package. However, we may get them in the swedish "expert" package. Two issues to think about:

1. If the data package does provide future exposure for any of the layers, will this be handled corectly with "ressources template"? (recommendation: we should test with swedish data package)

2. (How) could we allow users to define future exposure in their study? Some possibilities:
 - one factor that is applied to the whole study area (2* more population)
 - multiplicator or replacing the value cell by cell in the study area

I suppose we will not have time/ressources to address this issue, but we need to at least document how this could be handled if and when CSIS is developed further.

**Comment by DenoBeno** [comment]
Of course, we could just hide the "select scenario" in exposure step, but I don't think tha tthis is necessary. Maybe jus tmention it in the text somewhere?

**Comment by p-a-s-c-a-l** [comment]
> may get them in the swedish "expert" package.

Doesn't [seem so](https://github.com/clarity-h2020/data-package/issues/21#issuecomment-587473641). 
If the situation changes, we can reopen, but ATM there's no future exposure in sight.
