### ISSUE TITLE
Improving the text content within CSIS and the data-package resources

### ISSUE THREAD

**Issue by RobAndGo** [clarity-h2020/csis#140]
It seems there is a desire to improve the text within CSIS and the data-package resources, perhaps to make it more understandable to the user.

In order to make things clear to me as to what is expected, I will start with an example of the data-package resources within the European Wide Data Package. At the moment the indices are described in terms of their definitions. e.g. for Summer Days:

```
The average yearly number of summer days in Europe for the baseline 
period 1971-2000 (ensemble mean).
A summer day is a day where the maximum temperature is greater than 25.0C. 
```

I can imagine that some text needs to be added which tells the user what this index means for them. So I thought of adding the following:

`Background: This climate index is a measure of daytime heat, with high values 
corresponding to warm conditions. An increase of this index with time means that the 
chance of warmer conditions will increase.
`

**Is this what people had in mind when they said that "text needs to be changed within the resources"?** I would like to be sure before I go ahead and make the necessary the changes.

**Comment by p-a-s-c-a-l** [comment]
> **Is this what people had in mind when they said that "text needs to be changed within the resources"?**

At leat that's what I had in mind. :-)

**Comment by RobAndGo** [comment]
I could expand upon this a bit further, e.g. for Tropical nights:

```
Background: This climate index is a measure of nighttime heat, with high values 
corresponding to warm, uncomfortable conditions. An increase of this index with time means 
that the chance of warmer conditions will increase. 

Impacts
Health sector: Cooling down is important after a hot day. A tropical night, where the 
temperature stays above 20°C makes it more difficult for the human body to cool down, 
especially for elderly or sick people. Therefore, an increase of tropical nights can lead to 
a rise of mortality. 
Energy sector: Higher electricity demand due to the increased use of air conditioning.
```

Or would this be too much text?

**Comment by claudiahahn** [comment]
I like the additional information. 
Where would that text appear? Only when the user has a look at the metadata of the resource (under the data tab?)? Or will it be displayed somewhere else as well?

**Comment by RobAndGo** [comment]
Actually, I don't know where the text will appear. 

I decided perhaps it is more important to explain the concept of the ensemble mean/standard deviation in the description, so I have added the following:

```
This climate index is a mean value (ensmean) calculated from an ensemble of the following 
7 bias-corrected EURO-CORDEX climate models:
- CLMcom-CCLM4-8-17/ICHEC-EC-EARTH, CLMcom-CCLM4-8-17/MOHC-HadGEM2-ES
- DMI-HIRHAM5/ICHEC-EC-EARTH
- KNMI-RACMO22E/ICHEC-EC-EARTH, KNMI-RACMO22E/MOHC-HadGEM2-ES
- SMHI-RCA4/ICHEC-EC-EARTH, SMHI-RCA4/MOHC-HadGEM2-ES
The use of several climate models provides a range of possible climate states, and the 
standard deviation or spread in their values (ensstd) provides an estimate of how 
probable the results are (i.e. a small standard deviation would imply a more probable 
outcome).
```

This text is text that I have used in CKAN - I'm assuming CSIS does not automatically extract any text from CKAN.

**Comment by p-a-s-c-a-l** [comment]
> This text is text that I have used in CKAN - I'm assuming CSIS does not automatically extract any text from CKAN.

no way 😁 
sorry, you have to copy & paste

**Comment by p-a-s-c-a-l** [comment]
Who's going to take care about the descriptions of the resources related to the RA/IA and HC/LE EMIKAT generated datasets? @humerh or @RobAndGo 

E.g. see https://github.com/clarity-h2020/data-package/issues/16#issuecomment-572068578
> Description of the [Heat mortality risk/impact screening ](https://csis.myclimateservice.eu/node/1356) has to be updated. At the moment, it just contains _"This data is generated by EMIKAT **on the fly** and for the study area indicated by $emikat_id"_ which is not enough.

> **We have to clearly describe the underlying methodology / models that lead to those results (mortality rate), the datasets that were used as input how these datasets were produced, processed and derived (provenance) as well as any uncertainties and quality issues involved. This applies also to the respective Data Package Resources representing these input datasets which include population exposure managed in EMIKAT, HC-LE input layers, HC-LE output (TMRT), etc.**

**Comment by p-a-s-c-a-l** [comment]
Robert's reply:

> As I am not completely aware of what has been calculated in EMIKAT, I would need @humerh's help in adding descriptions for the data. You have sent the link for the data-set here:
> https://csis.myclimateservice.eu/node/1356/edit?destination=/node/1356
> It’s just a matter of filling out a description text.

**Comment by p-a-s-c-a-l** [comment]
What's the status here? Can we close this issue?

**Comment by RobAndGo** [comment]
I have already added a description of the data, and since no one seems to object to it, I think we can close this issue, The text update for other aspects of the CSIS is covered in another github issue started by @claudiahahn.

**Comment by p-a-s-c-a-l** [comment]
Thank you!
