### ISSUE TITLE
User access to external layers protected by user/passwd

### ISSUE THREAD

**Issue by ghilbrae** [clarity-h2020/csis#141]
We are working on the Resccue DP + Study and we've run into a bit of a problem or doubt regarding how private information is going to be handled by the CSIS.

So, we have a bunch of layers that are private, we can add them to CKAN as private data so no one can access them, the thing is that if we add them to some place that is protected by user/passwd will the CSIS be able to access them? I suppose the answer is no. So that has us scratching our heads trying to figure out how a user that wants to create a DP with information that is private will be able to visualize their data. Is this addressed in any way?

On an additional note, will the CKAN ID for the resources always be mandatory? Will the users always need to create a CKAN account somewhere to upload their information before adding that to the CSIS?

**Comment by p-a-s-c-a-l** [comment]
> Is this addressed in any way?

no :-)

> will the CKAN ID for the resources always be mandatory

no :-)

**Comment by ghilbrae** [comment]
Closing this issue, as it has already been addressed.
