### ISSUE TITLE
CSIS User permissions and access to tabs and creation links

### ISSUE THREAD

**Issue by ghilbrae** [clarity-h2020/csis#142]
I'm trying to write a short guide for some of our DC4 users and I'm rather confused about the access options and permissions of certain functionalities.

I've been using two users to compare edit/creation possibilities: angela and meteogrid. The confusion comes from this: 
![content1](https://user-images.githubusercontent.com/1615745/73938607-ebdd1000-48e7-11ea-82b9-28307eb5c3bd.png)

Here this user can access all the content they have created that is not a study. I understand that a user that has no permissions to create DP or Resources would not be able to see this tab to either create or access their content but the thing is that a user that does not have this tab available can still click on the links below:
![links](https://user-images.githubusercontent.com/1615745/73938805-4aa28980-48e8-11ea-877b-cc9f5b09cff2.png)

And create DPs or Resources, or at least to access the creation pages. Is this something that needs to be fixed?

**Comment by patrickkaleta** [comment]
> And create DPs or Resources, or at least to access the creation pages. Is this something that needs to be fixed?

You're right. This needed fixing. Logged in users without special roles (like Meteogrid user) cannot create DPs or Resources, but they were able to view the creation page for them. That was a mistake and I updated the respective permissions. Thanks for pointing that out.

About the "Important Links" at the bottom: I guess we need to revise them. They've been added a while back, so they might not be up-to-date anymore. Also, they are mainly for registered users with special roles (admins, editors, developers), so we might want to hide it (partly/completely) for anonymous users and registered users without special purpose.

**Comment by ghilbrae** [comment]
Great! Thanks for your response :)
