### ISSUE TITLE
Revising "Data" tab 

### ISSUE THREAD

**Issue by patrickkaleta** [clarity-h2020/csis#146]
Post from @DenoBeno back in October 2019:

> What I'm wondering is if we should allow people to choose some of the resources and include them to the report, like we do for the adaptation options now.
> 
> see e.g. https://csis.myclimateservice.eu/study/33/step/1515/view/table
> 
> This is my proposal on how the new "data" tab could look like. Just like for the twins, we will probably end up using different views for different steps, so I recommend to resolve what is shown where in the same way as it's done for the tables now.
> 
> ![image](https://user-images.githubusercontent.com/2961790/66108249-77553600-e5c2-11e9-99c3-3b078747552e.png)
> 
> The report should IMO contain details only for the chosen resources (in the section where they were chosen) and just a basic information for the all resources in the data package in a separate section (annex).
> 
> **Reminder:** we also need to include the "pseudo resources" in the data tabs and in the annex listing all resources. That's the adaptation options and the vulnerability functions. I believe that we can use the already existing views that are currently under "table" for this purpose (with minimal changes).

**Comment by patrickkaleta** [comment]
Resposible views for the current implementation:
- [Resource preview at the bottom of Data tab](https://csis.myclimateservice.eu/admin/structure/views/view/rest_node/edit/rest_export_3)
- [List of all resources in DP & step](/admin/structure/views/view/step_data_collection_2/edit/entity_view_3)

**Comment by p-a-s-c-a-l** [comment]
Is this still relevant?

**Comment by patrickkaleta** [comment]
I'm not aware of any progress here and I'm currently not able to contribute here. I'm not even sure if this include/remove resources in report would have any real benefit for users. **IMO this is no longer relevant** and we should focus on adaptation options and their impact/cost calculation.
