### ISSUE TITLE
CSIS demo for workshop in Linz

### ISSUE THREAD

**Issue by claudiahahn** [clarity-h2020/csis#147]
@humerh, what are the units for the mortality layer? 
![grafik](https://user-images.githubusercontent.com/45260352/75492021-29006380-59b7-11ea-8e5a-bb47bba6e948.png)

**Comment by p-a-s-c-a-l** [comment]
AFAIK damage quantity = number of dead.

**Comment by p-a-s-c-a-l** [comment]
done
