### ISSUE TITLE
The summary page of some studies loads very long

### ISSUE THREAD

**Issue by therter** [clarity-h2020/csis#152]
Every screenshot will be loaded in its original resolution, when the summary page is loaded. This can take very much time. For example for [this](https://csis.myclimateservice.eu/study/1/view/summary) page.

**Comment by p-a-s-c-a-l** [comment]
1st we should remove all report images from test study 1. I assume this is a manual process?
2nd we should change image format of screenshots from PNG to JPEG.

**Comment by therter** [comment]
> 1st we should remove all report images from test study 1. I assume this is a manual process?
> 2nd we should change image format of screenshots from PNG to JPEG.

I will do this

**Comment by therter** [comment]
> 1st we should remove all report images from test study 1. I assume this is a manual process?

All report images from study 1 are removed. But I haven't removed the unused image files from the csis directory, yet. 


> 2nd we should change image format of screenshots from PNG to JPEG.

JPEG images are now used

**Comment by therter** [comment]
Unused files will be deleted from the file system, if the status of the file is temporary (table file_managed, field status = 0) and the last change was 3 month ago (this can be changed [here](https://csis.myclimateservice.eu/admin/config/media/file-system)). 
But the current drupal version does not change the status of orphaned files to temporary. (See [here](https://www.drupal.org/node/2891902))

The status can be set manually via the database. For example with an update statement like this 

`
update file_managed set status = 0 where fid in
(
select m.fid from file_managed m left join file_usage u on (m.fid = u.fid) 
where coalesce(u.count, 0) = 0 
)
`

To delete the files now instead of after three months, the database fields "created" and "changed" should be changed.  

All files, which are temporary and the last change was 3 month ago, will be deleted during the  drupal cron job (The drupal cron job can be configured [here](https://csis.myclimateservice.eu/admin/config/system/cron)). Note: one run of the drupal cron job removes a maximum of 100 files.
