### ISSUE TITLE
Allow Emikat calculation tests to be run by the UI testing service

### ISSUE THREAD

**Issue by patrickkaleta** [clarity-h2020/csis#153]
Up until now the csis helpers module [Emikat testing mechanism](https://github.com/clarity-h2020/csis-helpers-module/blob/dev/src/Utils/TestingService.php) was executed as part of a cronjob. 

I've changed that, so that it can now be triggered by the UI testing service via visiting the following URLs (those URLs are only accessible if user is logged in as an administrator):
- to trigger the calculations in Emikat for the test Study: https://csis.myclimateservice.eu/maintenance/trigger-emikat-test
- to view the results of the batchjobs for the test Study:
https://csis.myclimateservice.eu/maintenance/check-emikat-results

![emikat-testing-batchjobs](https://user-images.githubusercontent.com/42167036/76766655-9d4d4c00-6798-11ea-983b-5f2a78496c1f.png)

The received batchjobs from Emikat are currently categorized into these 3 states:
1) `batchjob-ok` -> Emikat status == OK & results > 0
2) `batchjob-error` -> Emikat status == ERR
3) `batchjob-warning` -> for all other statuses returned by Emikat or if an "OK" batchjob has 0 results (which indicates possible errors in the calculation)

@p-a-s-c-a-l  please have a look at this and let me know if that's enough for now or if it should somehow be improved/changed. 

**Please also keep in mind** that ATM the calculation trigger is fired each time the URL is called, so we could potentially spam Emikat with test calculations. It would probably make sense to implement a check that would only allow to fire the trigger if the previous calculations have finished. I'll start working on that.

**Comment by p-a-s-c-a-l** [comment]
Thanks!

I'm going to test against problems > 0 == failed. ATM, running batch jobs that haven't returned any results **yet** (INI), not count as problem:

![grafik](https://user-images.githubusercontent.com/1788226/76840125-f10e7280-6836-11ea-8d3d-4b6ada3d6835.png)

That's not an issue as I'm planning to run tests every 2 hours and check the status page first and then, if all batch jobs are ok (problems == 0 , trigger a new test.

**Comment by patrickkaleta** [comment]
Triggering and viewing the results now possible for new User role "Testing". Also, there is now a button linking to the results of the Emikat test in the Maintenance overview.

@p-a-s-c-a-l : as wished, I added the "clarity-ci-csis" user to this new user role.

**Comment by p-a-s-c-a-l** [comment]
Our CI System is now periodically checking the [status page](https://csis.myclimateservice.eu/maintenance/check-emikat-results). If the problem count is 0, it will trigger an new calculation. If it is > 0, it will create a new bug report like [this one](https://github.com/clarity-h2020/csis-technical-validation/issues/21) in [csis-technical-validation](https://github.com/clarity-h2020/csis-technical-validation/issues).

@humerh Could you therefore please subscribe to the [csis-technical-validation](https://github.com/clarity-h2020/csis-technical-validation/) repository?

**Comment by p-a-s-c-a-l** [comment]
Currently, the status check fails with
> expected '<span.total-warning-count>' to have text '0', but the text was '1'

@patrickkaleta @humerh 

Is this a 'real problem' or can it be ignored:
> ID: 70515, Name: Rebuild Table CLY_FL_STRAEMS#2156, Status: OK, Message: **Result=0 **

Perhaps we have we to distinguish between `error-count` and `warning-count`.

**Comment by p-a-s-c-a-l** [comment]
If possible, the status page should also include the date and time when the last test study was triggered. 

Continuous Integration System triggers only when warning count is zero. However, current warning count checked by CI  [is 6](https://github.com/clarity-h2020/csis-technical-validation/issues/21#issuecomment-603710781) while  previous warning count [was 1](https://github.com/clarity-h2020/csis-technical-validation/issues/21#issuecomment-603207708). So  *probably* somebody manually triggered the test study.

**Comment by patrickkaleta** [comment]
> If possible, the status page should also include the date and time when the last test study was triggered.
> 

Emikat doesn't directly provide that information, but I've now added the date & time when the first batch job of the calculation was started ( which will roughly be the same time when the trigger was fired, **unless** there is currently another Study calculation running and this one has to be queued).

**Comment by humerh** [comment]
If you want I can also provide the information, when the batch job was queued.

**Comment by humerh** [comment]
If you want I can also provide the information, when the batch job was queued.

**Comment by patrickkaleta** [comment]
> Currently, the status check fails with
> 
> > expected '<span.total-warning-count>' to have text '0', but the text was '1'
> 
> @patrickkaleta @humerh
> 
> Is this a 'real problem' or can it be ignored:
> 
> > ID: 70515, Name: Rebuild Table CLY_FL_STRAEMS#2156, Status: OK, Message: **Result=0**
> 

Not sure if that's a problem or not, @humerh has to tell us whether this batch job should return some results or not.


> Perhaps we have we to distinguish between `error-count` and `warning-count`.

I could do that if needed. As **error** I could count just those batch jobs that have an `ERR` status and all other things like `Result=0` or a status of `INI` or `RUN` would count as a **warning**.

**Comment by patrickkaleta** [comment]
Thanks to @humerh I realized that for our test study we had selected a completely wrong city, for which we don't have the necessary data. That would explain why some batch jobs had 0 results. I changed the city and now selected Vienna, but still some batch jobs return 0 results.

According to [this commen](https://github.com/clarity-h2020/emikat/issues/33#issuecomment-603172199)t from @negroscuro height information is not available for Vienna. @humerh could that maybe be the reason why some batch jobs still return 0 results?

**Comment by patrickkaleta** [comment]
> If you want I can also provide the information, when the batch job was queued.

@humerh If it's not too much work for you, you could add this information at some point (I'm sure it would also be nice to have thisinformation from inside the Emikat client's batch-job list). But for the CI testing system it's ATM probably enough to just know when the batch job was started.

**Comment by p-a-s-c-a-l** [comment]
Currently, I've disabled the UI tests. ATM there are have been [6 problem(s) in a total of 13 batchjobs](https://csis.myclimateservice.eu/maintenance/check-emikat-results). I'm going to enable the tests again when we can make sure that at least the test study works.

**Comment by p-a-s-c-a-l** [comment]
Tests enabled again.
