### ISSUE TITLE
Create or clone datapackage?

### ISSUE THREAD

**Issue by LenaStr** [clarity-h2020/csis#156]
I want ro create a new datapackage, or clone the European wide package to have something to start from but can not figure out how to do this. Same problem seems to be there for resources.

Am I missing something or is it a question of rights again?

/Lena

**Comment by p-a-s-c-a-l** [comment]
Cloning of  data packages is supported by a specific module. See [this discussion](https://github.com/clarity-h2020/data-package/issues/65#issuecomment-596488373) for more details.  AFAIK it is not enable for all users. @DanielRodera has used it to clone the European Data Package, I think he can assist you.

Please be aware that only the data package is cloned by value. All sub entities (including resources) are cloned by reference. E.g. if you clone the data package, changes made to resources in the cloned data package are reflected in all other data package that use the same resources! 

To actually change an existing resource, you would have to clone the resource separately and add it to the data package. IMHO this particular use case is supported out of the box without using the special module. I Think @RobAndGo can tall you how to clone resources. However, if you [clone a resource](https://github.com/clarity-h2020/data-package/issues/41#issuecomment-521118673) you have to be aware that `dp_references` contained therein are also cloned *by reference* so editing them directly will also change affect the original resource. 

**All in all cloning should be used with great care as it can have unwanted side effects.**

**Comment by LenaStr** [comment]
OK! 

What I need to do is to create a data package containing a subset of the resources from the European data package and then complement it with resources from our expert studies.
(What you say about valueas and references seems what I expect.)

It might be as easy to create a new datapackage and then import the resources I want.
Hoowever, I can not figure out how to create a new datapackage or resource. Where can I do this?

**Comment by patrickkaleta** [comment]
> It might be as easy to create a new datapackage and then import the resources I want.
> Hoowever, I can not figure out how to create a new datapackage or resource. Where can I do this?

Hi Lena,

the links for creating data packages and resources should be available in your account pages (https://csis.myclimateservice.eu/user/41/content). There you should see on top two buttons ("create data package" and "create resource")

**Comment by patrickkaleta** [comment]
> I want ro create a new datapackage, or clone the European wide package to have something to start from but can not figure out how to do this. Same problem seems to be there for resources.

Regarding cloning, as Pascal mentioned it's ATM only possible for administrators to do that. Reason is, that it could potentially change/destroy the original data package if not used carefully.

If you think that it would be much easier to work with a clone of the European DP, than please talk to @DanielRodera. He has the most experience with this cloning feature and he could clone the data package for you and give you the ownership of the new, cloned data package.

**Comment by DanielRodera** [comment]
@LenaStr, I have created a cone of the European DP. I named it _Clone of European Wide Data Package_, you can use it.

Let me know if you have any problem or you need to clone another one.
