### ISSUE TITLE
CSIS - Text for each step

### ISSUE THREAD

**Issue by claudiahahn** [clarity-h2020/csis#159]

**Comment by RobAndGo** [comment]
While modifying the text, I noticed that we tend to (not always) use the American English version of "characterization", as in "Hazard Characterization". I think we should use "Characterisation", as this is how it it written in the original EU-GL document. And using one version instead of switching between the two would make it appear more consistent throughout.

Now, I am hoping that this change would be an "easy" search and replace job through all files. Can this change be done?

**Comment by p-a-s-c-a-l** [comment]
Which files?

**Comment by DenoBeno** [comment]
It can be done somehow... If nothing else, we can always do a database dump, replace all occurrences and then load the DB in again. This isn't so difficult to do, but I'll let @patrickkaleta do it because I'm normally not touching the database in this product...

Patrick, here is how it can be done:

1) dump the whole DB, either using drush, directly from mysql or or using the "backup migrate" module that currently isn't installed on csis https://www.drupal.org/project/backup_migrate (That's strange. How are we making backups on that site?)
2) unzip the file (if produced by backup migrate module). The result will be an SQL file with plenty of drop/create table and a whole lot of "INSERT" lines. 
3) Replace the text in the whole file and then load it back to the server.

Unless you have a better idea?

Of course, we can give this a try too: https://www.drupal.org/project/scanner. Sounds quite cool, actually...

Note: 
- Beware of the capitalisation. I suppose you will have to replace the capitalised and not capitalised version separately. 
- You don't need to worry about Drupal variable naming/database schema. Even if we have called some variable "characterization" and this changes to "characterisation", it will not break anything since the change will be done everywhere. As long as we do this on all servers, obviously...

**Comment by p-a-s-c-a-l** [comment]
>     3\. Replace the text in the whole file and then load it back to the server.

what could possible go wrong? :-)

Seriously, **never change a running system**. If you really dare to mess with the database dump and load it again, it will break so many thing you can't even imagine now. E.g. if you replace characterisation by characterisation, this will also rename our taxonomy URIs like https://csis.myclimateservice.eu/taxonomy/eu-gl/hazard-characterization and ids like `eu-gl:hazard-characterization`.

I cannot foresee all consequences of these **breaking** changes. At at least it will break map and table component as they rely on these taxonomy ids .

So please, don't touch the database. We are nearly ready to make a first release.

**Comment by RobAndGo** [comment]
OK, fair enough. In that case, it is not important. So, for the text description we will use "characterization" for consistency.

**Comment by claudiahahn** [comment]
based on recent publications, it would be better to call the RCP8.5 scenario "worst case scenario" instead of "business as usual". 
I hope it is not too much of an effort to change that?

**Comment by claudiahahn** [comment]
I have uploaded a word document with text for some of the CSIS steps: 
https://newrepository.atosresearch.eu/remote.php/webdav/CLARITY/WP1%20CO-Creation/T1.3%20Climate%20Services%20Co-Creation/CSIS-text/Text_for_CSIS_v1.docx

So far I have not changed the text in the Vienna study (no: 25), but I have seen that I am not able anyway to change the text for the introduction (https://csis.myclimateservice.eu/study/25/view/intro). 

Questions regarding the text: 
@humerh, is it correct to write "EMIKAT, a software tool from the Austrian Institute of Technology (AIT), is used to perform the following calculations on the fly:", or should it be emikat?

Is there already an official website for the marketplace? I probably need to ask Andrea.

**Comment by DenoBeno** [comment]
> based on recent publications, it would be better to call the RCP8.5 scenario "worst case scenario" instead of "business as usual".
> I hope it is not too much of an effort to change that?

Honestly, I don't know. 

I have changed the label of https://csis.myclimateservice.eu/taxonomy/term/2262 now 

That was easy and shouldn't cause any problems since labels aren't used by underlying software for anything ("meaning ID" field didn't change). But where else does it need to be changed?

**Comment by DenoBeno** [comment]
By the way, are we using mysql or posgresql DB backend? If mysql, we could really try out https://www.drupal.org/project/scanner

**Comment by p-a-s-c-a-l** [comment]
> is this name used as part of the program logic anywhere?

`field_id` and `field_rcp` are used at least in map and table component and shouldn't be changed.

> we could really try out https://www.drupal.org/project/scanner
We are using PostgreSQL.

**Comment by DenoBeno** [comment]
> I have uploaded a word document with text for some of the CSIS steps:
> https://newrepository.atosresearch.eu/remote.php/webdav/CLARITY/WP1%20CO-Creation/T1.3%20Climate%20Services%20Co-Creation/CSIS-text/Text_for_CSIS_v1.docx
> 
> So far I have not changed the text in the Vienna study (no: 25), but I have seen that I am not able anyway to change the text for the introduction (https://csis.myclimateservice.eu/study/25/view/intro).
> 
> Questions regarding the text:
> @humerh, is it correct to write "EMIKAT, a software tool from the Austrian Institute of Technology (AIT), is used to perform the following calculations on the fly:", or should it be emikat?
> 
> Is there already an official website for the marketplace? I probably need to ask Andrea.

- Marketplace is at https://myclimateservice.eu/
- I usually write EMIKAT, but http://www.emikat.at/?lang=en says "emikat". hm.
- intro text is indeed hard coded at the moment. Sh*.. Let me take a look at that.

**Comment by DenoBeno** [comment]
**@intro text.** 

The way this is implemented now, the intro text is taken from taxonomy term and the same for all studies. It's not even study type specific, which is not good IMO.

Now, the problem is that the intro text is part of the group and not part of the group nodes... That is, we aren't producing it on the fly from templates but are instead just adding a new group with some fields set to default...

I have added a new text field and a button to edit this text, please try it out. Should also print properly.... 

The methodology text can't be changed, but user can disable it or replace it with another term description now. 

**For discussion:**

1) We could add a few more generic methodology texts that the user can choose from. Default text would be a very very generic one and  then there could be a few more texts that are more appropriate for certain study types. This could be in a separate taxonomy to avoid clutter.
2) We could completely remove link to methodology and add default text to this new text field.

There are more fancy solutions too, but it's IMO overkill.

**Comment by DenoBeno** [comment]
> > is this name used as part of the program logic anywhere?
> 
> `field_id` and `field_rcp` are used at least in map and table component and shouldn't be changed.
> 
> > we could really try out https://www.drupal.org/project/scanner
> > We are using PostgreSQL.

That's clear. I'm specifically interested in that strangely looking title field. Title  *should* not be used for anything except displaying things, but I want to be sure here...

**Comment by DenoBeno** [comment]
I have noticed that the images upload path is a public one. 

https://csis.myclimateservice.eu/admin/config/content/formats/manage/basic_html?destination=/admin/config/content/formats

Should this be changed to private images?

**Comment by DenoBeno** [comment]
@claudiahahn : I have updated the texts that you provided, but that's just for the first step. You can see the new texts here:

https://csis.myclimateservice.eu/taxonomy/study-type/screening-urban

**Comment by patrickkaleta** [comment]
> > > is this name used as part of the program logic anywhere?
> > 
> > 
> > `field_id` and `field_rcp` are used at least in map and table component and shouldn't be changed.
> > > we could really try out https://www.drupal.org/project/scanner
> > > We are using PostgreSQL.
> 
> That's clear. I'm specifically interested in that strangely looking title field. Title _should_ not be used for anything except displaying things, but I want to be sure here...

The csis helpers module does not use any of the fields nor the whole [EmissionScenarios](https://csis.myclimateservice.eu/admin/structure/taxonomy/manage/emissions/overview) taxonomy at all, so changing the titles of these taxonomy terms won't affect the csis helpers module.

By the looks of the whole taxonomy, I'm guessing that @DanielRodera created it way back (when we thought about an automated content import from xml files or whatever, where machine-readable names had a much higher importance than now) in a rather generic way, so I don't believe the machine-readable-like titles serve any purpose.

**Comment by claudiahahn** [comment]
I have updated the text for the CSIS steps: (https://newrepository.atosresearch.eu/index.php/apps/files/?dir=/CLARITY/WP1%20CO-Creation/T1.3%20Climate%20Services%20Co-Creation/CSIS-text&fileid=417380/Text_for_CSIS_v2.docx)

-	Advanced screening – urban infrastructure: I changed the following, also in the template (https://csis.myclimateservice.eu/taxonomy/study-type/screening-urban):
o	Streams come from HydroSHEDS, basins from Copernicus (that was previously mixed up, sorry!)
o	Inserted links to Copernicus, Eurostat and hydroSHEDS
o	Note: the basins data from Copernicus is not available anymore. Instead a new data set is provided (I guess Mario has already completed the layer generation or is it still possible to use the new data and maybe also the streams data from Copernicus?)

-	Study / Intro: the first sentence was updated (also in the template)
-	Hazard - Local effect description included

I have entered the new text for the first steps in the following study: (except for the pluvial flood local effect part):  https://csis.myclimateservice.eu/study/25/view/intro

When choosing the intro text: the text that is displayed now should be labelled: EU-GL (or EU-GL, 2 if you want to keep the other EU-GL text as well). As of now, I had to choose “Advanced screening methodology”, which should have a different content (see word doc or https://csis.myclimateservice.eu/taxonomy/term/1159).

Maybe it would be good to enable a selection of two texts – the EU-GL methodology and below the one for the study type?

**Comment by claudiahahn** [comment]
I have updated the text for the exposure step: (https://newrepository.atosresearch.eu/index.php/apps/files/?dir=/CLARITY/WP1%20CO-Creation/T1.3%20Climate%20Services%20Co-Creation/CSIS-text&fileid=417380/Text_for_CSIS_v3.docx)

The new text is also available in the study 25: https://csis.myclimateservice.eu/study/25/step/3683/view/introduction

I have not yet updated the templates (https://csis.myclimateservice.eu/taxonomy/term/1159). 
Can I do that, or shall I wait?

**Comment by p-a-s-c-a-l** [comment]
> Can I do that, or shall I wait?

Please wait. Now that we are making the system public for everyone we've moved it to a new server. That means all changes have to be made in https://csis-dev.myclimateservice.eu and we synchronise them to https://csis.myclimateservice.eu. So please don't make any direct changes in csis.myclimateservice.eu.

**Comment by p-a-s-c-a-l** [comment]
> * I have changed the label of **https://csis.myclimateservice.eu/taxonomy/term/2262** now
> 
> * **https://csis.myclimateservice.eu/taxonomy/term/2251** gets a title automatically assigned to it, so I have just saved it again without changing it.

![grafik](https://user-images.githubusercontent.com/1788226/83871566-92b7a880-a730-11ea-87c9-d89c5f04681b.png)

To restore consistency in naming conventions, I've renamed it to **Emissions Scenario: RCP 8.5 (worst case)** in DEV instance. Now we have to sync it to PROD.

**Comment by p-a-s-c-a-l** [comment]
> I have not yet updated the templates (https://csis.myclimateservice.eu/taxonomy/term/1159).
> Can I do that, or shall I wait?

@claudiahahn 

You can now make these changes on https://csis-dev.myclimateservice.eu

**Comment by claudiahahn** [comment]
@p-a-s-c-a-l , Thanks!
I hope to do that soon, but probably won't manage today. I will write, when I have done it. 

Short note: in the screenshot you have send, it says "worst case scenario", but it should be "RCP 8.5 (worst case scenario)"

**Comment by claudiahahn** [comment]
@p-a-s-c-a-l with the login data I have, I cannot login to the CLARITY CSIS - DEVELOPMENT INSTANCE. I just wanted to update the text for the templates (https://csis-dev.myclimateservice.eu/taxonomy/term/1159)

**Comment by p-a-s-c-a-l** [comment]
> with the login data I have, I cannot login to the CLARITY CSIS - DEVELOPMENT INSTANCE.

@fgeyer16 How can we resolve this issue of allowing CLARITY partners to use their CAS login for the dev instance of CSIS?

**Comment by patrickkaleta** [comment]
> > with the login data I have, I cannot login to the CLARITY CSIS - DEVELOPMENT INSTANCE.
> 
> @fgeyer16 How can we resolve this issue of allowing CLARITY partners to use their CAS login for the dev instance of CSIS?

I believe I was able to fix this by changing the settings in the CAS module on the DEV instance. Admins and accounts which were created "outside" of the CAS system were working fine, but others (like Claudia) couldn't log in until now.

@claudiahahn please try to access the CSIS DEV instance again.

**Comment by claudiahahn** [comment]
@patrickkaleta I tried to login, but It still does not work for the DEV instance. My login name is claudiahahn

**Comment by patrickkaleta** [comment]
> @patrickkaleta I tried to login, but It still does not work for the DEV instance. My login name is claudiahahn

Sorry, to hear that. I think it will be necessary to remove the CAS module completely from the DEV instance. But then users will need to use the "forgot password" link when trying to login for the first time on DEV. @fgeyer16 do you see any other possibility that would allow users to login on DEV without giving them any troubles?

@claudiahahn in the meantime, could you send me your updated text and tell me where you wanted to apply those changes? I'll take care of it until @fgeyer16 and me come up with a solution to the login troubles.

**Comment by fgeyer16** [comment]
>  @fgeyer16 do you see any other possibility that would allow users to login on DEV without giving them any troubles?

If we do not want/need CAS/SSO on the dev instance I would remove it completely. A mixed login will always cause troubles if only because of the existence of two login possibilities. Users seem to tend always to use the wrong one ;-).

**Comment by claudiahahn** [comment]
@patrickkaleta I wanted to update the descriptions of the first few study steps (General introduction, hazard characterization, local effect, exposure, description for advanced screening). The text is available on owncloud: https://newrepository.atosresearch.eu/index.php/apps/files/?dir=/CLARITY/WP1%20CO-Creation/T1.3%20Climate%20Services%20Co-Creation/CSIS-text&fileid=417380/Text_for_CSIS_v4.docx

I wanted to update the templates, such that the text appears for every new study. I am not exactly sure where to do that. Denis once sent me this link: https://csis.myclimateservice.eu/taxonomy/term/1159

Since changes should now be done in the development instance, it is probably https://csis-dev.myclimateservice.eu/taxonomy/term/1159.

**Comment by patrickkaleta** [comment]
@claudiahahn ok I will take care of updating the texts. In the meantime I've reset your password for the DEV instance. I will send you a mail with the password. Once you logged in, you can change the password back to your original one [here](https://csis-dev.myclimateservice.eu/user/127/edit). This only affects the CSIS DEV instance, you don't have to change the password anywhere else.

**Comment by claudiahahn** [comment]
@patrickkaleta Thank you!

**Comment by patrickkaleta** [comment]
@claudiahahn I've updated the texts. I've made some comments, which are in the [document](https://newrepository.atosresearch.eu/remote.php/webdav/CLARITY/WP1%20CO-Creation/T1.3%20Climate%20Services%20Co-Creation/CSIS-text/Text_for_CSIS_v4.docx) on owncloud.

FYI: Currently, for the **Study Introduction** texts (so the texts shown at .../study/XX/view/intro) have to be chosen by the Study members (by clicking on "Change description" and then either writing a custom text or selecting one of the predefined onces), since by default only the general EU-GL description is displayed. For the [Study 37](https://csis-dev.myclimateservice.eu/study/37/view/intro) this was already done (I think by Denis?), so it already shows the updated text from your word document.

**Comment by patrickkaleta** [comment]
Do we need any additional changes to some of the Study/GL-step texts or can this issue be closed now?

**Comment by claudiahahn** [comment]
There will be a few more things that need to be updated, so I would leave it open.

**Comment by claudiahahn** [comment]
``FYI: Currently, for the Study Introduction texts (so the texts shown at .../study/XX/view/intro) have to be chosen by the Study members (by clicking on "Change description" and then either writing a custom text or selecting one of the predefined onces), since by default only the general EU-GL description is displayed. For the Study 37 this was already done (I think by Denis?), so it already shows the updated text from your word document.

to show the updated text, I had to select "Advanced Screening Methodology", which is not the right decsription. It would be good to display this text as default or list it under EU-GL (or EU-GL2 if both versions should be available). Under "Advanced Screening" there should be another description

**Comment by claudiahahn** [comment]
I have noticed a small mistake and wanted to correct it, but I don't know where to do it. 
The templates here: https://github.com/clarity-h2020/csis/issues/159 
still have old text in it. So the change probably needs to be done somewhere else.

The following should be changed: under the "hazard characterization" tab: historical period (1971-2000)
as of now it says 1979-2000, which is wrong.

**Comment by claudiahahn** [comment]
sorry, here is the correct link:
https://csis-dev.myclimateservice.eu/maintenance/gl-templates

**Comment by patrickkaleta** [comment]
> I have noticed a small mistake and wanted to correct it, but I don't know where to do it.
> The templates here: #159
> still have old text in it. So the change probably needs to be done somewhere else.
> 
> The following should be changed: under the "hazard characterization" tab: historical period (1971-2000)
> as of now it says 1979-2000, which is wrong.

Thanks! It was [this template](https://csis-dev.myclimateservice.eu/node/934) and I've now changed the year to 1971.

**Comment by claudiahahn** [comment]
Thank you!

However, the text displayed under these templates are slightly different to what one can see on the csis-dev website (https://csis-dev.myclimateservice.eu/study/113/step/3630/view/introduction), which is why I wondering if the text can be changed somewhere else too. 

looking at the EU_GL templates listed here: https://csis-dev.myclimateservice.eu/maintenance/gl-templates, 
for example, the exposure evaluation text is still the old one (https://csis-dev.myclimateservice.eu/node/936) and not the one that was updated and is displayed on the website (https://csis-dev.myclimateservice.eu/study/113/step/3632/view/introduction)

I would like to know in case I need to make a few more changes.

**Comment by patrickkaleta** [comment]
> However, the text displayed under these templates are slightly different to what one can see on the csis-dev website (https://csis-dev.myclimateservice.eu/study/113/step/3630/view/introduction), which is why I wondering if the text can be changed somewhere else too.

Changing the GL-templates does not affect any of the already existing GL-steps in the Studies. Think of the individual GL-steps shown inside the Studies as snapshots, which show the status of the GL-template at the moment when the Study was created. After that point there is no more interaction between the existing GL-step and the template which was used to create it.

**In short:** Changing a template will only affect those GL-steps that are created afterwards. All already existing GL-steps will not be updated.


> I would like to know in case I need to make a few more changes.

If you want to update the texts of individual Study GL-steps, you need to edit these GL-steps directly. That has to be done for each Study individually. Should that be the case, I would suggest you open up a new issue on Github, where you post the Studies and the individual GL-steps that need to be updated + the texts that should be shown instead of the current ones.

**Comment by patrickkaleta** [comment]
> looking at the EU_GL templates listed here: https://csis-dev.myclimateservice.eu/maintenance/gl-templates,
> for example, the exposure evaluation text is still the old one (https://csis-dev.myclimateservice.eu/node/936) and not the one that was updated and is displayed on the website (https://csis-dev.myclimateservice.eu/study/113/step/3632/view/introduction)

Here we have a rather special case. What you see in Study 113 is the general description for "Exposure Evaluation" as defined for the EU-GL guideline (which is stored [here](https://csis-dev.myclimateservice.eu/taxonomy/term/4/edit?destination=/study/113/step/3632/view/introduction)). But depending on the used Study type, some people wanted to use slightly different texts in each GL-step, we added the possibility to write custom texts into the templates for each GL-step, **which are then Study type specific**.

What must've happend to Study 113 was that when it was created, it didn't have a custom description inside the template, so the GL-step therefore took the general EU-GL guideline description for the "Exposure Evaluation". Later, someone added the custom description (which you say is outdated) and all Studies of that Study type afterwards showed the custom (but outdated) text in the "Exposure Evaluation".

How to fix this:
Well, if the default EU-GL description for this step is good enough for the Study type, I would suggest to remove the custom text from the template, because then it will show only this default EL-GL description.
If the text has to include something specific to this Study type only, then the [template](https://csis-dev.myclimateservice.eu/node/936) must be updated accordingly.

**Comment by claudiahahn** [comment]
ok, thanks for explaining!
I will take care of this, and check the text in each template ... hopefully next week.

**Comment by patrickkaleta** [comment]
Maybe a question to you @claudiahahn:

I [recently noticed](https://github.com/clarity-h2020/csis/issues/184#issuecomment-669747889) that on DEV the [description](https://csis-dev.myclimateservice.eu/taxonomy/term/1159/edit) for the "Advanced Screening: Urban Infrastructure" Study type was changed. This is the original [description](https://csis.myclimateservice.eu/taxonomy/term/1159/edit) currently on PROD.

Which of these two is correct? (In the next synchronization run the description from DEV would replace the description in PROD)

**Comment by claudiahahn** [comment]
Thank you @patrickkaleta for pointing it out!
The description currently on the PROD is the correct one for a new "advanced screening: urban infrastructure" study and should not be replaced. 

The one on the DEV system is very specific and focuses on the RESCCUE project. I guess it is supposed to be a description for the RESCCUE data package? We should not delete it but copy the text and figures to another template or maybe to the specific study or data package. Do you know who entered this text? 

When do you plan the next synchronisation? I wanted to check some of the text as well (to make sure the correct text for exposure is used etc.) and add something too,

**Comment by patrickkaleta** [comment]
> The one on the DEV system is very specific and focuses on the RESCCUE project. I guess it is supposed to be a description for the RESCCUE data package?

That's what I thought as well...

> We should not delete it but copy the text and figures to another template or maybe to the specific study or data package. Do you know who entered this text?

No, but I'm guessing that it was someone from Meteogrid. I will talk to them and ask them to "move" that description to a RESCCUE-specific Study.

> When do you plan the next synchronisation? I wanted to check some of the text as well (to make sure the correct text for exposure is used etc.) and add something too,

My goal was to do it later today, but maybe I'll do it over the weekend or on Monday. So, if you want to first check and update the texts, go ahead and I'll wait.

**Comment by claudiahahn** [comment]
Thank you! I will have a look at it now.

**Comment by claudiahahn** [comment]
I just noticed, that when creating a new study and selecting _Advanced screening: Urban Infrastructure_, a study is created but without a “hazard characterization - local effect” tab: https://csis-dev.myclimateservice.eu/study/173/view/intro 

Also I cannot change the [templates](https://csis-dev.myclimateservice.eu/maintenance/gl-templates) for _Advanced Screening: Urban Infrastructure_
In this list, there is also no “hazard characterization - local effect” template listed anymore, only for the _[TEST] Advanced Urban Screening new_ there are all templates (with old text!) but again I cannot edit the templates. 
I could edit the Basic Screening text using the templates listed here. When selecting “edit” after the respective basic screening step, I would enter text under “step description”. Is that ok?

**Comment by claudiahahn** [comment]
[Study Introduction text](https://csis-dev.myclimateservice.eu/study/173/view/intro) for all study types should be updated!!
As default, the text stored under _EU-GL_ is displayed, but this should just be kept as an option.  

It should automatically / initially display the text and figures currently stored under “Advanced Screening Methodology” when selecting the “change description” button. The text under “Advanced Screening Methodology” does not describe the advanced screening methodology but provides a good introduction to CSIS and the EU-GL.

**Comment by patrickkaleta** [comment]
> I just noticed, that when creating a new study and selecting _Advanced screening: Urban Infrastructure_, a study is created but without a “hazard characterization - local effect” tab: https://csis-dev.myclimateservice.eu/study/173/view/intro

You're right, thanks for noticing. Someone removed the HC-LE step from the [Study type steps](https://csis-dev.myclimateservice.eu/taxonomy/term/1159/edit?destination=/admin/structure/taxonomy/manage/study_type/overview). 

I suppose this might have been (accidentally) done by @DenoBeno? Nonetheless, Denis was working on a new version of the Adv. Screening: Urban Infrastructure Study type [here](https://csis-dev.myclimateservice.eu/taxonomy/term/2217/edit?destination=/admin/structure/taxonomy/manage/study_type/overview), so @claudiahahn you can check those and I will then move this set of steps into the actual [Adv. Scr.: UI Study type](https://csis-dev.myclimateservice.eu/taxonomy/term/1159/edit?destination=/admin/structure/taxonomy/manage/study_type/overview)

**Comment by claudiahahn** [comment]
ok. Thank you. 
The text in these steps is old too, I cannot change it though. 

I will create a word document and put all the necessary changes in there.

**Comment by patrickkaleta** [comment]
> I will create a word document and put all the necessary changes in there.

I hope it's not too much asked, but could you please include in that document **all** text descriptions and not only those that need to be changed? I talked to Angela and they in fact  changed that one description by accident (it's fixed now). These accidental overwrites happen way too often and if they go unnoticed, the correct texts will be lost on PROD during synchronizations. Having a document with all the correct and up-to-date texts for the Study types could help us find and correct such mistakes.

**Comment by claudiahahn** [comment]
I have uploaded a word doc with text for the _Advanced Screening - Urban Infrastructure_ study type to [owncloud](https://newrepository.atosresearch.eu/index.php/apps/files/?dir=/CLARITY/WP1%20CO-Creation/T1.3%20Climate%20Services%20Co-Creation/CSIS-text&fileid=417380)

I contains the whole text, not only what I have changed. In the first parts (till Exposure step) I have made changes using the track changes mode, so you can see where I have changed or added things. So you can work with the text already in CSIS and just adjust where necessary. Otherwise, just accept all changes and include the whole text. 

For the steps ""Vulnerabiliy Analysis", "Risk and Impact Assessment" and "Adaptation Options Identification" I have copied text that is currently available on CSIS in the word document. For the last two steps (Risk and Impact, and Adaptation options) I have added a short paragraph at the end of the section. 



for the steps:

**Comment by claudiahahn** [comment]
I hope to upload a Word doc with text for the Basic screening on Monday

**Comment by DenoBeno** [comment]
Please note that we have two additional adaptation related steps now.

**Comment by claudiahahn** [comment]
I have updated the [templates](https://csis-dev.myclimateservice.eu/maintenance/gl-templates) for _Advanced Screening: Urban Infrastructure_ and _Basic Screening: General_ 
The word documents with the text are on [owncloud](https://newrepository.atosresearch.eu/index.php/apps/files/?dir=/CLARITY/WP1%20CO-Creation/T1.3%20Climate%20Services%20Co-Creation/CSIS-text&fileid=417380).

**Comment by claudiahahn** [comment]
> Study Introduction text for all study types should be updated!!
As default, the text stored under EU-GL is displayed, but this should just be kept as an option.

It should automatically / initially display (as default) the text and figures currently stored under “Advanced Screening Methodology” when selecting the “change description” button. The text under “Advanced Screening Methodology” does not describe the advanced screening methodology but provides a good introduction to CSIS and the EU-GL.

Could someone change that?

**Comment by patrickkaleta** [comment]
> > Study Introduction text for all study types should be updated!!
> > As default, the text stored under EU-GL is displayed, but this should just be kept as an option.
> 
> It should automatically / initially display (as default) the text and figures currently stored under “Advanced Screening Methodology” when selecting the “change description” button. The text under “Advanced Screening Methodology” does not describe the advanced screening methodology but provides a good introduction to CSIS and the EU-GL.
> 
> Could someone change that?

So, by default, instead of the [current introduction text](https://csis-dev.myclimateservice.eu/taxonomy/term/1/edit), you would like to display the [text](https://csis-dev.myclimateservice.eu/taxonomy/term/5747/edit) from the “Advanced Screening Methodology” taxonomy term? If that's so, we just need to copy the text from the "Advanced Screening Methodology" term into the "EU-GL" term.

**Comment by claudiahahn** [comment]
ok, Perfect. Then we should do that. 
The current introduction text could maybe be saved under a new "EU-GL-v2" taxonomy term. so that we don't loose it?

**Comment by claudiahahn** [comment]
or we just save it in a word document, just in case

**Comment by patrickkaleta** [comment]
Done. I saved the old text in a [new term](https://csis-dev.myclimateservice.eu/taxonomy/term/5816/edit), which I left unpublished, so it won't show up on the website for normal users, but it's still available for us if we ever need it again.

**Comment by patrickkaleta** [comment]
> or we just save it in a word document, just in case

That's also an option. Can't hurt to have these texts stored somewhere centralized outside the CSIS.

**Comment by claudiahahn** [comment]
Thank you!

**Comment by p-a-s-c-a-l** [comment]
done
