### ISSUE TITLE
CLARITY Data Package: Vulnerability Maps Resource specification

### ISSUE THREAD

**Issue by maesbri** [clarity-h2020/csis#16]
This task is responsible for defining the data structure of the Vulnerability Map(s) that will be included in CLARITY data package. This includes indicating:

how is the resource encoded (e.g., store the information in raster or vector format). Besides, in the case of using vector based data, a set of "standard" attributes must be defined for containing the information, so that all resources of this type have always the same set of attributes (and names) and CLARITY tools can process them in the same manner.
what formats are supported for this specific type of resource (e.g., for raster data: netcdf, geotiff, etc.; for vector data: geojson, shapefile, etc.)
what metadata attributes are used to describe this resource (refer to CLARITY General Data Package specification and https://frictionlessdata.io/specs/data-resource/).

In this task the following partners MUST be involved: METEOGRID/PLINIVS/ZAMG

**Comment by p-a-s-c-a-l** [comment]
@bernhardsk @stefanon 

Any idea what kind of resources we could add here to the data package? I though of the vulnerability curves (images) from one of the PKINIVS presentation. But perhaps there is already something forseen regarding vulnerability classes in the Data Package specification  @maesbri ?

**Comment by p-a-s-c-a-l** [comment]
Implementation of [VA API](https://github.com/clarity-h2020/emikat/issues/13) is currently on-hold. In the long term, we would provide some Vulnerability Curves Editor. ATM we just need a description for inclusion in the Data Package!

**Comment by p-a-s-c-a-l** [comment]
No support for Vulnerability Maps.
