### ISSUE TITLE
Paging in views broken 

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/csis#160]
_Originally posted by @DenoBeno in https://github.com/clarity-h2020/csis/issues/104#issuecomment-623531624_

Last week, I have stumbled into a very strange issue. It's IMO almost a "showstopper", but more interestingly, it's something I have never seen in Drupal except on CSIS.

**- paging links aren't shown**

E.g. on https://csis.myclimateservice.eu/adaptation-options, first 25 adaptation options are shown but no links to the next page is presented to users. 

Probably the same in https://csis.myclimateservice.eu/solution-offers and https://csis.myclimateservice.eu/showcases - I didn't check if they have paging enabled or not.

As long as the number of elements is small, we can use "show all" option, but this needs to be addressed.

**Comment by patrickkaleta** [comment]
Definitely strange behaviour. I removed the pager on that View and added it back again and now it's working as expected. Other pagers (for Showcases and Solution offers) are working just fine, so I guess this was just a weird bug affecting only one View.
