### ISSUE TITLE
Transport module embedded screen 

### ISSUE THREAD

**Issue by luis-meteogrid** [clarity-h2020/csis#167]
Is it possible to enlarge the embedded screen area for the TM? We are going to remove the menu bar but even doing that the map area remains still a bit small to work comfortably.

**Comment by p-a-s-c-a-l** [comment]
What is the required size in pixels?

**Comment by ghilbrae** [comment]
I think that @luis-meteogrid is aiming at something that makes using the TM from the CSIS more comfortable. I don't know if it is feasible to make it wider but it would definitely be an improvement if it was longer, maybe tale up the space that now is occupied by the **Select Scenario** button and the **No Study scenario currently selected**. Enlarging it as much as possible, TBH.

![image](https://user-images.githubusercontent.com/1615745/85854902-967d9e80-b7b5-11ea-9b91-77f62f318b86.png)

**Comment by ghilbrae** [comment]
@p-a-s-c-a-l we do not need the Scenarios for the TM studies so that button can safely disappear.

It could be useful in the future, if a better integration was developed and we could implement it on our side, but that seems quite improbable right now.

**Comment by p-a-s-c-a-l** [comment]
O.K. I've updated the iFrames and set the height to 800px in DEV instance (@patrickkaleta we have to make sure that *Extended iFrame* nodes are [synchronised](https://github.com/clarity-h2020/docker-drupal/issues/147), too) 

If the height is still not sufficient, you can easily change it yourself here:

- [Transport Application: Generic Table](https://csis-dev.myclimateservice.eu/node/4085/edit?destination=/admin/content%3Ftitle%3D%26type%3Dextended_iframe%26status%3DAll%26langcode%3DAll)
- [Transport Application: Generic Map](https://csis-dev.myclimateservice.eu/node/4084/edit?destination=/admin/content%3Ftitle%3D%26type%3Dextended_iframe%26status%3DAll%26langcode%3DAll)
- [Transport Application: Study Area Map](https://csis-dev.myclimateservice.eu/node/1982/edit?destination=/admin/content%3Ftitle%3D%26type%3Dextended_iframe%26status%3DAll%26langcode%3DAll)

That's the relevant code:

```html
    <iframe name="transport-application" id="transport-application"
         src="https://clarity.saver.red" style="width:100%;height:800px">
    </iframe>
```

Regarding the removal of the scenario selection controls, we have to ask @patrickkaleta

**Comment by ghilbrae** [comment]
Many thanks, it looks much better now!

**Comment by patrickkaleta** [comment]
> O.K. I've updated the iFrames and set the height to 800px in DEV instance 
> * [Transport Application: Study Area Map](https://csis-dev.myclimateservice.eu/node/1982/edit?destination=/admin/content%3Ftitle%3D%26type%3Dextended_iframe%26status%3DAll%26langcode%3DAll)

For that map the height was still 500px in DEV, so I've changed that to 800px (this will take affect on the live CSIS after the next synchronization).

> (@patrickkaleta we have to make sure that _Extended iFrame_ nodes are [synchronised](https://github.com/clarity-h2020/docker-drupal/issues/147), too)
>

This is already the case and the changes are active on the PROD instance.

> 
> Regarding the removal of the scenario selection controls, we have to ask @patrickkaleta

The scenario selection block is created by a [View](https://csis-dev.myclimateservice.eu/admin/structure/views/view/view_presets_and_edit/edit/block_2). I think I should be able to apply a filter that would hide this View depending on the Study type of currently viewed Study.
