### ISSUE TITLE
Adaptation Options for Expert Studies

### ISSUE THREAD

**Issue by ghilbrae** [clarity-h2020/csis#170]
We are working on the RESCCUE project study and we've found a few things. RESCCUE has two different groups of Adaptation Options, they can be interpreted as scenarios for AOs. Currently, when we create a scenario, the only options are with or without adaptation options. Would it be feasible to add two more options to this list to account for these groups?

**Comment by DenoBeno** [comment]
This is not how AOs in CSIS work. The "with AOs" option refers to use of adaptation scenario and is only relevant for advanced screening.

**Comment by p-a-s-c-a-l** [comment]
probably wontfix
