### ISSUE TITLE
Invalid web certificates?

### ISSUE THREAD

**Issue by patrickkaleta** [clarity-h2020/csis#173]
I tried to access https://csis.myclimateservice.eu/ and https://csis-dev.myclimateservice.eu/, but both were unreachable, Chrome said it couldn't establish a secure connection (exact error code in Chrome: `NET::ERR_CERT_AUTHORITY_INVALID`). 
Then after a while, suddenly https://csis-dev.myclimateservice.eu/ became accessible again, showing no more warnings or errors. What appears to be different in the two instances are the certicates - the DEV instance has a valid one, for the PROD instance it's apparently invalid.

Screenshot shows certificate issue for PROD on the left side, and the working certificate for DEV on the right side:
![certificate-invalid](https://user-images.githubusercontent.com/42167036/86892166-2e598180-c100-11ea-92f3-8d48b28facc1.png)

@Itsman-AT are you aware of any changes on our servers made by AIT or can you detect any unusual activities?

**Comment by p-a-s-c-a-l** [comment]
The certificate warning comes from the reverse proxy when the backend (drupal apache) is not reachable.
I'm currently [updating the docker containers](https://github.com/clarity-h2020/docker-drupal/issues/156) as announced on Monday so that @fgeyer16 can update Drupal Core and Modules.
