### ISSUE TITLE
Search radius isn't working in "twins"

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/csis#176]
I suppose this has something to do with change of the map type?

**Comment by patrickkaleta** [comment]
Where? On which Twins map? For [Hazard Char.](https://csis-dev.myclimateservice.eu/study/25/step/3681/view/twins) its working. For [Exposure](https://csis-dev.myclimateservice.eu/study/25/step/3683/view/twins) the Map type was wrong, but even despite that search radius was still working (I changed the map type on DEV to Leaflet, so it's now the correct one).

**Comment by patrickkaleta** [comment]
Search radius is working on map and on the "Available Twins" table. Only the "Included Twins" is not affected by the search radius, but that is on purpose. Closing this issue now.
