### ISSUE TITLE
AO appraisal step for advanced screening study

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/csis#177]
Summary: in advanced screening, differentiate between "AO Identification" and "AO appraisal" steps.

- [x] Define new templates for these two steps and adm to test study type
- [x] In AO identification allow the users to explore the available adaptation options
- [x] In AO appraisal, allow the users to define the adaptation strategy
- [x] In AO appraisal, allow the users to trigger re-calculation
- [x] In AO appraisal, allow the users to explore the difference between situation with and without adaptation options.

**Comment by DenoBeno** [comment]
I have defined a new "test" workflow that extends and improves the "Advanced screening". Some of it works as designed, some doesn't and will require your attention:

1) Possibility to trigger re-calculatioon directly from AO Appraisal step (easy to implement, I presume)
2) Possibility to use scenario analysis in this step. Currently nothing is shown at all, no idea why.
3) Possibility to visualize before/after situation in a map component. Currently the map works, but this is not possible.
4) Ideally, we should also be able to show simple cost / benefit analysis - currently not available AFAIK.

**Comment by patrickkaleta** [comment]
> 2\. Possibility to use scenario analysis in this step. Currently nothing is shown at all, no idea why.

Reason for that was that the [View](https://csis-dev.myclimateservice.eu/admin/structure/views/view/view_mode_for_gl_step/edit/page_7) had a filter applied, which allowed only GL-steps with the EU-GL methodology tax. term = "Risk and Impact Assessment". I've removed that filter and now the Scenario Analysis app is also shown in this AO appraisal step.

**Comment by p-a-s-c-a-l** [comment]
> Possibility to visualize before/after situation in a map component. Currently the map works, but this is not possible.

Adaptation Map is now implemented on DEV instance and can be tested [here](https://csis-dev.myclimateservice.eu/study/163/step/4896/view/maps):

![image](https://user-images.githubusercontent.com/1788226/88293703-a6789780-ccfb-11ea-8f7c-cbf41ae98831.png)

[Test Template: Adaptation Options Appraisal](https://csis-dev.myclimateservice.eu/node/4869/edit?destination=/admin/content%3Ftitle%3Dtemplate%26type%3Dgl_step%26status%3DAll%26langcode%3DAll) is also updated. Note that the maps don't show any difference, this is probably just a matter of [updating the styles](https://github.com/clarity-h2020/data-package/issues/73#issuecomment-654088923) in EMIKAT WMS.

Moreover, I've updated all tables to include **all** columns and adaptation scenarios when **downloading** the tables as JSON or CSV, so you can compare data offline.

**Comment by p-a-s-c-a-l** [comment]
> 2. Possibility to use scenario analysis

ATM I'm stuck here until the issues with **aggregated** "[view.2994](https://service.emikat.at/EmiKatTst/api/scenarios/3210/feature/view.2994/table/data)" are fixed and/or with adaptation results [randomly disappearing](https://github.com/clarity-h2020/emikat/issues/17#issuecomment-663459437).

**Comment by p-a-s-c-a-l** [comment]
[Scenario Analysis](https://csis-dev.myclimateservice.eu/study/163/step/4894/view/scenario-analysis) has been updated on CSIS-DEV. ATM all indicators [available](https://github.com/clarity-h2020/scenario-analysis/issues/24#issuecomment-663535694) in [EMIKAT view.2994](https://service.emikat.at/EmiKatTst/api/scenarios/3207/feature/view.2994/table/data) are shown, Pluvial Flood indicators yet [to come](https://github.com/clarity-h2020/emikat/issues/46).

![image](https://user-images.githubusercontent.com/1788226/88395523-83182000-cdc1-11ea-900f-dcb2b9866290.png)

I'm not sure about the cost and the unit of "Heat Wave Impact", though. Furthermore, adaptation scenarios as well as some values [randomly appear and disappear](https://github.com/clarity-h2020/emikat/issues/17#issuecomment-663459437).

Furthermore, there is no difference between Scenario Analysis in RA/IA and AOAP Step. So the only difference is the Map, which shows Baseline (left) and Adaptation Scenarios (right) on in the new AOAP step. I don't know if this really justifies the new AOAP or if we better  just change the map in the RA/IA step.

**Comment by p-a-s-c-a-l** [comment]
Now with pluvial flood:

![image](https://user-images.githubusercontent.com/1788226/88678018-495f5600-d0ee-11ea-9a3e-5a43e780710f.png)

[Example Study 25](https://csis-dev.myclimateservice.eu/study/25/step/5110/view/scenario-analysis) on CSIS DEV.

**Note:** Scenario Analysis on PROD-CSIS is **broken** since EMIKAT API changed. 

Before I make a new public release, please let me know if you want any change of indicator name / units @claudiahahn @DenoBeno @mattia-leone

**Comment by claudiahahn** [comment]
This might be an unqualified comment, but without an explanation of the indicators they'll not be very helpfull for the user. 
I have been on vacation, so maybe I have missed the discussion about that. But it seems that the indicators are not explained in any of the tabs under the "Risk/Impact" step. What does heat wave impact mean, or damage class mean?

**Comment by p-a-s-c-a-l** [comment]
> What does heat wave impact mean, or damage class mean?

This is a good question. I think this information  is somewhere hidden in [vulnerability](https://csis-dev.myclimateservice.eu/study/25/step/5109/view/table) whereas I'm sure whether is this conceptually consistent or not.

Anyway, this should be explained in the [respective resource](https://csis-dev.myclimateservice.eu/node/1356) so that it is visible on the [RA/IA data tab](https://csis-dev.myclimateservice.eu/study/25/step/5110/view/data).

**Comment by claudiahahn** [comment]
ah, true. There it is. Thanks @p-a-s-c-a-l 
In addition to the explanation in the resource itself, it might also be an option to add a short note next to "indicator" under the Risk/Impact step and to link to the vulnerability site. 
something like: "Information about the indicators can be found here"

**Comment by DenoBeno** [comment]
We can very easily add texts. Either in introduction of the step or at the page. Just tell us what to write.

**Comment by DenoBeno** [comment]
@p-a-s-c-a-l :

There is indeed no difference between Scenario Analysis in RA/IA and AOAP steps. Except for the maps.

I don't really care,  but if this turns out to be a problem,  we can disable everything except for the map in RA/IA step.

My vote is on "let it be for now " .

Even better would be to hide all "with AO" from RA/IA step,  but again I don't see this as important.

**Comment by claudiahahn** [comment]
> We can very easily add texts. Either in introduction of the step or at the page. Just tell us what to write.

on that page it would be good to insert: "Information about the indicators are available in the "Vulnerability" step, under the "Table" tab".

**Comment by DenoBeno** [comment]
I have added the missing files to vulnerability descriptions on CSIS. Synchronization failed to copy them, so I did it per hand now. They could disappear again on next sync though.

**Comment by patrickkaleta** [comment]
Can this be closed now?
