### ISSUE TITLE
Create new Showcases directly on PROD rather than on DEV

### ISSUE THREAD

**Issue by patrickkaleta** [clarity-h2020/csis#178]
**Problem:**
As mentioned [here](https://github.com/clarity-h2020/csis-technical-validation/issues/63), there is currently now migration file for Showcases. So I started working on it and realized the complications with that. Showcases reference Solution providers, which are users in our system. However, we deactivated CAS (Single-sign-on) on DEV, so newly created users on our Profiles-page are not automatically imported into DEV. Therefore, it won't be possible to select those new users as Solution providers for new Showcases! 

**Solution:**
I propose that we allow editors to create new Showcases directly on PROD. Showcases are not connected to Data packages or resources in any way (these two content types and their complexity are the main reason why we even decided to create new content on DEV first and then sync it with PROD), so they're relatively easy to create and threaten the functionality and stability of the CSIS.

A couple of Showcases have now already been added by PLENIVS to DEV, which I would move manually to PROD, so that we don't lose any of our Showcases.

**Comment by patrickkaleta** [comment]
Allowing for Showcases to be created directly on PROD is a much faster solution than trying to come up with a way how to import new users into DEV, so that they could then be referenced in Showcases.

@p-a-s-c-a-l and @fgeyer16 is that solution ok for you?

**Comment by p-a-s-c-a-l** [comment]
O.K. But then we have to prevent users from creating showcases in DEV instance.

**Comment by patrickkaleta** [comment]
> O.K. But then we have to prevent users from creating showcases in DEV instance.

Agreed. I will remove the respective permissions from DEV.

**Comment by patrickkaleta** [comment]
Done. Showcases can be added directly in PROD and no longer on DEV.
