### ISSUE TITLE
Making Studies Public

### ISSUE THREAD

**Issue by ghilbrae** [clarity-h2020/csis#179]
Is there a way to make a Study public to anonymous users?

I understand that the option when creating a Study and ticking the checkbox in the context tab is to make them public within the CSIS only.

**Comment by patrickkaleta** [comment]
Yes, this can be done in the [settings](https://csis.myclimateservice.eu/admin/config/csis_helpers/default) for the CSIS helpers module. Just let me know which Study you would like to make accessible even to anonymous users and I can configure it on the PROD site.

**Comment by patrickkaleta** [comment]
@ghilbrae Can I close this now? Did you have a specific Study in mind, which I should make public for everyone or was this just a general question if something like is even possible at all?

**Comment by ghilbrae** [comment]
Sure, sorry I forgot.
