### ISSUE TITLE
CLARITY Data Package: Impact Maps Resource specification

### ISSUE THREAD

**Issue by maesbri** [clarity-h2020/csis#18]
This task is responsible for defining the data structure of the Impact Map(s) that will be included in CLARITY data package. This includes indicating:

how is the resource encoded (e.g., store the information in raster or vector format). Besides, in the case of using vector based data, a set of "standard" attributes must be defined for containing the information, so that all resources of this type have always the same set of attributes (and names) and CLARITY tools can process them in the same manner.
what formats are supported for this specific type of resource (e.g., for raster data: netcdf, geotiff, etc.; for vector data: geojson, shapefile, etc.)
what metadata attributes are used to describe this resource (refer to CLARITY General Data Package specification and https://frictionlessdata.io/specs/data-resource/).
In this task the following partners MUST be involved: PLINIVS

**Comment by p-a-s-c-a-l** [comment]
RA/IA resources are being defined [in this issue](https://github.com/clarity-h2020/data-package/issues/16) referring to the [RA/IA EMIKKAT API](https://github.com/clarity-h2020/emikat/issues/9) but are not yet available. However, the [Impact Scenarios Taxonomy](https://csis.myclimateservice.eu/admin/structure/taxonomy/manage/impact_scenarios/overview) doesn't seem be complete / correct.

**Comment by p-a-s-c-a-l** [comment]
done
