### ISSUE TITLE
Advanced urban screening with EMIKAT calculation type disappeared in CSIS-dev

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/csis#181]
I have just noticed that the Advanced urban screening study calculation type has disappeared in csis-dev. Instead of it there is one called BARCELONA RESEARCH SITES.

https://csis.myclimateservice.eu/taxonomy/term/2218 - this is what it should be

![image](https://user-images.githubusercontent.com/2961790/88534903-46d70080-d009-11ea-8ef1-6360537089b1.png)

https://csis-dev.myclimateservice.eu/taxonomy/term/2218 - and this is what we have in csis-dev now.

![image](https://user-images.githubusercontent.com/2961790/88534865-3757b780-d009-11ea-98d9-9b7d86179420.png)

As a result, all urban screening studies in csis-dev will have wrong description for the calculation now. Calculation is not affected since it just looks at the calculation method ID.

Who and why changed this?

**Comment by DenoBeno** [comment]
Since I'm at it, I'll put it back to original state now. Please don't change it...

**Comment by patrickkaleta** [comment]
@ghilbrae wanted to make some changes for the Studies used by the TM ("Adv. Screening: Transport Infrastr.") a while back (#171). Maybe during those updates this text was also changed by mistake?

**Comment by p-a-s-c-a-l** [comment]
resolved
