### ISSUE TITLE
Expert Studies

### ISSUE THREAD

**Issue by luis-meteogrid** [clarity-h2020/csis#182]
We are trying to create the three RESCCUE expert studies and we are finding some difficulties. First one is that should we want to use all the methodology steps the only option we have is to create an advanced screening study. The second an most important one is that we can no create expert studies for cities/regions not available in CSIS. 

In RESCCUE one of the cities is Bristol, that is not available in CSIS. They don't need local effects and they have their own reference layers and of course their own climate related data that we are uploading into a new datapackage. 

Is it possible to allow expert studies in CSIS without the need the city is included in the CSIS city-set?

**Comment by patrickkaleta** [comment]
Hi @luis-meteogrid,

**Regarding your first problem (available steps in Expert Studies):**
which methodology steps do you need that are currently missing? The both Expert Study types "Expert: Urban infrastructure" and "Expert: Transport Infrastructure" feature all the steps expect for "Hazard Characterization - Local effects", which according to your comment is not even needed. Only the Study type "Expert: General" has a more limited selection of methodology steps.

**Regarding your second problem (selecting cities which are not supported):**
I don't see a way how we could cleanly integrate "pseudo-supported" cities into our actually supported cities list, but AFAIK for Expert Studies the city field is not required, so you could leave it empty and only select the country. In the Study area map you should then still be able to zoom into Bristol and mark the area as your Study area. You can try it out on the DEV instance and create a Study there to see if it's possible to achieve what you're looking for.

**Comment by luis-meteogrid** [comment]
Thank you Patrick. We have already checked that it is possible to select the Bristol Area in Basic Screening studies although there is no Vulnerability step, so we'll be able to create the study, but just to know, is there a possibility of creating expert studies for urban and transport? Our user does not offer that possibility (neither meteogrid, nor Angela), they allow us to choose just among  Basic Urban, Advanced Urban and Advanced Transport.

**Comment by patrickkaleta** [comment]
> Thank you Patrick. We have already checked that it is possible to select the Bristol Area in Basic Screening studies although there is no Vulnerability step, so we'll be able to create the study, but just to know, is there a possibility of creating expert studies for urban and transport? Our user does not offer that possibility (neither meteogrid, nor Angela), they allow us to choose just among Basic Urban, Advanced Urban and Advanced Transport.

My bad, your users didn't have the permissions for the two Expert Study types I was talking about. I fixed that, so now you should be able to create those as well.

**Comment by luis-meteogrid** [comment]
Tank you Patrick
