### ISSUE TITLE
Request Permissions for User

### ISSUE THREAD

**Issue by ghilbrae** [clarity-h2020/csis#183]
Hi! We'd like for user LauraParra to have permissions to create Transport Studies. Thanks!

**Comment by patrickkaleta** [comment]
I gave her the user role of "Expert", which allows her now to create such Studies. 

@ghilbrae: 
In that regard, Transport Studies (Study type: "**Advanced Screening: Transport Infrastructure**") can currently be created by users with the roles "**Admin**", "**Editor**" or "**Expert**". Is this configuration meant only temporary until this Study type has all the remaining features implemented (e.g. the PDF report from the TM) or is this already the final configuration and ordinary, registered users without any special roles are not allowed to create such Studies?

**Comment by ghilbrae** [comment]
The final configuration should allow ordinary users to create Transport Studies.

**Comment by patrickkaleta** [comment]
> The final configuration should allow ordinary users to create Transport Studies.

Done. On DEV it's now configured so that ordinary users can create Transport Studies as well. Will be available on PROD after next sync process.
