### ISSUE TITLE
CLARITY Data Package: Adaptation Options Resource specification

### ISSUE THREAD

**Issue by maesbri** [clarity-h2020/csis#19]
This task is responsible for defining the data structure of the Adaptation Options resource that will be included in CLARITY data package. This includes indicating:

how is the resource encoded (e.g., store the information in raster or vector format). Besides, in the case of using vector based data, a set of "standard" attributes must be defined for containing the information, so that all resources of this type have always the same set of attributes (and names) and CLARITY tools can process them in the same manner.
what formats are supported for this specific type of resource (e.g., for raster data: netcdf, geotiff, etc.; for vector data: geojson, shapefile, etc.)
what metadata attributes are used to describe this resource (refer to CLARITY General Data Package specification and https://frictionlessdata.io/specs/data-resource/).

The definition of the Adaptation Options resource will be based on EMIKAT

In this task the following partners MUST be involved: AIT

**Comment by therter** [comment]
@maesbri This is ok for me

**Comment by maesbri** [comment]
Adaptation options file has been updated according to https://github.com/clarity-h2020/table-components/issues/6 and added as resource to the Naples data package.

**Comment by p-a-s-c-a-l** [comment]
done

**Comment by p-a-s-c-a-l** [comment]
Adaptation Options specified but Data Package Resource Meta-Data [not yet available](https://github.com/clarity-h2020/data-package/issues/17).
