### ISSUE TITLE
European Transport Studies Data Package selection

### ISSUE THREAD

**Issue by ghilbrae** [clarity-h2020/csis#190]
Hi! We have created a Data Package for European  Transport Studies https://csis-dev.myclimateservice.eu/node/5580 and we've tried to assign it to a study but it is not available in any type of study. We've tried Basic Studies, Advanced Transport and Expert Transport but it is not available in any of them. Is there something we are missing? How do we make the DP available?

**Comment by patrickkaleta** [comment]
In which Study types a DP can be used is decided by the calculation methods set inside the DP. For your DP it was set to "**Emikat screening**", so it was available in "**Advanced Screening: Urban Infrastructure**" Studies.

![tm-datapackage](https://user-images.githubusercontent.com/42167036/93574720-0d7f9900-f999-11ea-9ce4-15b26b274a39.png)


I've changed the calculation method to "**Meteogrid transport screening**" and now the DP is available in "**Advanced Screening: Transport Infrastructure**" Studies.

For which Study types do you want this DP to be available?

**Comment by ghilbrae** [comment]
> In which Study types a DP can be used is decided by the calculation methods set inside the DP. For your DP it was set to "**Emikat screening**", so it was available in "**Advanced Screening: Urban Infrastructure**" Studies.
> 
Thanks a lot for the info, it seems we didn't realize that detail :)

> For which Study types do you want this DP to be available?

We think it would be safest to have the DP available for both Advanced and Expert studies, to have something to work with in both cases.

**Comment by patrickkaleta** [comment]
> > For which Study types do you want this DP to be available?
> 
> We think it would be safest to have the DP available for both Advanced and Expert studies, to have something to work with in both cases.

Done and synchronization from DEV -> PROD has also been performed. You should now be able to use the new data package on the live CSIS.

**Comment by patrickkaleta** [comment]
I guess this can be closed now...
