### ISSUE TITLE
https://geoserver.myclimateservice.eu/ not accessible

### ISSUE THREAD

**Issue by patrickkaleta** [clarity-h2020/csis#192]
CSIS can't show layers provided by this GeoServer. There seems to be a problem with the certificate or the date/time setting on the server. Chrome throws this error message: NET::ERR_CERT_DATE_INVALID

**Comment by maesbri** [comment]
Hi,

Yes, we are aware of it.

In any case there is an ongoing restructuring of our IT services within our department, implying a change of domain names. Taking advantage of this, we have asked for a wildcard certificate for the domain we have acquired for our unit and plan to apply it for all the services hosted in our servers.

This transition will also imply switching off temporarily CLARITY services and performing various configurations with the reverse proxy we plan to set up to manage all this. I hope we can do it in a single day. 

We'll let you know when the services will be unavailable.

**Comment by DanielRodera** [comment]
Hi @patrickkaleta, 

The certificate has been renovated,

**Comment by patrickkaleta** [comment]
Thanks @maesbri and @DanielRodera for fast response and handling. GeoServer and its layers are accessible again.
