### ISSUE TITLE
CLARITY Data Package: Example

### ISSUE THREAD

**Issue by maesbri** [clarity-h2020/csis#20]
This task will provide a comprehensive example of CLARITY Data Package with all possible resources it can contain.

In this task the following partners MUST be involved: METEOGRID/PLINIVS/ZAMG/ATOS/AIT

This task is broken down into the the following sub-tasks:

- [ ] [00 Background Layers](https://github.com/clarity-h2020/data-package/issues/4)
- [ ] [01 HC Layers](https://github.com/clarity-h2020/data-package/issues/8)
- [ ] [02 Hazard Local Effects Layers](https://github.com/clarity-h2020/data-package/issues/11)
- [ ] [03 Exposure Layers](https://github.com/clarity-h2020/data-package/issues/10)
- [ ] [04 Vulnerability Curves](https://github.com/clarity-h2020/data-package/issues/15)
- [ ] [05 Risk & Impact ](https://github.com/clarity-h2020/data-package/issues/16)
- [ ] [06 Adaptation Scenarios](https://github.com/clarity-h2020/data-package/issues/17)

**Comment by p-a-s-c-a-l** [comment]
Also related to @humerh 's activities to develop a concrete example.

**Comment by p-a-s-c-a-l** [comment]
Detailed sub-tasks are defined in the data-package repository: **[Milestone: 1st Data Package](https://github.com/clarity-h2020/data-package/milestone/1)**

Later, these tasks may serve as blueprint or "how-to" for creating Data Packages for the Demonstration Cases and as input for the [CLARITY Guideline](https://github.com/clarity-h2020/csis/milestone/11).

**Comment by p-a-s-c-a-l** [comment]
Draft 1st Data Package available at https://csis.myclimateservice.eu/node/100/

**Comment by negroscuro** [comment]
-Population 15 to 65 WMS:
https://clarity.meteogrid.com/geoserver/clarity/wms?service=WMS&version=1.1.0&request=GetMap&layers=clarity%3APopulation_15to65_naples&bbox=4647500.0%2C1947500.0%2C4716000.0%2C2003000.0&width=768&height=622&srs=EPSG%3A3035&format=image%2Fgif

-Population 15 to 65 WCS:
https://clarity.meteogrid.com/geoserver/wcs?SERVICE=WCS&VERSION=2.0.1&REQUEST=GetCoverage&COVERAGEID=clarity:Population_15to65_naples&FORMAT=image/tiff

-Population_mayor65_naples WMS:
https://clarity.meteogrid.com/geoserver/clarity/wms?service=WMS&version=1.1.0&request=GetMap&layers=clarity%3APopulation_mayor65_naples&bbox=4647500.0%2C1947500.0%2C4716000.0%2C2003000.0&width=768&height=622&srs=EPSG%3A3035&format=image%2Fgif

-Population_mayor65_naples WCS:
https://clarity.meteogrid.com/geoserver/wcs?SERVICE=WCS&VERSION=2.0.1&REQUEST=GetCoverage&COVERAGEID=clarity:Population_mayor65_naples&FORMAT=image/tiff

-Population_men15_naples WMS:
https://clarity.meteogrid.com/geoserver/clarity/wms?service=WMS&version=1.1.0&request=GetMap&layers=clarity%3APopulation_men15_naples&bbox=4647500.0%2C1947500.0%2C4716000.0%2C2003000.0&width=768&height=622&srs=EPSG%3A3035&format=image%2Fgif

-Population_men15_naples WCS:
https://clarity.meteogrid.com/geoserver/wcs?SERVICE=WCS&VERSION=2.0.1&REQUEST=GetCoverage&COVERAGEID=clarity%3APopulation_men15_naples&FORMAT=image/tiff

**Comment by negroscuro** [comment]
INPUT LAYERS

-it003l3_napoli_ua2012_agricultural_areas WMS:
http://5.79.69.33:8080/geoserver/clarity/wms?service=WMS&version=1.1.0&request=GetMap&layers=clarity%3Ait003l3_napoli_ua2012_agricultural_areas&bbox=4647975.0%2C1948174.625%2C4719495.0%2C2007715.625&width=768&height=639&srs=EPSG%3A3035&format=image%2Fgif

-it003l3_napoli_ua2012_agricultural_areas WFS:
http://5.79.69.33:8080/geoserver/clarity/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=clarity%3Ait003l3_napoli_ua2012_agricultural_areas&maxFeatures=50&outputFormat=gml3

-it003l3_napoli_ua2012_buildings WMS:
http://5.79.69.33:8080/geoserver/clarity/wms?service=WMS&version=1.1.0&request=GetMap&layers=clarity%3Ait003l3_napoli_ua2012_buildings&bbox=4644000.0%2C1842000.0%2C4844000.0%2C2042000.0&width=768&height=768&srs=EPSG%3A3035&format=image%2Fgif

-it003l3_napoli_ua2012_buildings WFS:
http://5.79.69.33:8080/geoserver/clarity/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=clarity%3Ait003l3_napoli_ua2012_buildings&maxFeatures=50&outputFormat=gml3

-it003l3_napoli_ua2012_built_open_spaces WMS:
http://5.79.69.33:8080/geoserver/clarity/wms?service=WMS&version=1.1.0&request=GetMap&layers=clarity%3Ait003l3_napoli_ua2012_built_open_spaces&bbox=4644000.0%2C1842000.0%2C4844000.0%2C2042000.0&width=768&height=768&srs=EPSG%3A3035&format=image%2Fgif

-it003l3_napoli_ua2012_built_open_spaces WCS:
http://5.79.69.33:8080/geoserver/clarity/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=clarity%3Ait003l3_napoli_ua2012_built_open_spaces&maxFeatures=50&outputFormat=gml3

-it003l3_napoli_ua2012_dense_urban_fabric WMS:
http://5.79.69.33:8080/geoserver/clarity/wms?service=WMS&version=1.1.0&request=GetMap&layers=clarity%3Ait003l3_napoli_ua2012_dense_urban_fabric&bbox=4648001.5%2C1949174.0%2C4715851.0%2C2006295.625&width=768&height=646&srs=EPSG%3A3035&format=image%2Fgif

-it003l3_napoli_ua2012_dense_urban_fabric WFS:
http://5.79.69.33:8080/geoserver/clarity/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=clarity%3Ait003l3_napoli_ua2012_dense_urban_fabric&maxFeatures=50&outputFormat=gml3

-it003l3_napoli_ua2012_low_urban_fabric WMS:
http://5.79.69.33:8080/geoserver/clarity/wms?service=WMS&version=1.1.0&request=GetMap&layers=clarity%3Ait003l3_napoli_ua2012_low_urban_fabric&bbox=4648108.5%2C1947818.375%2C4719095.5%2C2007671.125&width=768&height=647&srs=EPSG%3A3035&format=image%2Fgif

-it003l3_napoli_ua2012_low_urban_fabric WFS:
http://5.79.69.33:8080/geoserver/clarity/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=clarity%3Ait003l3_napoli_ua2012_low_urban_fabric&maxFeatures=50&outputFormat=gml3

-it003l3_napoli_ua2012_medium_urban_fabric WMS:
http://5.79.69.33:8080/geoserver/clarity/wms?service=WMS&version=1.1.0&request=GetMap&layers=clarity%3Ait003l3_napoli_ua2012_medium_urban_fabric&bbox=4647990.0%2C1949038.625%2C4715089.0%2C2007544.25&width=768&height=669&srs=EPSG%3A3035&format=image%2Fgif

-it003l3_napoli_ua2012_medium_urban_fabric WFS:
http://5.79.69.33:8080/geoserver/clarity/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=clarity%3Ait003l3_napoli_ua2012_medium_urban_fabric&maxFeatures=50&outputFormat=gml3

-it003l3_napoli_ua2012_public_military_industrial WMS:
http://5.79.69.33:8080/geoserver/clarity/wms?service=WMS&version=1.1.0&request=GetMap&layers=clarity%3Ait003l3_napoli_ua2012_public_military_industrial&bbox=4647900.0%2C1947678.25%2C4715292.5%2C2006729.125&width=768&height=672&srs=EPSG%3A3035&format=image%2Fgif

-it003l3_napoli_ua2012_public_military_industrial WFS:
http://5.79.69.33:8080/geoserver/clarity/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=clarity%3Ait003l3_napoli_ua2012_public_military_industrial&maxFeatures=50&outputFormat=gml3

-it003l3_napoli_ua2012_railways WMS:
http://5.79.69.33:8080/geoserver/clarity/wms?service=WMS&version=1.1.0&request=GetMap&layers=clarity%3Ait003l3_napoli_ua2012_railways&bbox=4663608.0%2C1958316.625%2C4711241.5%2C2002387.125&width=768&height=710&srs=EPSG%3A3035&format=image%2Fgif

-it003l3_napoli_ua2012_railways WFS:
http://5.79.69.33:8080/geoserver/clarity/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=clarity%3Ait003l3_napoli_ua2012_railways&maxFeatures=50&outputFormat=gml3

-it003l3_napoli_ua2012_roads WMS:
http://5.79.69.33:8080/geoserver/clarity/wms?service=WMS&version=1.1.0&request=GetMap&layers=clarity%3Ait003l3_napoli_ua2012_roads&bbox=4647967.5%2C1947662.0%2C4719111.5%2C2007704.625&width=768&height=648&srs=EPSG%3A3035&format=image%2Fgif

-it003l3_napoli_ua2012_roads WFS:
http://5.79.69.33:8080/geoserver/clarity/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=clarity%3Ait003l3_napoli_ua2012_roads&maxFeatures=50&outputFormat=gml3

-it003l3_napoli_ua2012_trees WMS:
http://5.79.69.33:8080/geoserver/clarity/wms?service=WMS&version=1.1.0&request=GetMap&layers=clarity%3Ait003l3_napoli_ua2012_trees&bbox=4647803.5%2C1947602.125%2C4720258.5%2C2006546.625&width=768&height=624&srs=EPSG%3A3035&format=image%2Fgif

-it003l3_napoli_ua2012_trees WFS:
http://5.79.69.33:8080/geoserver/clarity/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=clarity%3Ait003l3_napoli_ua2012_trees&maxFeatures=50&outputFormat=gml3

-it003l3_napoli_ua2012_vegetation WMS:
http://5.79.69.33:8080/geoserver/clarity/wms?service=WMS&version=1.1.0&request=GetMap&layers=clarity%3Ait003l3_napoli_ua2012_vegetation&bbox=4647780.5%2C1947569.625%2C4719056.0%2C2007621.75&width=768&height=647&srs=EPSG%3A3035&format=image%2Fgif

-it003l3_napoli_ua2012_vegetation WFS:
http://5.79.69.33:8080/geoserver/clarity/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=clarity%3Ait003l3_napoli_ua2012_vegetation&maxFeatures=50&outputFormat=gml3

-it003l3_napoli_ua2012_water WMS:
http://5.79.69.33:8080/geoserver/clarity/wms?service=WMS&version=1.1.0&request=GetMap&layers=clarity%3Ait003l3_napoli_ua2012_water&bbox=4647680.5%2C1947469.875%2C4709668.0%2C2005923.75&width=768&height=724&srs=EPSG%3A3035&format=image%2Fgif

-it003l3_napoli_ua2012_water WFS:
http://5.79.69.33:8080/geoserver/clarity/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=clarity%3Ait003l3_napoli_ua2012_water&maxFeatures=50&outputFormat=gml3

**Comment by negroscuro** [comment]
-Tx75p_consecutive_max_EUR-11_ICHEC-EC-EARTH_historical_r12i1p1_SMHI-RCA4_v1_day_19710101-20001231_netcdf3 WMS:
https://clarity.meteogrid.com/geoserver/clarity/wms?service=WMS&version=1.1.0&request=GetMap&layers=clarity%3ATx75p_consecutive_max_EUR-11_ICHEC-EC-EARTH_historical_r12i1p1_SMHI-RCA4_v1_day_19710101-20001231_netcdf3&bbox=2145500.0%2C982500.0%2C6606000.0%2C5706500.0&width=725&height=768&srs=EPSG%3A3035&format=image%2Fgif

-Tx75p_consecutive_max_EUR-11_ICHEC-EC-EARTH_historical_r12i1p1_SMHI-RCA4_v1_day_19710101-20001231_netcdf3 WCS:
https://clarity.meteogrid.com/geoserver/wcs?SERVICE=WCS&VERSION=2.0.1&REQUEST=GetCoverage&COVERAGEID=clarity:Tx75p_consecutive_max_EUR-11_ICHEC-EC-EARTH_historical_r12i1p1_SMHI-RCA4_v1_day_19710101-20001231_netcdf3&FORMAT=image/tiff

-Tx75p_consecutive_max_EUR-11_ICHEC-EC-EARTH_rcp26_r12i1p1_SMHI-RCA4_v1_day_20110101-20401231_netcdf3 WMS:
https://clarity.meteogrid.com/geoserver/clarity/wms?service=WMS&version=1.1.0&request=GetMap&layers=clarity%3ATx75p_consecutive_max_EUR-11_ICHEC-EC-EARTH_rcp26_r12i1p1_SMHI-RCA4_v1_day_20110101-20401231_netcdf3&bbox=2145500.0%2C982500.0%2C6606000.0%2C5706500.0&width=725&height=768&srs=EPSG%3A3035&format=image%2Fgif

-Tx75p_consecutive_max_EUR-11_ICHEC-EC-EARTH_rcp26_r12i1p1_SMHI-RCA4_v1_day_20110101-20401231_netcdf3 WCS:
https://clarity.meteogrid.com/geoserver/wcs?SERVICE=WCS&VERSION=2.0.1&REQUEST=GetCoverage&COVERAGEID=clarity:Tx75p_consecutive_max_EUR-11_ICHEC-EC-EARTH_rcp26_r12i1p1_SMHI-RCA4_v1_day_20110101-20401231_netcdf3&FORMAT=image/tiff

-Tx75p_consecutive_max_EUR-11_ICHEC-EC-EARTH_rcp26_r12i1p1_SMHI-RCA4_v1_day_20410101-20701231_netcdf3 WMS:
https://clarity.meteogrid.com/geoserver/clarity/wms?service=WMS&version=1.1.0&request=GetMap&layers=clarity%3ATx75p_consecutive_max_EUR-11_ICHEC-EC-EARTH_rcp26_r12i1p1_SMHI-RCA4_v1_day_20410101-20701231_netcdf3&bbox=2145500.0%2C982500.0%2C6606000.0%2C5706500.0&width=725&height=768&srs=EPSG%3A3035&format=image%2Fgif

-Tx75p_consecutive_max_EUR-11_ICHEC-EC-EARTH_rcp26_r12i1p1_SMHI-RCA4_v1_day_20410101-20701231_netcdf3 WCS:
https://clarity.meteogrid.com/geoserver/wcs?SERVICE=WCS&VERSION=2.0.1&REQUEST=GetCoverage&COVERAGEID=clarity:Tx75p_consecutive_max_EUR-11_ICHEC-EC-EARTH_rcp26_r12i1p1_SMHI-RCA4_v1_day_20410101-20701231_netcdf3&FORMAT=image/tiff

-Tx75p_consecutive_max_EUR-11_ICHEC-EC-EARTH_rcp26_r12i1p1_SMHI-RCA4_v1_day_20710101-21001231_netcdf3 WMS:
https://clarity.meteogrid.com/geoserver/clarity/wms?service=WMS&version=1.1.0&request=GetMap&layers=clarity%3ATx75p_consecutive_max_EUR-11_ICHEC-EC-EARTH_rcp26_r12i1p1_SMHI-RCA4_v1_day_20710101-21001231_netcdf3&bbox=2145500.0%2C982500.0%2C6606000.0%2C5706500.0&width=725&height=768&srs=EPSG%3A3035&format=image%2Fgif

-Tx75p_consecutive_max_EUR-11_ICHEC-EC-EARTH_rcp26_r12i1p1_SMHI-RCA4_v1_day_20710101-21001231_netcdf3 WCS:
https://clarity.meteogrid.com/geoserver/wcs?SERVICE=WCS&VERSION=2.0.1&REQUEST=GetCoverage&COVERAGEID=clarity:Tx75p_consecutive_max_EUR-11_ICHEC-EC-EARTH_rcp26_r12i1p1_SMHI-RCA4_v1_day_20710101-21001231_netcdf3&FORMAT=image/tiff

-Tx75p_consecutive_max_EUR-11_ICHEC-EC-EARTH_rcp45_r12i1p1_SMHI-RCA4_v1_day_20110101-20401231_netcdf3 WMS:
https://clarity.meteogrid.com/geoserver/clarity/wms?service=WMS&version=1.1.0&request=GetMap&layers=clarity%3ATx75p_consecutive_max_EUR-11_ICHEC-EC-EARTH_rcp45_r12i1p1_SMHI-RCA4_v1_day_20110101-20401231_netcdf3&bbox=2145500.0%2C982500.0%2C6606000.0%2C5706500.0&width=725&height=768&srs=EPSG%3A3035&format=image%2Fgif

-Tx75p_consecutive_max_EUR-11_ICHEC-EC-EARTH_rcp45_r12i1p1_SMHI-RCA4_v1_day_20110101-20401231_netcdf3 WCS:
https://clarity.meteogrid.com/geoserver/wcs?SERVICE=WCS&VERSION=2.0.1&REQUEST=GetCoverage&COVERAGEID=clarity:Tx75p_consecutive_max_EUR-11_ICHEC-EC-EARTH_rcp45_r12i1p1_SMHI-RCA4_v1_day_20110101-20401231_netcdf3&FORMAT=image/tiff

-Tx75p_consecutive_max_EUR-11_ICHEC-EC-EARTH_rcp45_r12i1p1_SMHI-RCA4_v1_day_20410101-20701231_netcdf3 WMS:
https://clarity.meteogrid.com/geoserver/clarity/wms?service=WMS&version=1.1.0&request=GetMap&layers=clarity%3ATx75p_consecutive_max_EUR-11_ICHEC-EC-EARTH_rcp45_r12i1p1_SMHI-RCA4_v1_day_20410101-20701231_netcdf3&bbox=2145500.0%2C982500.0%2C6606000.0%2C5706500.0&width=725&height=768&srs=EPSG%3A3035&format=image%2Fgif

-Tx75p_consecutive_max_EUR-11_ICHEC-EC-EARTH_rcp45_r12i1p1_SMHI-RCA4_v1_day_20410101-20701231_netcdf3 WCS:
https://clarity.meteogrid.com/geoserver/wcs?SERVICE=WCS&VERSION=2.0.1&REQUEST=GetCoverage&COVERAGEID=clarity:Tx75p_consecutive_max_EUR-11_ICHEC-EC-EARTH_rcp45_r12i1p1_SMHI-RCA4_v1_day_20410101-20701231_netcdf3&FORMAT=image/tiff

-Tx75p_consecutive_max_EUR-11_ICHEC-EC-EARTH_rcp45_r12i1p1_SMHI-RCA4_v1_day_20710101-21001231_netcdf3 WMS:
https://clarity.meteogrid.com/geoserver/clarity/wms?service=WMS&version=1.1.0&request=GetMap&layers=clarity%3ATx75p_consecutive_max_EUR-11_ICHEC-EC-EARTH_rcp45_r12i1p1_SMHI-RCA4_v1_day_20710101-21001231_netcdf3&bbox=2145500.0%2C982500.0%2C6606000.0%2C5706500.0&width=725&height=768&srs=EPSG%3A3035&format=image%2Fgif

**Comment by negroscuro** [comment]
-Tx75p_consecutive_max_EUR-11_ICHEC-EC-EARTH_rcp45_r12i1p1_SMHI-RCA4_v1_day_20710101-21001231_netcdf3 WCS:
https://clarity.meteogrid.com/geoserver/wcs?SERVICE=WCS&VERSION=2.0.1&REQUEST=GetCoverage&COVERAGEID=clarity:Tx75p_consecutive_max_EUR-11_ICHEC-EC-EARTH_rcp45_r12i1p1_SMHI-RCA4_v1_day_20710101-21001231_netcdf3&FORMAT=image/tiff

-Tx75p_consecutive_max_EUR-11_ICHEC-EC-EARTH_rcp85_r12i1p1_SMHI-RCA4_v1_day_20110101-20401231_netcdf3 WMS:
https://clarity.meteogrid.com/geoserver/clarity/wms?service=WMS&version=1.1.0&request=GetMap&layers=clarity%3ATx75p_consecutive_max_EUR-11_ICHEC-EC-EARTH_rcp85_r12i1p1_SMHI-RCA4_v1_day_20110101-20401231_netcdf3&bbox=2145500.0%2C982500.0%2C6606000.0%2C5706500.0&width=725&height=768&srs=EPSG%3A3035&format=image%2Fgif

-Tx75p_consecutive_max_EUR-11_ICHEC-EC-EARTH_rcp85_r12i1p1_SMHI-RCA4_v1_day_20110101-20401231_netcdf3 WCS:
https://clarity.meteogrid.com/geoserver/wcs?SERVICE=WCS&VERSION=2.0.1&REQUEST=GetCoverage&COVERAGEID=clarity:Tx75p_consecutive_max_EUR-11_ICHEC-EC-EARTH_rcp85_r12i1p1_SMHI-RCA4_v1_day_20110101-20401231_netcdf3&FORMAT=image/tiff

-Tx75p_consecutive_max_EUR-11_ICHEC-EC-EARTH_rcp85_r12i1p1_SMHI-RCA4_v1_day_20410101-20701231_netcdf3 WMS:	
https://clarity.meteogrid.com/geoserver/clarity/wms?service=WMS&version=1.1.0&request=GetMap&layers=clarity%3ATx75p_consecutive_max_EUR-11_ICHEC-EC-EARTH_rcp85_r12i1p1_SMHI-RCA4_v1_day_20410101-20701231_netcdf3&bbox=2145500.0%2C982500.0%2C6606000.0%2C5706500.0&width=725&height=768&srs=EPSG%3A3035&format=image%2Fgif

-Tx75p_consecutive_max_EUR-11_ICHEC-EC-EARTH_rcp85_r12i1p1_SMHI-RCA4_v1_day_20410101-20701231_netcdf3 WCS:
https://clarity.meteogrid.com/geoserver/wcs?SERVICE=WCS&VERSION=2.0.1&REQUEST=GetCoverage&COVERAGEID=clarity:Tx75p_consecutive_max_EUR-11_ICHEC-EC-EARTH_rcp85_r12i1p1_SMHI-RCA4_v1_day_20410101-20701231_netcdf3&FORMAT=image/tiff

-Tx75p_consecutive_max_EUR-11_ICHEC-EC-EARTH_rcp85_r12i1p1_SMHI-RCA4_v1_day_20710101-21001231_netcdf3 EMS:
https://clarity.meteogrid.com/geoserver/clarity/wms?service=WMS&version=1.1.0&request=GetMap&layers=clarity%3ATx75p_consecutive_max_EUR-11_ICHEC-EC-EARTH_rcp85_r12i1p1_SMHI-RCA4_v1_day_20710101-21001231_netcdf3&bbox=2145500.0%2C982500.0%2C6606000.0%2C5706500.0&width=725&height=768&srs=EPSG%3A3035&format=image%2Fgif

-Tx75p_consecutive_max_EUR-11_ICHEC-EC-EARTH_rcp85_r12i1p1_SMHI-RCA4_v1_day_20710101-21001231_netcdf3 WCS:
https://clarity.meteogrid.com/geoserver/wcs?SERVICE=WCS&VERSION=2.0.1&REQUEST=GetCoverage&COVERAGEID=clarity:Tx75p_consecutive_max_EUR-11_ICHEC-EC-EARTH_rcp85_r12i1p1_SMHI-RCA4_v1_day_20710101-21001231_netcdf3&FORMAT=image/tiff

**Comment by negroscuro** [comment]
New layers published in Atos Geoserver for Pluvial Floods.

-streams WMS:
http://services.clarity-h2020.eu:8080/geoserver/clarity/wms?service=WMS&version=1.1.0&request=GetMap&layers=clarity%3Astreams&bbox=-2819487.5%2C577137.5%2C7382812.5%2C5414462.5&width=768&height=364&srs=EPSG%3A3035&format=image%2Fgif

-streams WFS:
http://services.clarity-h2020.eu:8080/geoserver/clarity/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=clarity%3Astreams&maxFeatures=50&outputFormat=gml3

-basins WMS:
http://services.clarity-h2020.eu:8080/geoserver/clarity/wms?service=WMS&version=1.1.0&request=GetMap&layers=clarity%3Abasins&bbox=943600.0%2C941800.0%2C8140000.0%2C5447600.0&width=768&height=480&srs=EPSG%3A3035&format=image%2Fgif

-basins WFS:
http://services.clarity-h2020.eu:8080/geoserver/clarity/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=clarity%3Abasins&maxFeatures=50&outputFormat=gml3

**Comment by maesbri** [comment]
Data Package for DC1 - Naples is available in Drupal here: https://csis.myclimateservice.eu/node/221

Currently there are 19 resources. Additional ones being added during this week

**Comment by p-a-s-c-a-l** [comment]
Draft Data Package available. Continuing [here](https://github.com/clarity-h2020/data-package/issues).
