### ISSUE TITLE
Create Impact/Risk assessment model

### ISSUE THREAD

**Issue by maesbri** [clarity-h2020/csis#21]
This task must be done by PLINIVS

**Comment by p-a-s-c-a-l** [comment]
See [Impact modelling logic example](https://repository.atosresearch.eu/owncloud/index.php/apps/files/ajax/download.php?dir=%2FCLARITY%2FWP4%20Technology%20Support%2FT4.2%20Catalogue%20of%20Elements%20at%20Risk%20and%20Adaptation%20Options%2FModelling%20Workflow&files=impact%20modelling%20heat%20wave.pptx)

**Comment by alecapolupo** [comment]
Hi @luis-meteogrid,

the "Population estimates by Urban Atlas polygon"(https://land.copernicus.eu/local/urban-atlas/urban-atlas-2012) have been upoloaded again. So the exposure can be computed for all cities included in UA dataset. The datapakages includes the population on the FUA.

**Comment by p-a-s-c-a-l** [comment]
done
