### ISSUE TITLE
myclimateservice.eu DNS Entries

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/csis#23]
Register (sub) domain names for myclimateservice.eu and point DNS entries to IP of csis.clarity-h2020.eu

- myclimateservice.eu
- www.myclimateservice.eu
- csis.myclimateservice.eu.eu
- geoserver.myclimateservice.eu
- erdapp.myclimateservice.eu
- tiles.myclimateservice.eu
- api.myclimateservice.eu
- geonode.myclimateservice.eu

**Comment by Itsman-AT** [comment]
Dear Mario,
a whois request showed that ATOS is the owner of the myclimateservice.eu domain, so I think you (ATOS) need to configure this.

[cid:image001.jpg@01D4388B.D95E9110]

Best regards
Jan

Von: mnunez [mailto:notifications@github.com]
Gesendet: Montag, 20. August 2018 13:23
An: clarity-h2020/csis <csis@noreply.github.com>
Cc: Peters-Anders Jan <Jan.Peters-Anders@ait.ac.at>; Assign <assign@noreply.github.com>
Betreff: Re: [clarity-h2020/csis] myclimateservices.eu DNS Entries (#23)


Miguel Angel is out of office until 3 september. Angel Saez is our IT but he will only care about internal inquieries. So my question is, this DNS management is done by ATOS or by AIT? sorry not to be aware of this but if ATOS is supposed to take care of this, please let me know to open an internal inquiry to our IT colleagues.
Sorry for the inconvenience.

**Comment by negroscuro** [comment]
OK I will let our IT staff about this.
Thank you

**Comment by negroscuro** [comment]
Our IT colleague is currently on it, anyway I asume this is wrong:

csis.myclimateservices.eu.eu --> csis.myclimateservices.eu

**Comment by p-a-s-c-a-l** [comment]
> csis.myclimateservices.eu.eu --> csis.myclimateservices.eu

yes, csis.myclimateservices.eu



> One thing I forgot to ask, those subdomains, which IPs will correspond to?

81.189.135.173

**Comment by p-a-s-c-a-l** [comment]
@negroscuro Please wait with myclimateservices.eu & www.myclimateservices.eu until you got the confirmation from @fgeyer16 that the respective Drupal 8 instance is available on 81.189.135.173.

**Comment by negroscuro** [comment]
One thing as out IT noticed, the domain is myclimateservice.eu and not myclimateservices.eu, is this a problem?

**Comment by p-a-s-c-a-l** [comment]
No, in fact myclimateservice.eu is the correct domain.

**Comment by negroscuro** [comment]
Regarding myclimateservice.eu and www.myclimateservice.eu they are currently pointing to 198.49.23.144 so you mean after Florian Drupal8 instance is available we will have to move from there to a different IP?
Sorry just to be sure.

**Comment by p-a-s-c-a-l** [comment]
Yes, the subdomains listed above (except www.myclimateservice.eu) can be changed to 81.189.135.173 **now**, for myclimateservice.eu and www.myclimateservice.eu we have to wait until @fgeyer16 moved the Drupal instance from 198.49.23.144 to 81.189.135.173.

**Comment by negroscuro** [comment]
DNS is currently updated.

**Comment by p-a-s-c-a-l** [comment]
@negroscuro Can you please also add ckan.myclimateservice.eu?

**Comment by negroscuro** [comment]
Sure, I already requested it.

**Comment by negroscuro** [comment]
Done.

**Comment by negroscuro** [comment]
Sure.

**Comment by p-a-s-c-a-l** [comment]
done

**Comment by p-a-s-c-a-l** [comment]
Those are the the new DNS entries for the CSIS [DEV & PROD](https://github.com/clarity-h2020/csis/issues/113) system:

DNS | IP | Fallback DNS
-- | -- | --
csis.myclimateservices.eu | 62.218.164.247 | csis.ait.ac.at
csis-dev.myclimateservices.eu | 62.218.164.246 | csis-dev.ait.ac.at
ckan.myclimateservice.eu | 62.218.164.246 | csis-dev.ait.ac.at
geoserver.myclimateservices.eu | 62.218.164.246 | csis-dev.ait.ac.at

We'll update the entries, when the new systems have been deployed, provisionally scheduled for FR, 2020-02-07.

**Comment by p-a-s-c-a-l** [comment]
csis.myclimateservices.eu has to **temporarily**  point to 62.218.164.246 instead of  62.218.164.247 until the question of [migration](https://github.com/clarity-h2020/csis/issues/135) is resolved.

**Comment by negroscuro** [comment]
> Those are the the new DNS entries for the CSIS [DEV & PROD](https://github.com/clarity-h2020/csis/issues/113) system:
> 
> DNS	IP	Fallback DNS
> csis.myclimateservices.eu	62.218.164.247	csis.ait.ac.at
> csis-dev.myclimateservices.eu	62.218.164.246	csis-dev.ait.ac.at
> ckan.myclimateservice.eu	62.218.164.246	csis-dev.ait.ac.at
> geoserver.myclimateservices.eu	62.218.164.246	csis-dev.ait.ac.at
> We'll update the entries, when the new systems have been deployed, provisionally scheduled for FR, 2020-02-07.

Are those the new IP's I have to ask my IT to change domains to?

**Comment by p-a-s-c-a-l** [comment]
@negroscuro Yes, please wait for my confirmation. I'll inform the users about the expected downtime first.

**Comment by negroscuro** [comment]
It is done!

> @negroscuro can you add / change to following myclimateservices.eu DNS entries?
csis-dev.myclimateservices.eu     62.218.164.246 
ckan.myclimateservice.eu             62.218.164.246
>

Done!

**Comment by p-a-s-c-a-l** [comment]
done
