### ISSUE TITLE
Geonode does not allow for uploading layers

### ISSUE THREAD

**Issue by Itsman-AT** [clarity-h2020/csis#25]
When trying to upload a shapefile through the  GeoNode interface , I get this error:

`401,`
`HTTP Status 401 – Unauthorized`
`Type Status Report`
`Message No AuthenticationProvider found for org.springframework.security.authentication.UsernamePasswordAuthenticationToken`

`Description The request has not been applied because it lacks valid authentication credentials for the target resource.`
`Apache Tomcat/9.0.10`

Might be solveable like this: https://github.com/GeoNode/geonode/issues/3175 
Could you have a look? Thanks!

**Comment by p-a-s-c-a-l** [comment]
To be addressed in https://github.com/clarity-h2020/docker-geonode/issues/7
