### ISSUE TITLE
Create a CSIS Account

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/csis#26]
CSIS Developers need to create an account at https://csis.myclimateservice.eu/user/register
Depends on 
- [x] https://github.com/clarity-h2020/docker-drupal/issues/10

**Comment by stefanon** [comment]
Hi, just sent a message via the web form from

https://csis.myclimateservice.eu/

for asking for an account (the page has only login for now) to follow
development, and I've received the contracdictory messages in the attached
pic.

**Comment by p-a-s-c-a-l** [comment]
@stefanon Yes, account registration is currently not possible until clarity-h2020/docker-drupal#10 is fixed,

**Comment by p-a-s-c-a-l** [comment]
@stefanon
Please try again.  We've implemented a temporary workaround for clarity-h2020/docker-drupal#10

**Comment by p-a-s-c-a-l** [comment]
Done.
