### ISSUE TITLE
Implement GUI functions for viewing and retrieval

### ISSUE THREAD

**Issue by Itsman-AT** [clarity-h2020/csis#34]
**GUI / Tagging functions:**
•	Mark areas /cities with an extreme event marker (heavy precipitation, extreme heat) 
•	provide a link where information on the local event is stored:
+ year(s) of occurrence, 
+ observed hazards, approximate costs to repair
+ photos depicting the impact
+ set adaption measures 
+ photos depicting the adaptation measures
Links can be stored in a database with variables coordinates, city(region name, event keyword, link to provide documentation

**GUI / Viewing functions:**
View areas with threshold x above a number of extreme event days: 
•	average annual number of summer days 
•	average annual number of tropical nights 
•	average annual number of heat episodes > 3 day, >5 days, > 10 days 
•	average annual number of frost days 
•	average annual number of frost episodes > 3 day, >5 days, > 10 days 
•	average annual number of storm days 

**GUI / Retrieval functions**
(1)	Pre-selection of events by event type above a threshold (frequency, magnitude
(2)	Spatial selection of the pre-selected events by drawing a polygon or a rectangle
(3)	Printing a map of the selection (pdf)
(4)	Point on the event markers to search for links were hazards and adaptation measures are documented  - or
(5)	list the links provided in the selection for reading or printing (pdf)

See also: https://github.com/clarity-h2020/map-component

**Comment by patrickkaleta** [comment]
Since this is heavily connected to the map compoment, I believe that @therter is the right person for this. I'm going to add him to this issue.

**Comment by p-a-s-c-a-l** [comment]
IMHO this is beyond the scope of the general map component and should be implemented in a separate "Hazard Twins" Map.

**Comment by Itsman-AT** [comment]
@therter : How far is the code for the general map component? I think it will be most efficient, if we join forces and I build the hazard twin map from/on top of your existing map frame, so we will be able to integrate the two in one map frame in the platform. @p-a-s-c-a-l : It you do not see this as a good way to do it, please say so.

**Comment by p-a-s-c-a-l** [comment]
@Itsman-AT do you agree? Then we should fork the map-component as *scenario-transferability-component* so that we can report it as Building Block in [D4.3 Technology Support Report v1](https://github.com/clarity-h2020/csis/milestone/6) and the [architecture specification](https://github.com/clarity-h2020/csis-architecture).

**Comment by Itsman-AT** [comment]
@p-a-s-c-a-l : Yes, I agree. In this way we can use scaling effects for the map components and maybe merge them in the future into one component/module, so I am, of course, fine with it. Thanks for all your pre-work in T4.4!

**Comment by Itsman-AT** [comment]
Decision: We will be using Geofieldmap (https://www.drupal.org/project/geofield_map)  until the review and first fill it with hazarda and vulnarability data to show. 
In parallel we will be extending the Leaflet mapComponent of Clarity as discussed above.
