### ISSUE TITLE
Define workflow for generating maps of extreme event patterns for prior and future decades cities

### ISSUE THREAD

**Issue by Itsman-AT** [clarity-h2020/csis#36]
On Climate twins adaptation
The initial climate twins paper as published in 2011 describes the climate twins application “being  designed to communicate climate changes in an intuitive and understandable way by showing regions which have now similar climate conditions as a given Point of Interest (POI) in the future to learn from adaptation options”.

Making use of the climate twins concept for CLARITY focusing on climate services objectives dealing with climate risk (=extreme events) / vulnerability and adaptation requires to adapt the research approach not finding similarities in average climate signals with respect to daily temperature maximum distribution and daily precipitation volume patterns for selected decades towards extreme event occurrence. Thus the appropriate objective must be finding similarities in extreme events to learn from cities which have experienced similar events earlier and frequently to cope better with climate risk, to better adapt to climate change and to  better mitigate vulnerability.

The CLARITY concept shall focus on extracting extreme event occurrence patters (n of heat waves of certain length, n of summer days or tropical nights during prior decades and years) and extracting the same indicators for extreme events screening future climate data at the European scale, from appropriate climate simulations (in our case from Euro-Cordex ensembles).

By identifying cities or regions with a certain number of prior extreme events of critical magnitude and extracting the expectations on extreme events for the own city allows to review the activities of those critically exposed cities which show a similar environmental and spatial framework (characteristics of terrain and land use) in earlier years or decades. 

By reviewing the damage repair and adaptation activities in cities with similar earlier experience, each target city can learn from activities in those earlier exposed cities to get better prepared and to cope better with future climate hazards.

Besides generating maps of extreme event patterns for prior and future decades cities can mark their location and provide a link where their adaption measures have successfully responded to such extreme events. In this way those cities can actively help other cities, facing future climate hazards,  in learning from their earlier experience.

**Comment by p-a-s-c-a-l** [comment]
duplicate of https://github.com/clarity-h2020/csis/issues/37
