### ISSUE TITLE
Check and add background data

### ISSUE THREAD

**Issue by Itsman-AT** [clarity-h2020/csis#38]
**Background data**
•	open street map content (source: OSM)
•	satellite image (source: Google)
•	digital elevation map  / terrain shading (source: EEA)
•	NUTS 1 and NUTS3 region borders (source: Eurogeographics)
•	Population distribution map (source: EU pop grid, Eurostat)
•	selected event indicator(s) as choropleth maps
(source: extracted from EUROCORDEX model runs.

### Subtasks
- [ ] [1st Data Package: Background Layers](https://github.com/clarity-h2020/data-package/issues/4)

**Comment by p-a-s-c-a-l** [comment]
Apart from the event indicator(s) maps (belongs to HC Maps task), those layers should be covered by https://github.com/clarity-h2020/data-package/issues/4

In particular, Data Sources for Background Layers and how to make them available as WMS/TMS should be provided in https://github.com/clarity-h2020/data-package/issues/5. There may also be overlaps with the layers generated in https://github.com/clarity-h2020/csis/issues/33 (to be checked against the [Models Excel Sheet](https://repository.atosresearch.eu/owncloud/index.php/apps/files/ajax/download.php?dir=%2FCLARITY%2FWP4%20Technology%20Support%2FT4.2%20Catalogue%20of%20Elements%20at%20Risk%20and%20Adaptation%20Options%2FModelling%20Workflow&files=Models.xlsx)).
