### ISSUE TITLE
Install ReactJS Docker Image

### ISSUE THREAD

**Issue by Itsman-AT** [clarity-h2020/csis#40]

**Comment by p-a-s-c-a-l** [comment]
What is a „ReactJS Docker Image“ ?
For react Integration into drupal see docker-drupal repository and related issues.

**Comment by Itsman-AT** [comment]
This is just a remark that this has been installed as a test installation already. I also marked it as being done. 
> 
> What is a „ReactJS Docker Image“ ? For react Integration into drupal see docker-drupal repository and related issues.
> […](#)
> Am 14.11.2018 um 11:20 schrieb Itsman-AT ***@***.***>: — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by Itsman-AT** [comment]
@p-a-s-c-a-l : Is there any action needed here still?

**Comment by p-a-s-c-a-l** [comment]
> What is a „ReactJS Docker Image“ ?
