### ISSUE TITLE
Need first data package for the demo

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/csis#41]
Need a data package with 

- at least one hazard layer (e.g. heath layer)
- at least one exposure layer (e.g. population)
- at least one vulnerability combination (e.g. heath/population)

The meta-information has to be published as a data package.
The data has to be published on relevant services (grid maps for hazard & population)

**Comment by maesbri** [comment]
This issue is kind of duplicated with #20

**Comment by maesbri** [comment]
This issue can only be completed once #13, #14, #15, #16, #17, #18, #19 are done

**Comment by p-a-s-c-a-l** [comment]
Detailed sub-tasks are defined in the data-package repository: **[Milestone: 1st Data Package](https://github.com/clarity-h2020/data-package/milestone/1)**

Later, these tasks may serve as blueprint or "how-to" for creating Data Packages for the Demonstration Cases and as input for the [CLARITY Guideline](https://github.com/clarity-h2020/csis/milestone/11).

**Comment by p-a-s-c-a-l** [comment]
Duplicate of https://github.com/clarity-h2020/csis/issues/20
