### ISSUE TITLE
Create private drupal configuration repository

### ISSUE THREAD

**Issue by maesbri** [clarity-h2020/csis#43]
We need a private git repository for storing and sharing among partners the drupal configuration files.

**Comment by maesbri** [comment]
I have just requested in our private gitlab repository in ATOS a new project named "clarity-csis-drupal".

The following persons will have access (let me know if someone else has to be included, indicate name and email address):

@maesbri 
@negroscuro 
@DanielRodera 
@p-a-s-c-a-l 
@patrickkaleta 
@fgeyer16

**Comment by maesbri** [comment]
gitlab repository has been created. Please, confirm that you can access it with the credentials that were sent to your emails.

**Comment by p-a-s-c-a-l** [comment]
@maesbri Yes, I can access the repo. Can you please add me to the group of project Maintainers. I need manage the project settings in order to unprotect the dev branch.

**Comment by p-a-s-c-a-l** [comment]
done
