### ISSUE TITLE
DataPackage: Add "references" property in resource

### ISSUE THREAD

**Issue by maesbri** [clarity-h2020/csis#58]
@fgeyer16 , @patrickkaleta I need to create a "references" property (in the dp_resource object) which is an array of unlimited number of subarrays (which have a lenght = 3), any idea on how can I model this in Drupal?

For the moment it would be fine if we cannot limit the length of the sub-arrays. The content of the subarrays is just text.

See below an example with 2 sub-arrays:
"references": [
        ["@mapview:ogc:wms", "#/path", "https://clarity.meteogrid.com/geoserver/Local_Effects/wms?service=WMS&version=1.1.0&request=GetMap&layers=Local_Effects:LE_Tmrt_FrequentEvent_1971-2000_observations_Naples&bbox=4647500,1947000,4720500,2008000&width=725&height=768&srs=EPSG:3035&format=image/png"],
        ["@resource:hazard-event:heat-wave-duration:$temperature=28:$duration=6", "#/resources/[name='hazard_event-HW.6d_28C']"]
      ]

**Comment by therter** [comment]
@maesbri Have you already changed the url property for the map view? Because now I retrieve an array instead of a string when I query the dp_resource objects.

**Comment by maesbri** [comment]
Hmm, it has been changed but I think it was @patrickkaleta . However, this doesn't correspond to this issue and in any case, if I recall correctly, my indication was that the "path" property (within the resource object) is the one to be converted into an array (it is now).

Anyhow, just to let you know that in parallel I am implementing the "references" properties, which will replace among others the "mapview" one. I'll let you know when it is ready so you can test it (and later on I will remove the "obsolete" properties, but of course, having copied their contents to the new properties)

**Comment by maesbri** [comment]
I managed to implement this property

**Comment by p-a-s-c-a-l** [comment]
How is the current DP Implementation in Drupal affected by the references property?
Which properties will be replaced by references? path? mapview? what else?

**Comment by p-a-s-c-a-l** [comment]
How is the current DP Implementation in Drupal affected by the references property?
Which properties will be replaced by references? path? mapview? what else?

**Comment by maesbri** [comment]
The "references" properties makes obsolete the following properties:
- mapview
- hazardEvent

the "path" property stays as it is (it is part of the original Frictionless Data Package specification).

With the references now we can described things like:

"references": [
        ["@mapview:ogc:wms", "damage-class:population:d1", "https://service.emikat.at/geoserver/clarity/wms?service=WMS&version=1.1.0&request=GetMap&layers=clarity:view.2813&styles=DamageLevel1Q&bbox=4650500.0,1942000.0,4713000.0,1995500.0&width=768&height=657&srs=EPSG:3035&format=image/gif&cql_filter=HAZARD_EVENT='HW.6d_34C'"],
        ["@mapview:ogc:wms", "damage-class:population:d2", "https://service.emikat.at/geoserver/clarity/wms?service=WMS&version=1.1.0&request=GetMap&layers=clarity:view.2813&styles=DamageLevel2Q&bbox=4650500.0,1942000.0,4713000.0,1995500.0&width=768&height=657&srs=EPSG:3035&format=image/gif&cql_filter=HAZARD_EVENT='HW.6d_34C'"],
        ["@mapview:ogc:wms", "damage-class:population:d3", "https://service.emikat.at/geoserver/clarity/wms?service=WMS&version=1.1.0&request=GetMap&layers=clarity:view.2813&styles=DamageLevel3Q&bbox=4650500.0,1942000.0,4713000.0,1995500.0&width=768&height=657&srs=EPSG:3035&format=image/gif&cql_filter=HAZARD_EVENT='HW.6d_34C'"],
        ["@mapview:ogc:wms", "damage-class:population:d4", "https://service.emikat.at/geoserver/clarity/wms?service=WMS&version=1.1.0&request=GetMap&layers=clarity:view.2813&styles=DamageLevel4Q&bbox=4650500.0,1942000.0,4713000.0,1995500.0&width=768&height=657&srs=EPSG:3035&format=image/gif&cql_filter=HAZARD_EVENT='HW.6d_34C'"],
        ["@mapview:ogc:wms", "damage-class:population:d5", "https://service.emikat.at/geoserver/clarity/wms?service=WMS&version=1.1.0&request=GetMap&layers=clarity:view.2813&styles=DamageLevel5Q&bbox=4650500.0,1942000.0,4713000.0,1995500.0&width=768&height=657&srs=EPSG:3035&format=image/gif&cql_filter=HAZARD_EVENT='HW.6d_34C'"]
      ]

or

"references": [
        ["@mapview:ogc:wms", "#/path", "https://clarity.meteogrid.com/geoserver/Exposure/wms?service=WMS&version=1.1.0&request=GetMap&layers=Exposure:Population_mayor65_naples&bbox=4647500,1947000,4716000,2003000&width=725&height=768&srs=EPSG:3035&format=image/png"]
      ]
In this case, we are indicating that the data available in "path" has its mapview representation in the attached link (this would be also equivalent to:
 ["@mapview:ogc:wms", "vulnerability-class:population:age-group>65", "https://clarity.meteogrid.com/geoserver/Exposure/wms?service=WMS&version=1.1.0&request=GetMap&layers=Exposure:Population_mayor65_naples&bbox=4647500,1947000,4716000,2003000&width=725&height=768&srs=EPSG:3035&format=image/png"]
      ]

In addition, if we had a resource with multiple path values (imagine for instance a resource considered as a whole, but it is split in multiple files) we could have for instance something like this:
"references": [["@mapview:ogc:wms", "#/path[0]", "http://geoserver/wms....."],
                ["@mapview:ogc:wms", "#/path[1]", "http://geoserver/wms....."],
                ["@mapview:ogc:wms", "#/path[2]", "http://geoserver/wms....."]
]

With the references properties we can also make references to other resources within the Data Package (e.g., local effect resource pointing to the hazard-event to which is linked):
"references": [
["@resource:hazard-event:heat-wave-duration:$temperature=28:$duration=6", "#/resources/[name='hazard_event-HW.6d_28C']"]]

Finally, we can also refer to external metadata repository if we want to know more about it:
"references": [
["@metadata:ogc:cws", "#/path", "http://some-ip/catalog/cws..."]
]

**Comment by maesbri** [comment]
btw, I use "@" to indicate it is a reserved word (i.e., "@tag", "@resource", "@metadata", "@mapview"). If it is confusing then we might consider removing it

**Comment by maesbri** [comment]
With respect to the "tags" property, it replaces the following individual properties:
- service_type
- resource_type
- workflow_step
- hazards
- index
- emissions_scenarios
- elements_at_risk
- vulnerability_classes
- damage_classes
