### ISSUE TITLE
Json DataPackage Import: Install necessary Drupal modules

### ISSUE THREAD

**Issue by maesbri** [clarity-h2020/csis#59]
@patrickkaleta , the following Drupal 8 modules need to be installed in order to use the ingest JSON data packages into our drupal data model:

Migrate (in core)
Migrate Plus 8.x-2.x
Migrate Tools 8.x-2.x
Migrate Source JSON 8.x-1.x (currently, requires this patch for Drupal 8.1.x+ compatibility)

(source: https://www.jeffgeerling.com/blog/2016/migrate-custom-json-feed-drupal-8-migrate-source-json)

**Comment by p-a-s-c-a-l** [comment]
Is this still required? Is it still planned to support import of externally created JSON (by which tool, btw? [qGIS plugin](https://github.com/clarity-h2020/qgis3-data-package-builder-plugin)?) now that we have [simplified Data Package Forms](https://github.com/clarity-h2020/docker-drupal/issues/78)?
