### ISSUE TITLE
Integration of EEA's Urban Adaptation Map Viewer

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/csis#60]
We should integrate maps and data from EEA's [Urban Adaptation Map Viewer](https://eea.maps.arcgis.com/apps/MapSeries/index.html?appid=ec9a942228894562bd53310e3c3bc211) into the CSIS.

We could show some of their [Urban-Adaptation-datasets](https://climate-adapt.eea.europa.eu/knowledge/tools/urban-adaptation/Urban-Adaptation-datasets) on our maps and embed the [city profiles](https://tableau.discomap.eea.europa.eu/t/Aironline/views/2019_Urban_vulnerability_links/mainpage?iframeSizedToWindow=false&%3Aembed=y&%3AshowAppBanner=true&%3Adisplay_count=yes&%3AshowVizHome=yes&%3Atoolbar=yes&City_param=Napoli) as external application via iFrame. 

I don't expect that this will save us some work regarding local effects data processing and impact calculation, but it will enhance the CSIS with a lot of useful information, especially the city profiles:

![grafik](https://user-images.githubusercontent.com/1788226/60009204-c4497800-9675-11e9-95b2-9ca823411cbc.png)

WDYT?

But we need a formal  / service level agreement to use their data and APIs (WMS, WFS, etc.). Denis?

**Comment by p-a-s-c-a-l** [comment]
According to their copyright notice we should be allowed to use the data:

*Information, documents and material available on this website and for which the EEA holds the rights of use are public and may be re-used without prior permission, free of charge, for commercial or non-commercial purposes, provided that the EEA is always acknowledged as the original source of the material and that the original meaning or message of the content is not distorted.* 
https://www.eea.europa.eu/legal/copyright

**Comment by maesbri** [comment]
I had a look at the links. These are mainly WMS services (so, no access to the underlying data).

In the case of the Urban-Adaptation-datasets, for instance, "Projected trends in drought frequency (RCP 8.5; 2071-2100; months/30-year period)" (http://climate.discomap.eea.europa.eu/arcgis/rest/services/UAMV/ProjectedDroughtFrequency2071_2100/MapServer) you end up here: https://www.eea.europa.eu/data-and-maps/indicators/river-flow-drought-2/assessment but the dowloadable data are only some high resolution european maps (in tif and gif format, not geographically referenced) so probably not very useful for integrating in our map component

**Comment by DenoBeno** [comment]
They must have somethign else in addition to WMS. E.g., where is this data coming from?

![grafik](https://user-images.githubusercontent.com/2961790/61808207-4080d800-ae3b-11e9-9515-99e79ca43fa2.png)

or this:

![grafik](https://user-images.githubusercontent.com/2961790/61808319-758d2a80-ae3b-11e9-995e-17caaab764df.png)

Or this:

![grafik](https://user-images.githubusercontent.com/2961790/61808413-9c4b6100-ae3b-11e9-89cb-995e61bdbe4c.png)

This data could indeed be useful in screening (IMO), e.g. one could use it to indicate if some hazard (projected number of heatwaves, percentage of UMZ potentially exposed to river flooding) or if some exposure (percentage of lone pensioner households, Percentage of people 75 years old or older)

**Comment by DenoBeno** [comment]
Ah, look what i found: 

https://climate-adapt.eea.europa.eu/knowledge/tools/urban-adaptation/Urban-Adaptation-datasets

By following the link to "people 75 y or older", I get this page

http://climate.discomap.eea.europa.eu/arcgis/rest/services/UAMV/Percentage_People_75_Or_Older/MapServer

**Service Description:** Data on number of people 75 years old or older was obtained from Eurostat (Population on 1 January by age groups and sex - cities and greater cities (urb_cpop1; http://appsso.eurostat.ec.europa.eu/nui/show.do?dataset=urb_cpop1&lang=en)) and joined to the Urban Audit 2011-2014 cities' centroids (https://ec.europa.eu/eurostat/web/gisco/geodata/reference-data/administrative-units-statistical-units/urban-audit#ua11-14) . 

http://appsso.eurostat.ec.europa.eu/nui/show.do?dataset=urb_cpop1&lang=en is a table

https://ec.europa.eu/eurostat/web/gisco/geodata/reference-data/administrative-units-statistical-units/urban-audit#ua11-14 has several data field for download:

![grafik](https://user-images.githubusercontent.com/2961790/61809519-bede7980-ae3d-11e9-95d2-6f5802c4eb75.png)

**Comment by p-a-s-c-a-l** [comment]
@alecapolupo @humerh @RobAndGo Is [this](https://github.com/clarity-h2020/csis/issues/60#issuecomment-514692854) something that might be useful as data source for the  screening model?

**Comment by RobAndGo** [comment]
Yes, this data source could be useful. As I understand it, for the explicit calculations of risk and impact using the vulnerability curves proposed by PLINIVS, the population are no longer split into the three age groups (is this correct @alecapolupo?). However, being able to overlay different age groups on the maps would provide the user a qualitative assessment where they could see where e.g. older people live and compare it to where the hazards are highest.

**Comment by alecapolupo** [comment]
I'm agree with Robert. Even if the population is not longer split in three groups for computing risk and impact, overlay different age groups on the maps could give additional qualitative information to the users.

**Comment by DenoBeno** [comment]
I would like to see some of this in CSIS, but I suppose that it's a low priority at the moment. 

Good news: I'm about to finalize the "templating for studies" - this will allow us to define new study types that can be used to show different applicaitons (e.g. this one) on some steps. Also to test with new applications without breaking the standard study types.

**Comment by p-a-s-c-a-l** [comment]
I've integrated EEA's Urban Adaptation Viewer into the ["Implementation of Adaptation Plans"](https://csis.myclimateservice.eu/node/941) Step Template. It should be available e.g. [here](https://csis.myclimateservice.eu/study/35/step/1525/view/introduction) as soon as the ["External" Tab](https://github.com/clarity-h2020/csis/issues/81#issuecomment-535495024) is implemented.

**Comment by patrickkaleta** [comment]
**External** tab is now implemented but taking screenshots is not working. The console log currently shows (IMO) these 2 main reasons/errors:
- **"no global drupalSettings object found...."** right after page is loaded 
This I can't quite understand, since I can access it with: `console.log(drupalSettings.csisHelpers.studyInfo)`  ...maybe this is called before the object is fully loaded?
- **"Cannot read property 'getElementById' of null"** right after clicking the "Include in Report" button.
This happens because `elementToPrint.contentDocument` ([csis_include_in_report.js -> line 128](https://github.com/clarity-h2020/csis-helpers-module/blob/dev/js/csis_include_in_report.js#L128)) returns null.

This part of the code was (AFAIK) added by @therter, so maybe you know how to get this fixed?

**Comment by therter** [comment]
> This part of the code was (AFAIK) added by @therter, so maybe you know how to get this fixed?

I will have a look on this

**Comment by DenoBeno** [comment]
> 
> 
> I've integrated EEA's Urban Adaptation Viewer into the ["Implementation of Adaptation Plans"](https://csis.myclimateservice.eu/node/941) Step Template. It should be available e.g. [here](https://csis.myclimateservice.eu/study/35/step/1525/view/introduction) as soon as the ["External" Tab](https://github.com/clarity-h2020/csis/issues/81#issuecomment-535495024) is implemented.

I took a look at the EEA fact sheet and decided that this needs its own step. The result is shown below:

![grafik](https://user-images.githubusercontent.com/2961790/66132416-522deb00-e5f5-11e9-8433-73292c3a24e5.png)

EEA factsheets is indeed a new entry in the EU-GL taxonomy now.

![grafik](https://user-images.githubusercontent.com/2961790/66132505-77225e00-e5f5-11e9-99bf-237fb09399ce.png)

I'll change the template too. We don't have anything to show in "implementation", so we don't need an implementation template at the moment.

**Comment by p-a-s-c-a-l** [comment]
> I will have a look on this

what's the status @therter ?

**Comment by p-a-s-c-a-l** [comment]
> I took a look at the EEA fact sheet and decided that this needs its own step.

@DenoBeno But it's not an "official" EU-GL step, so it's conceptually inconsistent with our whole approach. The EU-GL  model has to be reflected in the UI design that guides the users. Furthermore, now you have empty / useless "Introduction", "Data" and "Summary" sub steps. That's rather confusing for the users. And what, if we want to add more external apps? Create a new top-level step for each of them? I don't think that's the way to go. I would revert this and put it into an EU-GL step where it fits best. That was the initial idea of  external apps. Enhance the steps but not artificially invent new ones. Maybe put it in vulnerability or directly under Study??

**Comment by Andrea4ad** [comment]
I agree on @p-a-s-c-a-l in that respect - external apps should be contribute to an EU-GL step and not flaw method, they are additional instruments for decisioning. 
Anywhere, I consider it were possible to create sort of list for useful apps with a short description and recommendation for use? Maybe their benefit lies beyond the EU-GL workflow, e.g. some maintenance plans for green infrastructure.

**Comment by p-a-s-c-a-l** [comment]
> Anywhere, I consider it were possible to create sort of list for useful apps with a short description and recommendation for use?

Yes, we could create them as showcase or solution offer.

**Comment by Andrea4ad** [comment]
I don´t think they are a solution offer, more "operational resources"; need to think about, maybe this funcionality is better embedded in the marketplace.

**Comment by Andrea4ad** [comment]
@fgeyer16, any opinions on that?

**Comment by DenoBeno** [comment]
In my opinion, EU GL is a good abstract model but we should not try to fit
things in it that obviously don't fit. And this application has parts that
fit into several categories.

In any case, this is a minor question that can be easily resolved by
modifying the template. The most difficult part is to decide where to put
it, technical work needed is trivial.

On a related note: most, but not all of the sub-steps are now configurable
by templates and can be omitted or replaced by a different application. The
only exceptions are introduction, summary and data tab.

- summary should not be changed IMO.
- for data step, it would IMO be better if we could choose different
applications in the template. E.g , the "table" in adaptation options step
could be moved to data
- for the introduction step, maybe we should consider putting (part of) the
text in the text field within the gl step node. This would have two
advantages:
1. we could have different text for each study if needed.
2. we could even let the users edit this text, thus changing the section
introduction in the report.

WEYT?

**Comment by patrickkaleta** [comment]
> > I took a look at the EEA fact sheet and decided that this needs its own step.
> 
> @DenoBeno But it's not an "official" EU-GL step ... The EU-GL model has to be reflected in the UI design that guides the users...

I would argue that the EU-GL model is still clearly reflected and we're only further enhancing it. So to me, doing something like that seems ok in general, if we have good reasons for that. But you're right, we have to be careful here. If we allow to omit steps or interchange steps and now also to add completely arbitrary steps, it will become very difficult for us to create useful user guides and comparing studies won't be an option, since they will have less and less in common.


> In any case, this is a minor question that can be easily resolved by
> modifying the template. The most difficult part is to decide where to put
> it, technical work needed is trivial.

@DenoBeno: I agree. From a technical standpoint this is not an issue. So maybe after we get some user feedback, we can have a bigger discussion about how much deviation from the original EU-GL model should be made possible in our CSIS.

Also, I agree with your comments about the **summary**, **data** and **introduction** sub-steps, but ATM I would give this a **low-medium priority**.

**Comment by p-a-s-c-a-l** [comment]
EEA's Urban Adaptation Map Viewer integrated. [Report Generation](https://github.com/clarity-h2020/csis-helpers-module/issues/9#issuecomment-547783778) to be fixed.

**Comment by Andrea4ad** [comment]
> - summary should not be changed IMO.
> - for data step, it would IMO be better if we could choose different
> applications in the template. E.g , the "table" in adaptation options step
> could be moved to data
> - for the introduction step, maybe we should consider putting (part of) the
> text in the text field within the gl step node. This would have two
> advantages:
> 1. we could have different text for each study if needed.
> 2. we could even let the users edit this text, thus changing the section
> introduction in the report.
> 

@DenoBeno: I think this is a good idea. On the one hand studies get individual and relevant for the project/case they deal with, on the other hand studies remain comparable.

@patrickkaleta: you have a point with comparability of studies also in terms of recommendation services.

Btw. IMHO these are items for the development roadmap. The whole application needs to become stable and handed over to "real" endusers, then we can propose new features ...

**Comment by p-a-s-c-a-l** [comment]
> I've integrated EEA's Urban Adaptation Viewer into the ["Implementation of Adaptation Plans"](https://csis.myclimateservice.eu/node/941) Step Template. It should be available e.g. [here](https://csis.myclimateservice.eu/study/35/step/1525/view/introduction) as soon as the ["External" Tab](https://github.com/clarity-h2020/csis/issues/81#issuecomment-535495024) is implemented.

@patrickkaleta Could you please restore this working behaviour: External Tab with EEA iFrame in IAO step, remove separate step "EEA City Factsheet" that has nothing to do with EU-GL. 

![grafik](https://user-images.githubusercontent.com/1788226/74840868-066faa00-5328-11ea-85e5-d8b6ae3c7819.png)


The "EEA City Factsheet" tab is broken: https://csis.myclimateservice.eu/study/35/step/1525/view/external Moreover, the "introduction", "Data" and "Summary" tabs don't provide any added value. 

I would like to revert to something lean and simple that actually did work (external tab in IAO) instead of putting even more effort into a broken feature that IMO just introduced incoherence and unnecessary  complexity.

**Comment by patrickkaleta** [comment]
> @patrickkaleta Could you please restore this working behaviour: External Tab with EEA iFrame in IAO step, remove separate step "EEA City Factsheet" that has nothing to do with EU-GL.

I will do that next week.

**Comment by patrickkaleta** [comment]
I removed the EEA step from all Study type templates  and instead placed the EEA iFrame in the "External tab" of the IAO step.

Since already existing Studies are not affected by updates of the corresponding Study templates, I went over all published Studies and removed the EEA step manually. 
**However,** I have not yet added the [EEA iFrame](https://csis.myclimateservice.eu/node/1488) into the "External tab" of the IAO step, since that iFrame is currently still not working (showing same "Page not found" error as in screenshot above). Once the iFrame is working again, I will add the "External tab" to our existing Studies as well. 
(To check the error, I already added the iFrame into [Study 35](https://csis.myclimateservice.eu/study/35/step/1526/view/external)).

@p-a-s-c-a-l 
according to [this comment](https://github.com/clarity-h2020/csis/issues/60#issuecomment-547784005), the EEA integration was completed on October, 30th. That's also the day the iFrame was last edited in the CSIS, so I'm guessing the reason for this error might be due to some changes on EEA's side?

**Comment by p-a-s-c-a-l** [comment]
> @p-a-s-c-a-l
> according to [this comment](https://github.com/clarity-h2020/csis/issues/60#issuecomment-547784005), the EEA integration was completed on October, 30th. That's also the day the iFrame was last edited in the CSIS, so I'm guessing the reason for this error might be due to some changes on EEA's side?

As far as I can see, the URL at EEA side did not change. Probably a problem with [our proxy configuration](https://github.com/clarity-h2020/docker-compose-letsencrypt-nginx-proxy-companion/issues/5#issuecomment-590327537). @therter will have a look at this.

**Comment by therter** [comment]
The [iFrame](https://csis.myclimateservice.eu/study/35/step/1526/view/external) should now work

**Comment by p-a-s-c-a-l** [comment]
> The [iFrame](https://csis.myclimateservice.eu/study/35/step/1526/view/external) should now work

What caused the problem?
