### ISSUE TITLE
Create (and update) wiki page listing all services endpoints we are using

### ISSUE THREAD

**Issue by maesbri** [clarity-h2020/csis#61]
We need some place where we can easily list and find all service endpoints instead of having to review tons of emails/issues for finding the service url we need everytime.

**Comment by maesbri** [comment]
Wiki entry is available here: https://github.com/clarity-h2020/csis/wiki/Services-endpoints-(used-by-CSIS)

Please, complete it.

**Comment by DenoBeno** [comment]
I have added links to these two views:

* https://csis.myclimateservice.eu/maintenance/resources/paths
* https://csis.myclimateservice.eu/maintenance/resources/paths2

They list all the paths used in our data packages; this can help in looking for service endpoints.

**Comment by p-a-s-c-a-l** [comment]
Please update the wiki page when the task [Export Geoserver layers from MTG to ATOS](https://github.com/clarity-h2020/ckan/issues/23) is completed.

**Comment by p-a-s-c-a-l** [comment]
@DanielRodera 

> Please update the wiki page when the task [Export Geoserver layers from MTG to ATOS](https://github.com/clarity-h2020/ckan/issues/23) is completed.

**Comment by DanielRodera** [comment]
Done
