### ISSUE TITLE
Please install views bulk edit module

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/csis#68]
Could someoen please install this?

https://www.drupal.org/project/views_bulk_edit

We will need this to fix the spatial extent, contributors and licenses for the existing dp_resources.

**Comment by p-a-s-c-a-l** [comment]
Ok, done. We shouldn't forget to locally test and apply this [update procedure](https://github.com/clarity-h2020/docker-drupal/issues/53#issuecomment-518341135).

**Comment by patrickkaleta** [comment]
> Ok, done. We shouldn't forget to locally test and apply this [update procedure](https://github.com/clarity-h2020/docker-drupal/issues/53#issuecomment-518341135).

I' just working on this right now. I'm applying the mentioned procedure (with some slight changes, which I'll mention directly in that issue) and after that I'll try to test the whole system as extensively as possible. I'm expecting to be done with this testing around tomorrow noon.

**Comment by patrickkaleta** [comment]
@DenoBeno the Views Bulk edit module is installed and enabled in the CSIS.
