### ISSUE TITLE
Simple way to associate icons with content on maps

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/csis#74]
It is possible (and easy) to dynamically associate the icons with different data types on D8 maps. Here is how:

1) First, define a taxonomy that will be used to categorise the content. E.g. "hazards" taxonomy.
2) Then add a field to store the icon in this taxonomy. E.g. "field_icon" in this example.

![image](https://user-images.githubusercontent.com/2961790/62858635-182e2000-bcfb-11e9-91bf-4829889bcc11.png)

Recommended: put them all in one directory and enable the "alt" field so that we can wite where the icons come from.

![image](https://user-images.githubusercontent.com/2961790/62858706-4b70af00-bcfb-11e9-99cb-de3226491bb4.png)

3) Then define a content type that will be tagged by this taxonomy. E.g. the "showcase". 
4) finally define a view that will show this data on a map. Depending on the geo-field type, this view will have "Geolocation Google Maps API - CommonMap" or "Geofield Google Map" format. The trick works with both.
5) Within this view, add a hidden field that provides a link to the icon image. Unless the icons are already in correct size (probably not), also choose a special image style that will resize the icons to the correct size. Surprisingly this works - url will be to resize icon, not to original one. (I hope this is cached)

![image](https://user-images.githubusercontent.com/2961790/62858971-27fa3400-bcfc-11e9-9f5a-b1042ff98aa6.png)

6) Finally, open the map settings and look for the "icon image path". This field doesn't only accept twig, it also works properly with different icons for different content. The name should be "paths" rather than "path" . Here is how it looks like with "Geofield Google Map".

![image](https://user-images.githubusercontent.com/2961790/62859156-a060f500-bcfc-11e9-8389-339b642498d8.png)

Same setting is available for "Geolocation Google Maps API - CommonMap", works in the same way, it's just not documented:

![image](https://user-images.githubusercontent.com/2961790/62859345-1feec400-bcfd-11e9-8447-6365621a6314.png)

That's it. Here is how a result might look like:

![image](https://user-images.githubusercontent.com/2961790/62859236-d8683800-bcfc-11e9-8da4-d23f6096332a.png)

**Comment by Itsman-AT** [comment]
@DenoBeno : Did you use a special icon site to download the icons? If not, I will look for royalty free ones.

@p-a-s-c-a-l : I guess this is the task you assigned, right?

**Comment by DenoBeno** [comment]
I have posted this just as a documentation how this can work. I suppose that we shall/should use the same trick on "twins" pages.

As for the icons, don't worry - they are royalty free. https://reliefweb.int/report/world/humanitarian-and-country-icons-2018

**Comment by DenoBeno** [comment]
Oh, by the way there is nothing special in hazards taxonomy. We can do the same for elements at risk. Or any other taxonomy. 

End result would be that "twins" data could look differently on a map, depending on the step where the map is shown.

**Comment by DenoBeno** [comment]
I've implemented several new twins views, they all work perfectly (AFAIK) and just need to be enabled in the template.

Closing the issue
