### ISSUE TITLE
Can we remove default values for "under construction" and "mock-up"?

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/csis#78]
In the EU-GL templates, it would be convenient to have nothing shown as placeholders once we are done with development. However, this is not possible if there are default values defined as it is now.

Can we remove these default values?

@p-a-s-c-a-l : do we need this for anything?
@DanielRodera : if not, can you remove them and check that everything still works as designed (that is - no mockups are shown if no mockups are defined)?

**Comment by p-a-s-c-a-l** [comment]
>  to have nothing shown as placeholders

Sorry, I don't understand what you mean.

We need default values for e.g. external applications, map component, table component, etc.

**Comment by DenoBeno** [comment]
What I mean is that the "mock-up" field has a default value that is shown when no mock up is defined. That's bad, because it prohibits us from producing empty views that could probably be hidden easily. 

I don't think that this is necessary for anything - disabled now.
