### ISSUE TITLE
Why is EU-GL step field multi-value in GL-step?

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/csis#79]
see https://csis.myclimateservice.eu/admin/structure/types/manage/gl_step/fields/node.gl_step.field_field_eu_gl_methodology/storage

![image](https://user-images.githubusercontent.com/2961790/63359598-4f40a900-c36d-11e9-9074-632b5f04d3b9.png)

Why would a step belong to more than one EU-gl step? Is this on purpose or a design error?

**Comment by p-a-s-c-a-l** [comment]
Probably an error.

**Comment by DenoBeno** [comment]
I can't set it to a single value anymore, since there is data in the DB that uses several of these. It doesn't really matter though. Closing.
