### ISSUE TITLE
Setup CI: Jenkins + Maven + TestNG/Junit Docker container

### ISSUE THREAD

**Issue by maesbri** [clarity-h2020/csis#8]

**Comment by p-a-s-c-a-l** [comment]
What are the plans here? There are several components that could benefit from CI, e.g. Table Component, Map Component, table-rest-api, probably also EMIKAT @humerh? Is there a CI process for Drupal Modules @fgeyer16?

IMHO This is also related to the validation task @luis-meteogrid

**Comment by p-a-s-c-a-l** [comment]
Jenkins CI available at http://ci.clarity-h2020.eu/

**Comment by p-a-s-c-a-l** [comment]
@DanielRodera When visiting ci.clarity-h2020.eu, I get:

``504 Gateway Time-out``

BTW, who is the person responsible for maintaining the CI system? We have to ensure that Jenkins security updates, etc.  are installed, etc. Furthermore, we are still missing [lacking http**s**](https://github.com/clarity-h2020/csis/issues/120).

**Comment by p-a-s-c-a-l** [comment]
> Your request for http://ci.clarity-h2020.eu/ could not be fulfilled, because the connection to ci.clarity-h2020.eu (5.79.69.49) could not be established. 

If those issues cannot be resolved in time, we have to move the CI to a more reliable server. I propose to span another Docker container on on our CSIS DEV server.

**Comment by DanielRodera** [comment]
Hi @p-a-s-c-a-l ,
Sorry for the inconveniences, 
It is weird because I can log in without problems as well as other colleagues, but sometimes they cannot connect and they are in the same network as me. I am working on it, I will let you know.

**Comment by p-a-s-c-a-l** [comment]
Yes, same for me here. Sometimes it's working although extremely slowly. ATM it's not.

`tracert ci.clarity-h2020.eu`tells me that there is a timeout at `po-1002.ce02.ams-01.nl.leaseweb.net [81.17.33.135]`.

**Comment by p-a-s-c-a-l** [comment]
> I uploaded the configuration files in the FTP server under the following path:  /clarityftp/CI
Few notes for deploying the Jenkins and the proxy properly:
>- I have split the configuration in two docker-compose files (one for Jenkins and other for the proxy) because the volumes couldn’t be mapped properly if both are in the same configuration file (the docker throws a syntax error).
>- I have used this nginx image (rckrdstrgrd/nginx-proxy) because the Jenkins cannot be proxied if I use the official nginx image. This one is adapted to work with Jenkins properly.

Deploy Jenkins on new DEV Server and [cypress.io UI integration Tests](https://github.com/clarity-h2020/csis-technical-validation/issues/3)

**Comment by p-a-s-c-a-l** [comment]
We've decided to use or https://ci.cismet.de/ Jenkins server. Closing.
