### ISSUE TITLE
Cannot add twins to Gl-steps with empty but required boolean field

### ISSUE THREAD

**Issue by patrickkaleta** [clarity-h2020/csis#80]
Currently it is not possible to add or remove twins in the 1. Study. JSON:API shows the following error message:
![jsonapi-error](https://user-images.githubusercontent.com/42167036/63422474-b5c7d480-c40a-11e9-9001-4165323452b5.png)

Drupal log messages show that the error is caused by an entity validation failure. Apparently JSON:API won't update the GL-step, because of the [changes](https://github.com/clarity-h2020/docker-drupal/issues/90#issuecomment-522552779) made by @DenoBeno. There is now a required boolean `field_is_template`. All Gl-steps created before this new boolean field now cannot be manipulated by the JSON:API.

My suggestion: Remove the `required` attribute from this boolean field. @DenoBeno was there any particular reason why this field was originally set to be required?

**Comment by DenoBeno** [comment]
It's OK not for it to be required. Sorry.
