### ISSUE TITLE
Allow user to skip non-existing steps

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/csis#82]
If no GL step is defined in a study template, then this step will not be shown to the user. Unfortunately this also means that the user will not be able to proceed to the next step...

Please fix.

**Comment by DenoBeno** [comment]
I would suggest to temporarily disable this completely and re-introduce it when we have more time to think of something better. Then it will not be a showstopper anymore.

**Comment by DenoBeno** [comment]
@p-a-s-c-a-l , WDYT?

**Comment by p-a-s-c-a-l** [comment]
Yes, disable and document how to enable it again. ATM I don't know where this functionality is implemented? csis-helpers, as business rule, ...?

**Comment by DenoBeno** [comment]
Patrick has implemented it, it's probably in the csis-helpers.

**Comment by DenoBeno** [comment]
Ah what. I think that I can "disable" it from the rules very easily. That way it's just necessary to delete one step in a rule when we want it again. I'll try.

**Comment by DenoBeno** [comment]
Ah, not even the rule is needed. I'll just set the default value of the "progress indicator" to 10 instead of to 1. All new groups will automatically be in 10-th step, that's more than enough. :-)

https://csis.myclimateservice.eu/admin/group/types/manage/study/fields/group.study.field_progress_indicator

![image](https://user-images.githubusercontent.com/2961790/63591915-7dfa9180-c5b0-11e9-9376-902f30a830f7.png)

@patrickkaleta : once we have a better solution, you can change this field default value to 1 again.

**Comment by DenoBeno** [comment]
Ah no. That doesn't work. Patricks code resets it again.

OK, then I'll add a rule that will trigger on EVERY update of the study. Maybe this will work better.

**Comment by DenoBeno** [comment]
Damn.

I have implemented the rule that updates this value on every group update. And it works.

However, it's spitting out a "warning" message:

> Warning: Creating default object from empty value in Drupal\business_rules\Plugin\BusinessRulesAction\SaveEntityVariableAction->execute() (line 127 of modules/contrib/business_rules/src/Plugin/BusinessRulesAction/SaveEntityVariableAction.php).

@fgeyer16 : I'm afraid, you will have to take a look at this. It's not exactly a showstopper anymore, but it's an ugly workaround. I don't like it when code starts spitting out warnings...

https://csis.myclimateservice.eu/admin/config/workflow/business_rules/update_study_content/edit?destination=/admin/config/workflow/business_rules/collection

![image](https://user-images.githubusercontent.com/2961790/63595566-8b684980-c5b9-11e9-9f3a-d545d534c7f5.png)

**Comment by DenoBeno** [comment]
It appears that all it takes as a workaround is to set the default value of the progress field in the study  to something high (e.g. 10). So this shoudl be OK now, closing.

**Comment by DenoBeno** [comment]
Hm, well it's not really closed... I'll just remove the "showstopper".

**Comment by patrickkaleta** [comment]
> Ah no. That doesn't work. Patricks code resets it again.
> 
> OK, then I'll add a rule that will trigger on EVERY update of the study. Maybe this will work better.

As you commented [later](https://github.com/clarity-h2020/csis/issues/82#issuecomment-528920434) @DenoBeno, setting the default value to 10 works as a workaround for now. **Just to clarify:** the csis helpers module does not overwrite the default value. It only increments the current value by one if certain criteria are met. Value is never reset to 1. IDK why the default value didn't work as workaround before.

**Comment by DenoBeno** [comment]
I don't think that we'll ever work on this. Change to "wontfix"?
