### ISSUE TITLE
Please define usable local effect parameter presets

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/csis#83]
We need to define a list of *sensible* local effect parameter presets as taxonomy entries here:

https://csis.myclimateservice.eu/admin/structure/taxonomy/manage/localeffectsparameters/overview

I have no idea what makes sense and what doesn't make sense, so this needs to be done by someone who understands what is reasonable and what is not. If any instructions are necessary for filling in the data, please ask (should be self-explaining).

@bernhardsk : I am not sure who is the best person to do this, please find it out and assign him/her to it.

**Comment by DenoBeno** [comment]
I suppose that we will have a set of simple adaptation options corresponding to these entries too. Adaptation options can be seen here: https://csis.myclimateservice.eu/adaptation-options-overview

New ones can be defined with https://csis.myclimateservice.eu/node/add/adaptation_options

Those adaptation options that will be used by EMIKAT for re-calculating the local effects just need to be added to the pan-european data package (https://csis.myclimateservice.eu/node/682/edit/simplifieddatapackage
), 

Other can be ignored or added to other data packages as needed.

**Comment by DenoBeno** [comment]
@bernhardsk : please also inform Heinrich as soon as this is available...

**Comment by DenoBeno** [comment]
@p-a-s-c-a-l , @bernhardsk , @humerh : who would be the best person to define these parameters?

**Comment by p-a-s-c-a-l** [comment]
Sorry, I don't know what makes sense in this context, so probably PLINIVS can answer this.

**Comment by DenoBeno** [comment]
@p-a-s-c-a-l : Who do we have from plinius on git? It's all nicknames, I don't know who is who. :-(

**Comment by DenoBeno** [comment]
@RobAndGo : please find someone who can do this and allocate them to this work.

**Comment by DenoBeno** [comment]
I have explained in details what to do to Matteo last tuesday. Unfortunately he isn't on Github

**Comment by DenoBeno** [comment]
@stefanon : how are you /Mattia progressing with this?

**Comment by stefanon** [comment]
Hi Denis,
we are proceeding with the definition of the list of sensitive local effect parameters and values assignment.
Mattia and Francesca are working on this and we expect to finish this task by the end of next week.

**Comment by DenoBeno** [comment]
Any chance of seeing this progress in CSIS?

**Comment by DenoBeno** [comment]
Please put some data in the CSIS ASAP.

**Comment by patrickkaleta** [comment]
Can this issue be closed now? Looking at the [local effects param taxonomy](https://csis.myclimateservice.eu/admin/structure/taxonomy/manage/localeffectsparameters/overview) we have around 50-60 entries. Are we expecting more or is that enough for now @DenoBeno and @stefanon ?

**Comment by DenoBeno** [comment]
I suppose it's enough for now.
