### ISSUE TITLE
What are the add/remove fields in showcases?

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/csis#84]
I have noticed that showcases feature some fields that are only shown in the view mode. 

https://csis.myclimateservice.eu/admin/structure/types/manage/showcase/display

![image](https://user-images.githubusercontent.com/2961790/63580687-a5903080-c595-11e9-9291-e349cc199ad8.png)

Add/remove buttons. I presume these are EVAs?

Do these buttons work? Are they used? Where?

**Comment by patrickkaleta** [comment]
@DenoBeno these buttons are used in the Summary tab of GL-steps. In this tab all selected Twins/showcases etc. are shown as "rendered entities" and there was a request for the user to be able to deselect them in this tab directly without the need of switching back to the Twins tab.

They are not EVAs, they are [token fields](https://csis.myclimateservice.eu/admin/structure/ds/fields) created with DisplaySuite. They are basically Node fields, meaning that they can directly appear when the content is being displayed as "rendered entites".

**Comment by DenoBeno** [comment]
OK, thanks
