### ISSUE TITLE
Page layout templates appear to be broken, please fix

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/csis#86]
I have noticed several issues with page layouts since we have got a new theme. 

For a start, the "inline" fields are formatted in a strange way, even a slightly longer text looks really ugly if "inline" is used. See e.g. 

![Screenshot_2019-08-23_12-33-01](https://user-images.githubusercontent.com/2961790/63586680-353bdc00-c5a2-11e9-8698-e3dc1fd1b68e.png)

Another thing that I noticed is that display suite "fluid" styles aren't fluid anymore. E.g. the showcases are using a fluid two column display style...

![image](https://user-images.githubusercontent.com/2961790/63586788-851aa300-c5a2-11e9-8e49-a6d831544d4f.png)

**Comment by DenoBeno** [comment]
@DanielRodera , could you please take care of this?

**Comment by p-a-s-c-a-l** [comment]
See also https://github.com/clarity-h2020/docker-drupal/issues/47#issuecomment-522973855 and related [issues](https://github.com/clarity-h2020/clarity-theme/issues).

**Comment by RobAndGo** [comment]
In addition, the link to **add a data package** leads to a page which doesn't seem to finish loading...
https://csis.myclimateservice.eu/node/add/data_package_metadata/simplifieddatapackage
Empty box-windows are shown switching between "Select spatial extent" and "Select contributors".
I observed this using both browsers Chrome and Firefox.

**Comment by p-a-s-c-a-l** [comment]
@RobAndGo Please try again, I updated the site.

**Comment by RobAndGo** [comment]
@p-a-s-c-a-l I have reloaded the website, but I still get the same error. I'll try to log out and log back in again.

**Comment by p-a-s-c-a-l** [comment]
So probably its a problem with the permissions. Maybe @DenoBeno or @fgeyer16 can help out here?

**Comment by RobAndGo** [comment]
Using the demo login account, I don't get the error described above. I can use this to add the data resources.

**Comment by RobAndGo** [comment]
@fgeyer16 modified my account to allow me to make edits and now the error no longer appears and I can add resources without problem. Thank you!

**Comment by DenoBeno** [comment]
Maybe I should open a new ticket for this, but I also discovered an error in the edit mode:

![image](https://user-images.githubusercontent.com/2961790/63789335-6fd1ab80-c8f7-11e9-8c70-536a3aa3d6c5.png)

It's not possible to sort elements any more.

It still works if I enable "show row weights", but then one has to type in the numbers...

![image](https://user-images.githubusercontent.com/2961790/63789401-998ad280-c8f7-11e9-88d3-1a5c2fc20f5b.png)

**Comment by DenoBeno** [comment]
@DanielRodera , how is this progressing?

**Comment by DenoBeno** [comment]
@DanielRodera , how is this progressing?

**Comment by DanielRodera** [comment]
Hi all,

@bullz is working on this, he will update you know as soon as he can.

**Comment by DenoBeno** [comment]
I noticed some e-mails about a new theme. Has this been resolved now?

**Comment by DenoBeno** [comment]
Has this been resolved?

**Comment by bullz** [comment]
Should be fix with this last update
