### ISSUE TITLE
Broken logic for "not included Twins 

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/csis#87]
The logic for the not-included twins is broken. It will show as "non-included" the twins that were included in other studies or in the same study  but in other steps.

![image](https://user-images.githubusercontent.com/2961790/63647679-39443700-c725-11e9-96f4-b30d2af50993.png)

Moreover, they will appear several times in non-included - once for every time they were included in another study.

**Comment by DenoBeno** [comment]
@fgeyer16 : this is a nasty little problem. What we need is a list of items that aren't listed in the "included" list yet. What we get is a list of items that aren't listed plus a list of items that are listed anywhere else.

Excluding the items that are listed elsewhere isn't a solution - then we will never get them.

I also tried a different approach: a single table listing them all:

test: https://csis.myclimateservice.eu/study/17/step/1029/view/twins
view: https://csis.myclimateservice.eu/admin/structure/views/view/twins_exposure_1/edit/block_twins_map?destination=/study/17/step/1029/view/twins

I can avoid duplicates here with aggregation, but that doesn't assure I will get the *right* ones for my list. It's a lottery. :-(

**Comment by DenoBeno** [comment]
Maybe we should use this?  https://www.drupal.org/project/other_view_filter

**Comment by DenoBeno** [comment]
This is a bit of a showstopper. If we don't resolve this ASAP, then we have to be *very* careful with demonstrations. Basically, "don't have any twins included in more than one study"

**Comment by DenoBeno** [comment]
@p-a-s-c-a-l : Florian and Patrick are unfortunately unresponsive at the moment. 

Let us try https://www.drupal.org/project/other_view_filter - if it works properly, I can fix this. Can you install it?

**Comment by p-a-s-c-a-l** [comment]
ok

**Comment by p-a-s-c-a-l** [comment]
> Let us try https://www.drupal.org/project/other_view_filter

Done

**Comment by DenoBeno** [comment]
I was able to implement the "exposure twins" using this method and it works as designed, except for one thing: refreshing of the tables when add/remove button is pressed.

@patrickkaleta : I tried to find the differences between the two views but it looks the same to me. Refreshing simply doesn't occur.

**Comment by fgeyer16** [comment]
Obviously there is a difference between the views ;-).

I looked on it and found that the proper display machine name ("included_twins" or "included_twins_ajax) is needed in the js. I changed the display name to "included_twins" for the included display and now at least the included content is updated. 
I could not figure how it works for the available content, yet.

**Comment by DenoBeno** [comment]
Ah nice. Relying on some hidden variables is always a good practice. :-(

Anyway, at least the "other view" filter works. I managed to successfully use it in exposure twins and in the new "study adaptation options" view.

**Comment by DenoBeno** [comment]
Oh jee. We need another patch, see 

- https://www.drupal.org/project/other_view_filter/issues/3011546#comment-13238743
- https://www.drupal.org/files/issues/2019-07-08/3011546-pass-along-contextual-filters-5.patch. 

This is getting annoying. I do hope that this patch will be include n the next module version...

**Comment by fgeyer16** [comment]
Patch is applied. I did not change any view please do this yourself to check if the patch helps.

**Comment by DenoBeno** [comment]
Works perfectly. Thanks.
