### ISSUE TITLE
CLARITY Data Package: Resource categorization (Tags) - deleting tags in the wrong order causes problems

### ISSUE THREAD

**Issue by RobAndGo** [clarity-h2020/csis#89]
@p-a-s-c-a-l @maesbri 
I have encountered the following problem when removing tags from the "Resource categorization (tags)", with slightly different outcomes being produced.

When I duplicate a resource, I want to remove some of the tags which aren't relevant. As an example, consider the new resources which have been duplicated from PI_consecutive-wet-days...:
DI_consecutive-dry-days_historical_19710101-20001231_ensmean
DI_consecutive-dry-days_historical_19710101-20001231_ensstd

![2019-09-02_133225](https://user-images.githubusercontent.com/45385637/64112331-63ca6b80-cd87-11e9-99a7-ee1ac46f3256.png)

I want to remove the two tags:
1. wet-periods
2. consecutive-wet-days

When I remove the last tag in the list first (consecutive-wet-days) and then the wet-periods, everything appears to be ok.
But when I remove the second-to-last tag first (wet-periods) and then consecutive-wet-days, the Categorization box disappears and shows me "Vulnerability change" instead.
![image](https://user-images.githubusercontent.com/45385637/64111799-d76b7900-cd85-11e9-9581-aba4810d0639.png)

In another occurrence, it showed this:
![image](https://user-images.githubusercontent.com/45385637/64111986-4ea10d00-cd86-11e9-9d66-a976ccccd5a8.png)

In another occurrence, it showed me the "Adaptation Options" field instead of the Categorization box.

**Comment by maesbri** [comment]
Hi @RobAndGo , probably is more a question for @DenoBeno or @patrickkaleta as they implemented the tagging of the resources.

**Comment by patrickkaleta** [comment]
I can confirm this bug. It even appears when using the old theme, so it's probably not theme-related. I'm guessing it's probably a bug caused by using the Inline entity form together with the Entity browser (when removing items in the order described above inside a resource, so only using Entity browser and not an Inline entity form, it works as expected).

I'll look further into this once I get some more pressing issues solved. Please for now, watch for a "correct" order when removing tags or work directly with resources and not from within the data package.

**Comment by DenoBeno** [comment]
Is this fixed?

**Comment by DenoBeno** [comment]
I have changed the way tags are chosen to the "Inline entity form" - complex - table view mode. If nothing else, this:
1. is more compact, 
2. allows rearranging the items
3. is more in-line with the way all other items are chosen.

Old: 
![image](https://user-images.githubusercontent.com/2961790/65050558-e1859e00-d967-11e9-8860-410b7b214e4b.png)
New: 
![image](https://user-images.githubusercontent.com/2961790/65050607-f104e700-d967-11e9-8b03-2917ca972268.png)

I can easily modify what is shown in the table, but name+vocabulary isn't so bad IMO. 

@RobAndGo : please try if this helps. 

Please also keep in mind that you may need to save the data package after duplicating the resource and before trying to change the associations. (This is a type of bugs that's interesting to know and report upstreams but that we aren't going to handle on our own.)

**Comment by RobAndGo** [comment]
The new tag-layout is definitely an improvement!!

**Comment by DenoBeno** [comment]
Can we close this now?

**Comment by RobAndGo** [comment]
I think we can - when I delete the tags, I make sure I do it starting with the last tag and working my way up the list.
