### ISSUE TITLE
Business rules for updating Studies not working properly?

### ISSUE THREAD

**Issue by patrickkaleta** [clarity-h2020/csis#96]
Just noticed that [Study 1](https://csis.myclimateservice.eu/study/1/view/intro) shows all GL-steps in its navigation bar twice. That's caused by the fact, that Study 1 now suddently has each GL-step twice.

I'm guessing the new Business rules for handling Studies created by @DenoBeno and @fgeyer16 are not always working as they should and in this case didn't remove the old GL-steps of the study after its Study type was changed.

@p-a-s-c-a-l you are shown as the owner of the new GL-steps of that Study. Could it be that you changed the Study type of the first Study today at around 8:30am? If so then I'm certain that we have a problem with the Business rules.

**Comment by patrickkaleta** [comment]
Just confirmed this bug locally. Changing the Study Type via the Study -> [context tab](https://csis.myclimateservice.eu/study/1/view/context) (as one should do it) lead to the creation of new GL-steps without removing the old ones. Changing the Study type again removed the recently created GL-steps but the "first edition" GL-Steps still remained.

So the business rules seem to work, just not for the really old GL-Steps. I'm guessing this is because of the various additional fields (like `is_template` etc) are missing in those old GL-steps.

I would now just remove those old GL-steps by hand, unless @p-a-s-c-a-l or @therter still need them?

**Comment by p-a-s-c-a-l** [comment]
Yes, I changed the study type from expert to screening. But it should be changed back from screening to expert again. :-)

Instead of trying to implement more and more business rules, I would define some fields like study area and study type as **write-once**. This kind of flexibility is IMHO not needed and introduces a lot of unnecessary complexity that bind resources that are better invested in implementing still missing basic functionality.

**Comment by patrickkaleta** [comment]
> Yes, I changed the study type from expert to screening. But it should be changed back from screening to expert again. :-)
> 

Ok I'll change it back.

> Instead of trying to implement more and more business rules, I would define some fields like study area and study type as **write-once**. This kind of flexibility is IMHO not needed and introduces a lot of unnecessary complexity that bind resources that are better invested in implementing still missing basic functionality.

Honestly, I'm also in favor of a more restrictive CSIS (for now), but @DenoBeno wanted this and it at least seems like those additional features (changing Study type and area) are like 90% done (though, from experience, finishing the last 10% might as well take just as much time :-) ).

Instead of deleting the old GL-steps, I will just unpublish the new ones. Main reason here is that I (and probably others too) are referencing links to those old GL-Steps in all our GitHub issues (since Study 1 is usually our reference study). If I remove the old GL-Steps, all those links will be useless.

**Comment by DenoBeno** [comment]
OK, this has been fixed now. Old studies lacked some fields in GL step, but now all of them have them. This deletng old steps will work also for old studdies now.

**Comment by DenoBeno** [comment]
> 
> 
> > Yes, I changed the study type from expert to screening. But it should be changed back from screening to expert again. :-)
> 
> Ok I'll change it back.
> 
> > Instead of trying to implement more and more business rules, I would define some fields like study area and study type as **write-once**. This kind of flexibility is IMHO not needed and introduces a lot of unnecessary complexity that bind resources that are better invested in implementing still missing basic functionality.
> 
> Honestly, I'm also in favor of a more restrictive CSIS (for now), but @DenoBeno wanted this and it at least seems like those additional features (changing Study type and area) are like 90% done (though, from experience, finishing the last 10% might as well take just as much time :-) ).
> 
> Instead of deleting the old GL-steps, I will just unpublish the new ones. Main reason here is that I (and probably others too) are referencing links to those old GL-Steps in all our GitHub issues (since Study 1 is usually our reference study). If I remove the old GL-Steps, all those links will be useless.

take care: next time when you change the study type for the study one, the gl steps WILL be deleted.
To the best of my knowledge, this is fixed now - closing.
