### ISSUE TITLE
Please install the https://www.drupal.org/project/chart_suite

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/csis#98]
Related to https://github.com/clarity-h2020/csis/issues/91

If we were to add vulnerability curves to dp_vulnerability, it would be convenient to visualise them. I stumbled upon a module that may be just what we need for it:

https://www.drupal.org/project/chart_suite

For reference: This works well together with https://www.drupal.org/project/foldershare module , but I am not sure if we need the "folder share" functionality at the moment.

The module isn't used much and doesn't have much in terms of the documentation, but it's possible to see it in action by visiting the http://dibbs.seedme.org/, clicking on "try now" and requesting a sandbox. I tried it out, and the functionality is quite impressive.

![image](https://user-images.githubusercontent.com/2961790/64778985-3f2b7c00-d55d-11e9-932f-786bf63fa083.png)

I think that we should give it a try.

**Comment by DenoBeno** [comment]
I received answer to first issue report about this module (related to documentation) from the author. That means that he's alive & well - good news.

**Comment by p-a-s-c-a-l** [comment]
Can this be closed? Are we really going to need this? For which purpose?

**Comment by patrickkaleta** [comment]
I don't think we will have the time to integrate this module into our system (at least I won't have the time for it).

**Comment by p-a-s-c-a-l** [comment]
c
